### ISSUE TITLE
Light and world height related kick in 20w49a+

### ISSUE THREAD

**Issue by Earthcomputer** [Earthcomputer/multiconnect#134]
```
[11:32:29] [Netty Epoll Client IO #0/ERROR] (multiconnect) Unexpectedly disconnected from server!
 io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(16) + length(1) exceeds writerIndex(16): PooledUnsafeDirectByteBuf(ridx: 16, widx: 16, cap: 16)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(16) + length(1) exceeds writerIndex(16): PooledUnsafeDirectByteBuf(ridx: 16, widx: 16, cap: 16)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.network.PacketByteBuf.readByte(PacketByteBuf.java:756) ~[minecraft-20w51a-projectmapped-net.fabricmc.yarn-20w51a+build.5-v2.jar:?]
	at net.minecraft.network.PacketByteBuf.readByte(PacketByteBuf.java:756) ~[minecraft-20w51a-projectmapped-net.fabricmc.yarn-20w51a+build.5-v2.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readByte$18(TransformerByteBuf.java:480) ~[main/:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:161) ~[main/:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:123) ~[main/:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readByte(TransformerByteBuf.java:480) ~[main/:?]
	at net.minecraft.network.PacketByteBuf.readVarInt(PacketByteBuf.java:207) ~[minecraft-20w51a-projectmapped-net.fabricmc.yarn-20w51a+build.5-v2.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readVarInt$1(TransformerByteBuf.java:118) ~[main/:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:161) ~[main/:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:123) ~[main/:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readVarInt(TransformerByteBuf.java:118) ~[main/:?]
	at net.minecraft.network.PacketByteBuf.readByteArray(PacketByteBuf.java:91) ~[minecraft-20w51a-projectmapped-net.fabricmc.yarn-20w51a+build.5-v2.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readByteArray$14(TransformerByteBuf.java:461) ~[main/:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:168) ~[main/:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:123) ~[main/:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readByteArray(TransformerByteBuf.java:461) ~[main/:?]
	at net.earthcomputer.multiconnect.protocols.v1_16_4.Protocol_1_16_4.lambda$registerTranslators$2(Protocol_1_16_4.java:100) ~[main/:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readTopLevelType(TransformerByteBuf.java:65) ~[main/:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readVarInt(TransformerByteBuf.java:115) ~[main/:?]
	at net.minecraft.network.DecoderHandler.decode(DecoderHandler.java:25) ~[minecraft-20w51a-projectmapped-net.fabricmc.yarn-20w51a+build.5-v2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	... 33 more
```

**Comment by LordCandyAndy** [comment]
I believe this is the same error: https://github.com/ViaVersion/ViaVersion/issues/2251
viaversion managed to find a fix

**Comment by Earthcomputer** [comment]
No it's not

**Comment by Earthcomputer** [comment]
Likely unrelated to either light or world height.
