### ISSUE TITLE
Log spam when firing arrows in 1.13.2

### ISSUE THREAD

**Issue by Earthcomputer** [Earthcomputer/multiconnect#147]
```
 java.lang.IllegalStateException: Invalid entity data item type for field 7 on entity ArrowEntity['Arrow'/1883, l='ClientLevel', x=198.41, y=72.52, z=189.37]: old=-1(class java.lang.Integer), new=Optional.empty(class java.util.Optional)
	at net.minecraft.entity.data.DataTracker.copyToFrom(DataTracker.java:249) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2.jar:?]
	at net.minecraft.entity.data.DataTracker.writeUpdatedEntries(DataTracker.java:237) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onEntityTrackerUpdate(ClientPlayNetworkHandler.java:556) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2.jar:?]
	at net.minecraft.network.packet.s2c.play.EntityTrackerUpdateS2CPacket.apply(EntityTrackerUpdateS2CPacket.java:41) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2.jar:?]
	at net.minecraft.network.packet.s2c.play.EntityTrackerUpdateS2CPacket.apply(EntityTrackerUpdateS2CPacket.java:17) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:20) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:136) [minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:22) [minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:109) [minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:97) [minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:979) [minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:624) [minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:187) [minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194) [fabric-loader-aafae0b8@net.fabricmc.yarn.1_16_4.1.16.4+build.1-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-aafae0b8@net.fabricmc.yarn.1_16_4.1.16.4+build.1-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-aafae0b8@net.fabricmc.yarn.1_16_4.1.16.4+build.1-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

**Comment by Earthcomputer** [comment]
I improved the error message, still doesn't mean very much: `Invalid entity data item type for field 7(LivingEntity::HEALTH) on entity minecraft:arrow: into=-1(class java.lang.Integer), from=Optional.empty(class java.util.Optional). Trying to copy from ID 7(LivingEntity::HEALTH)`

**Comment by Earthcomputer** [comment]
Wait what, `LivingEntity`?!

**Comment by Earthcomputer** [comment]
Oh I fucked up the debug code. Here's the actual error:
`java.lang.IllegalStateException: Invalid entity data item type for field 7(ArrowEntity::COLOR) on entity minecraft:arrow: into=-1(class java.lang.Integer), from=Optional.empty(class java.util.Optional). Trying to copy from ID 7(unknown)`
