### ISSUE TITLE
issue connecting to 1.12.2 server

### ISSUE THREAD

**Issue by devomaa** [Earthcomputer/multiconnect#162]
Here is what happened on server:
```
[11:15:02] [Server thread/INFO]: pjals joined the game
[11:15:10] [Server thread/INFO]: pjals lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/5 (ld) was larger than I expected, found 7 bytes extra whilst reading packet 5
[11:15:10] [Server thread/INFO]: pjals left the game
```
Client:
```
[13:17:21] [main/INFO]: Connecting to 192.168.1.66, 25565
[13:17:21] [Server Connector #3/INFO]: Protocol version forced to 340 (1.12.2)
```
...thats it (dont mind the time differences, timezones are incorrectly configured :p)

**Comment by Earthcomputer** [comment]
What actions did you do to trigger that error?

**Comment by devomaa** [comment]
i connected to a vanilla 1.12.2 server

**Comment by Earthcomputer** [comment]
What other client-side mods do you have?

**Comment by devomaa** [comment]
On 2021-03-24 15:11, Joseph Burton wrote:
> What other client-side mods do you have?
none

**Comment by devomaa** [comment]
(sending this because you might have not gotten the notif)

**Comment by Earthcomputer** [comment]
Please don't be rude. How do you expect me to fix an issue that only you and no-one else has? Are you on the latest version of multiconnect? (1.3.35)

**Comment by devomaa** [comment]
yes, i have the latest version

**Comment by nonetrix** [comment]
same here with 2b2t.org and I also tried 2b2t.jp since it's the only other server I know with the same version, I would love for this mod to work on these servers for sodium support and etc.

**Comment by nonetrix** [comment]
also saw this in the logs

`20:58:05] [main/INFO]: [CHAT] ==============================
[20:58:05] [main/INFO]: [CHAT] Things might change rapidly
[20:58:05] [main/INFO]: [CHAT] ルールはありません！ -There is no rules-
[20:58:05] [main/INFO]: [CHAT] 
[20:58:05] [main/INFO]: [CHAT] ここはキューです。-This is a queue.-
[20:58:05] [main/INFO]: [CHAT] 順番が来るまでお待ちください。-Please wait until your turn comes.-
[20:58:05] [main/INFO]: [CHAT] 
[20:58:05] [main/INFO]: [CHAT] /spawn 初期リスポーンに戻ることができます。-Return to initial respawn-
[20:58:05] [main/INFO]: [CHAT] Discord : https://discord.2b2t.jp/
[20:58:05] [main/INFO]: [CHAT] 寄付・優先キュー/Donate・Priority Queue: https://donate.2b2t.jp/
[20:58:05] [main/INFO]: [CHAT] ==============================
[20:58:05] [Netty Epoll Client IO #1/ERROR]: Unexpectedly disconnected from server!
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
	at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
[20:58:05] [Netty Epoll Client IO #1/INFO]: Failed to sent packet
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
	at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]`

**Comment by Earthcomputer** [comment]
The only anti-cheat that multiconnect has ever been known to trigger is on hypixel, which is why it disables itself on that server. 2b2t uses waterfall + paper, a combination already known to work if you force the protocol version. If you can specify which plugin that 2b2t in particular uses that breaks it then please tell me.

**Comment by redalpha333** [comment]
I got an error connecting to Wynncraft which uses paper to allow cross version support and I get 

Connection Lost

FastDecoderException: Error decoding packet class Chat with contents: |  0 1 2 3 4 5 6 7 8 9 a b c d e f  |
+--------+----------------------------------------------------------------+--------+
|00000000| 02 01 2f 80 00
+--------+----------------------------------------------------------------+--------+

(BTW I have no other fabric mods and am on the latest version)

**Comment by Earthcomputer** [comment]
That is a server-side error, or another mod you have sending malformed packets. Not multiconnect.

**Comment by Earthcomputer** [comment]
Please, people, this issue isn't a support ticket where you get to post every error you've ever had when using multiconnect. ***The original issue clearly stated that the server was running vanilla***. So, if you're having issues on a modded server please post a separate issue.

**Comment by SenkJu** [comment]
I am having the same issue when connecting to any (vanilla) server below 1.13. No other mods. Latest Fabric for 1.16.5 and multiconnect 1.3.35. 

I can see the world for a split second and then get disconnected.

**Comment by TecnaGamer** [comment]
Version 1.3.34 for Minecraft 1.16.4 seems to work on 1.16.5 when connecting to 1.12.2 servers (note I also have via fabric installed)

**Comment by TecnaGamer** [comment]
![2B73D135-9914-457E-B243-1B6C2ACD8048](https://user-images.githubusercontent.com/34553765/113625371-d9b34a80-962e-11eb-8f1b-37e340ac2e26.png)
Also Minecraft online spat out this message using the latest version on multiconnect

**Comment by devomaa** [comment]
@TecnaGamer has the same issue as me, if anyone else has this issue, if you have it, please provide the server logs, thanks!

**Comment by devomaa** [comment]
this issue might be the same as #132 ?

**Comment by SenkJu** [comment]
Might also be related to #150

**Comment by Earthcomputer** [comment]
Finally fixed. Sorry for how long this took, I've been quite busy lately.

**Comment by devomaa** [comment]
poggers can confirm

**Comment by nonetrix** [comment]
Nice will test out on 2b2t soon really excited to be able to use sodium on 2b2t :D

**Comment by nonetrix** [comment]
yep works fine besides the some odd issues here and there good work!

**Comment by Bluscream** [comment]
```
[08:07:20] [Render thread/INFO]: Connecting to 2b2t.org, 25565
[08:07:20] [Server Connector #1/INFO]: Protocol version forced to 340 (1.12.2)
[08:07:26] [Server Connector #1/ERROR]: Couldn't connect to server
java.util.NoSuchElementException: null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.6) ~[?:?]
	at it.unimi.dsi.fastutil.objects.ObjectArrayList$1.next(ObjectArrayList.java:868) ~[fastutil-8.5.6.jar:?]
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:669) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]
	at net.fabricmc.fabric.impl.registry.sync.trackers.StateIdTracker.recalcStateMap(StateIdTracker.java:78) ~[fabric-registry-sync-v0-0.8.5+3ac43d95c8-23154b7a71e68627.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.trackers.StateIdTracker.onEntryAdded(StateIdTracker.java:63) ~[fabric-registry-sync-v0-0.8.5+3ac43d95c8-23154b7a71e68627.jar:?]
	at net.minecraft.util.registry.SimpleRegistry.md767eb5$lambda$new$0$5(SimpleRegistry:586) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.handler$zij000$setPost(SimpleRegistry:664) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:92) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:66) ~[?:?]
	at net.minecraft.util.registry.DefaultedRegistry.set(DefaultedRegistry:27) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.registerInPlace(SimpleRegistry:1626) ~[?:?]
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Blocks_1_12_2.registerAliases(Blocks_1_12_2.java:159) ~[multiconnect-1.5.6.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Blocks_1_12_2.registerBlocks(Blocks_1_12_2.java:433) ~[multiconnect-1.5.6.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.RegistryMutator.runMutations(RegistryMutator.java:51) ~[multiconnect-1.5.6.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.AbstractProtocol.doRegistryMutation(AbstractProtocol.java:79) ~[multiconnect-1.5.6.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.AbstractProtocol.setup(AbstractProtocol.java:59) ~[multiconnect-1.5.6.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Protocol_1_12_2.setup(Protocol_1_12_2.java:760) ~[multiconnect-1.5.6.jar:?]
	at net.earthcomputer.multiconnect.connect.ConnectionHandler.onSendHandshake(ConnectionHandler.java:113) ~[multiconnect-1.5.6.jar:?]
	at net.minecraft.class_412$1.redirect$bjn000$sendHandshake(class_412.java:537) ~[client-intermediary.jar:?]
	at net.minecraft.class_412$1.run(class_412.java:79) [client-intermediary.jar:?]
[08:07:26] [Server Connector #1/ERROR]: Caught previously unhandled exception :
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "java.lang.Exception.getMessage()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.6) ~[?:?]
	at net.minecraft.class_412$1.run(class_412.java:96) ~[client-intermediary.jar:?]
[08:07:26] [Render thread/INFO]: Connecting to 2b2t.org, 25565
[08:07:26] [Server Connector #2/INFO]: Protocol version forced to 340 (1.12.2)
[08:07:35] [Render thread/INFO]: Connecting to 2b2t.org, 25565
[08:07:35] [Server Connector #3/INFO]: Protocol version forced to 340 (1.12.2)
[08:07:44] [Render thread/INFO]: Connecting to 2b2t.org, 25565
[08:07:44] [Server Connector #4/INFO]: Protocol version forced to 340 (1.12.2)
[08:07:55] [Render thread/INFO]: Connecting to 2b2t.org, 25565
[08:07:55] [Server Connector #5/INFO]: Protocol version forced to 340 (1.12.2)
[08:07:55] [Netty Client IO #15/INFO]: Auto-detected 1.18/1.18.1 (757) for connect.2b2t.org/23.145.208.24:25565
[08:08:05] [Render thread/INFO]: Connecting to 2b2t.org, 25565
[08:08:05] [Server Connector #6/INFO]: Protocol version forced to 340 (1.12.2)
```

i have a similar issue
