### ISSUE TITLE
Connecting to 2b2t.org

### ISSUE THREAD

**Issue by B2H990** [Earthcomputer/multiconnect#163]
When attempting to join 2b2t.org on 1.16.5 I get disconnected with a blank disconnect message and this error appears in my logs.

```
[11:09:38] [Netty Client IO #2/ERROR]: Unexpectedly disconnected from server!
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_271]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_271]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_271]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_271]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_271]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]`
```

**Comment by UltraBlackLinux** [comment]
You need 1.12.2 btw

**Comment by redpenguinyt** [comment]
I had a similar error where my client disconnects with the error:
`java.lang.RuntimeException: Attempted to register object Block{minecraft:orange_banner} twice! (at raw IDs 431 and 65712)`

**Comment by raffel080108** [comment]
Bump
I need a fix for this too, because I'm using a 1.17.1 fabric client and wanna join 2b2t

**Comment by Earthcomputer** [comment]
Please don't bump issues

**Comment by raffel080108** [comment]
Bruh then fix it I guess

**Comment by Earthcomputer** [comment]
I'm not paid for this so I don't give ETAs for fixing issues

**Comment by raffel080108** [comment]
This is over 2 months old.. also I didn't even ask for an ETA..? I just said don't tell me not to say that I need a fix for the same issue if you haven't fixed it yet, what's even wrong about that

**Comment by Earthcomputer** [comment]
If it's so urgent you can fix it yourself and contribute the fix via a PR. It's far more productive than being disrespectful towards someone who has put thousands of hours of their time into software you can download for free.

**Comment by raffel080108** [comment]
First of all, I wasn't disrespectful in any way, you started this conversation. Second of all random guy please stop reacting to his comments. Third of all I still just said that I need a fix for the same issue and nothing else

**Comment by Felix14-v2** [comment]
@raffel080108 , all we can do from the user's side is to provide a clear description of the bug, which would help the author of the mod to find the problem. Just do the best you can. And wait.

**Comment by Earthcomputer** [comment]
Banned, fuck off.

**Comment by raffel8108** [comment]
Excuse me, what the hell? I wasn't rude or disrepectful in any way. I simply said, that I need a fix for the same issue. I never said that I need it urgently, complained about it not being fixed yet or anything else. I don't understand the problem here at all

**Comment by Earthcomputer** [comment]
Locked, and reported to GitHub for creating alt accounts to evade a ban to harass me to fix an issue.

**Comment by Sneakometer** [comment]
I don't know if this is helpful, but i actually can join 2b2t using multiconnect 1.4.15 on fabric 1.17.1 just fine....

**Comment by friendlytherapist** [comment]
> I don't know if this is helpful, but i actually can join 2b2t using multiconnect 1.4.15 on fabric 1.17.1 just fine....

Same but it is only sometimes. Same issue as #227

**Comment by Gaming32** [comment]
I've never had issues joining the 2b2t queue with multiconnect. I also don't have the time to sit through the queue, though, so I don't know if I can connect to the actual server...

**Comment by friendlytherapist** [comment]
> I've never had issues joining the 2b2t queue with multiconnect. I also don't have the time to sit through the queue, though, so I don't know if I can connect to the actual server...

Its not an issue with joining the actual server. Once you get into the queue youre able to join just fine. The problem is getting kicked as soon as you join the queue server. So you dont need much time to test although the problem is random and I think dependant on server lag
