### ISSUE TITLE
random disconnect

### ISSUE THREAD

**Issue by ayunami2000** [Earthcomputer/multiconnect#185]
possibly related to the indexoutofbounds disconnect, but different error message. cannot confirm this mod caused it but with the number of issues ive been having from it i feel it's worth making a bug report on it.

```
Unexpectedly disconnected from server!
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Earthcomputer** [comment]
Unfortunately this bug report doesn't contain enough information for me to do anything with it
