### ISSUE TITLE
Error in logs when joining 1.17 server on 1.17

### ISSUE THREAD

**Issue by B2H990** [Earthcomputer/multiconnect#191]
[15:14:57] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_268.method_1197()" because "â˜ƒ" is null
	at net.minecraft.class_269.method_1191(class_269.java:199) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_634.method_11099(class_634.java:2081) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_5900.method_34173(class_5900.java:130) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_5900.method_11054(class_5900.java:15) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1077) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

**Comment by Earthcomputer** [comment]
Happens in vanilla

**Comment by B2H990** [comment]
yes I was getting random crashes turns out 1.17 is just buggy
