### ISSUE TITLE
1.8 block desyncs

### ISSUE THREAD

**Issue by UltraBlackLinux** [Earthcomputer/multiconnect#202]
Hey there,
(I hope it's not a mod conflict again...)
There seems to be some block desyncing happening in 1.8 where some blocks randomly disappear, here are my logs: https://paste.ee/p/bzTPy
Can I do something about this?
Thanks!

**Comment by Earthcomputer** [comment]
This is the meat of the log:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26227()" because "â˜ƒ" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.13) ~[?:?]
	at net.minecraft.world.chunk.ChunkSection.method_21731(ChunkSection:128) ~[?:?]
	at net.minecraft.world.chunk.PalettedContainer.method_21733(PalettedContainer:269) ~[?:?]
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap$MapEntrySet.forEach(Int2IntOpenHashMap.java:927) ~[fastutil-8.2.1.jar:?]
	at net.minecraft.world.chunk.PalettedContainer.count(PalettedContainer:269) ~[?:?]
	at net.minecraft.world.chunk.ChunkSection.calculateCounts(ChunkSection:127) ~[?:?]
	at net.earthcomputer.multiconnect.protocols.v1_13_2.Protocol_1_13_2.postTranslateChunk(Protocol_1_13_2.java:418) ~[multiconnect-1.4.6.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_10.Protocol_1_10.postTranslateChunk(Protocol_1_10.java:302) ~[multiconnect-1.4.6.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_9_2.Protocol_1_9_2.postTranslateChunk(Protocol_1_9_2.java:88) ~[multiconnect-1.4.6.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator.lambda$submit$0(ChunkDataTranslator.java:74) ~[multiconnect-1.4.6.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Earthcomputer** [comment]
It might be related to #128

**Comment by UltraBlackLinux** [comment]
Hmm multiconnect seems to have some real block rendering issues in 1.8: Now for example there are chunks not even rendering in (mcplayhd.net lobby)

**Comment by Earthcomputer** [comment]
> Hmm multiconnect seems to have some real block rendering issues in 1.8: Now for example there are chunks not even rendering in (mcplayhd.net lobby)

That sounds like #215

**Comment by Earthcomputer** [comment]
I just debugged an issue with the same stacktrace, and it was indeed #128. Closing this is that issue is now fixed.
