### ISSUE TITLE
Joining server

### ISSUE THREAD

**Issue by JackTGG** [Earthcomputer/multiconnect#207]
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:495) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:190) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1140) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index (8941) is greater than or equal to list size (7198)
	at it.unimi.dsi.fastutil.ints.IntArrayList.getInt(IntArrayList.java:267) ~[fastutil-8.2.1.jar:?]
	at net.minecraft.class_1128.method_4807(class_1128.java:125) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1121.method_4799(class_1121.java:40) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1124.method_14491(class_1124.java:23) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.AbstractProtocol.setup(AbstractProtocol.java:60) ~[multiconnect-1.4.5.jar:?]
	at net.minecraft.class_310.handler$bjf000$onDisconnect(class_310.java:10055) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_18096(class_310.java:2223) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_18099(class_310.java:2185) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_412.method_36877(class_412.java:49) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_500.method_2548(class_500.java:234) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_500.method_2536(class_500.java:226) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_4267$class_4270.method_25402(class_4267.java:473) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:359) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class

**Comment by Earthcomputer** [comment]
What's your multiconnect version?

**Comment by JackTGG** [comment]
I'm pretty sure it's 4.9could be a later version tho

**Comment by JackTGG** [comment]
I'll update check and update it when I get beach to my pc

**Comment by Earthcomputer** [comment]
There is no 4.9

**Comment by JackTGG** [comment]
Hmm maybe it was a different mods version lemon check.

**Comment by JackTGG** [comment]
okay so Ima update. it was 1.4.5
