### ISSUE TITLE
Incompatible with Pehkui

### ISSUE THREAD

**Issue by OsoaGH** [Earthcomputer/multiconnect#224]
Here is the error:
```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_2246.<clinit>(class_2246.java:103)
	at net.minecraft.class_3523.<clinit>(class_3523.java:13)
	at net.minecraft.class_5471.<clinit>(class_5471.java:11)
	at net.minecraft.class_5458.method_30573(class_5458.java:44)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:266)
	at net.minecraft.class_2966.method_12851(class_2966.java:44)
	at net.minecraft.client.main.Main.main(Main.java:139)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyVelocityZero(D)D in multiconnect.1_8.mixins.json:MixinLivingEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap multiconnect-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 36 more
Exiting with -1
```
I'm launching from MultiMC, using JDK 16, MC 1.17.1, Fabric Loader 0.11.6 and Fabric API 0.37.2+1.17. multiconnect is on version 1.4.12

**Comment by Earthcomputer** [comment]
What's your mod list?

**Comment by OsoaGitHub** [comment]
Mods:
  [✔️] AFKPeace-1.17-4.6.4
  [✔️] antighost-1.17.1-fabric0.36.1-1.1.4
  [✔️] appleskin-fabric-mc1.17-2.1.3
  [✔️] architectury-2.4.25-fabric
  [✔️] authme-1.17-1.5.0
  [✔️] autoconfig1u-3.3.1
  [❌] bedrockwaters-1.4.3+1.16.4.jar (disabled)
  [✔️] beenfo-1.17.1-fabric0.36.1-1.3.2
  [✔️] betterbeds-1.2.0
  [✔️] betterf3-1.1.5+1.17
  [✔️] BetterPingDisplay-Fabric-1.17.1-1.1
  [✔️] Boat-Item-View-Fabric-1.17-0.0.2
  [✔️] bobby-2.0.4
  [✔️] boosted-brightness-2.1.0
  [✔️] capes-1.2.1
  [✔️] chat_heads-0.3.1+1.17.1
  [❌] chime-1.1.3.jar (disabled)
  [✔️] cleardespawn-1.17.1-fabric0.36.1-1.1.1
  [✔️] clickthrough-1.17.1-fabric0.36.1-0.4
  [✔️] clientsidenoteblocks-2.0+1.17
  [✔️] cloth-api-2.0.54
  [✔️] cloth-config-5.0.38-fabric
  [❌] colormatic-2.2.9+mc.1.16.5.jar (disabled)
  [✔️] CraftPresence-Fabric-1.17.1-Release-1.8.2
  [✔️] CreativeOnePunch-1.2
  [✔️] crowmap-1.17-1.0.1
  [✔️] ctm-fabric-0.5.1+1.17
  [✔️] cullleaves-2.2.0
  [✔️] custom-lan-1.17-v1.0.1
  [✔️] damage-tint-fabric-1.17.1-1.1.0
  [✔️] DCCH-2.0+1.17
  [✔️] deathlog-0.1.3
  [✔️] dynamic-fps-2.0.5
  [✔️] eggtab-2.1.0+1.16-fabric
  [✔️] enhanced_attack_indicator-1.0.2+1.17
  [✔️] enhancedblockentities-0.4.1+1.17
  [❌] EntityCulling-Fabric-1.3.3.jar (disabled)
  [✔️] fabric-api-0.37.2+1.17
  [✔️] fabric-language-kotlin-1.6.3+kotlin.1.5.21
  [✔️] fabricskyboxes-1.17-0.5.2
  [✔️] fabulousclouds-0.2.0
  [❌] fadeinchunks-1.0.0.jar (disabled)
  [✔️] fallingleaves-1.7.3+1.17.1
  [❌] fastbench-2.3.jar (disabled)
  [✔️] fastfurnace-1.17-3.0
  [✔️] ferritecore-3.0.1-fabric
  [✔️] here-be-no-dragons-1.0.0
  [✔️] horse-stats-vanilla-4.1.8
  [✔️] hydrogen-fabric-mc1.17.1-0.3
  [❌] illuminations-1.4.4.jar (disabled)
  [✔️] indium-1.0.0+mc1.17.1
  [✔️] inventory-fix-0.0.1
  [✔️] iris-mc1.17-1.1.1
  [✔️] item-model-fix-1.0.2+1.17
  [✔️] krypton-0.1.4
  [✔️] lambdabettergrass-1.2.0+1.17
  [✔️] lambdynamiclights-2.0.2+1.17
  [✔️] lazydfu-0.1.2
  [✔️] lithium-fabric-mc1.17.1-0.7.3
  [✔️] Loading-Timer-1.5.0-Beta1
  [✔️] MCG-1.17-1.2.3
  [✔️] modmenu-2.0.4
  [✔️] monsters-in-the-closet-1.0.2+1.17
  [✔️] multiconnect-1.4.12
  [✔️] music-duration-reducer-1.2.1
  [✔️] nogizmo-mc1.17-1.4
  [✔️] notenoughanimations-1.3.0
  [✔️] notenoughcrashes-3.4.0+1.17-fabric
  [✔️] okzoomer-5.0.0-beta.2+1.17
  [✔️] Pehkui-2.3.0+1.14.4-1.17.1
  [✔️] PetOwner-1.8.1-1.17-rc1+
  [❌] recipecache-0.2.0-1.17.1.jar (disabled)
  [❌] respackopts-2.3.0.jar (disabled)
  [✔️] RoughlyEnoughItems-6.0.268-alpha-fabric
  [✔️] seamless-loading-screen-1.3.6+1.17.1
  [✔️] semitranslucency-1.1-fabric
  [✔️] Skin_Swapper_1.17-2.1.0
  [✔️] slight-gui-modifications-2.0.1
  [✔️] smoothboot-fabric-1.16.5-1.6.0
  [✔️] sodium-extra-mc1.17.1-0.3.3
  [✔️] spectater-2.0.0
  [✔️] starlight-1.0.0-RC3+fabric.1.17.x
  [✔️] statuseffecttimer-1.0.3
  [✔️] stendhal-1.2.0-1.17.1
  [✔️] TRansliterationLib-1.1.0
  [❌] VanillaFix-2.0.0+beta-29-03-2021.jar (disabled)
  [✔️] visualoverhaul-3.3.0
  [✔️] vt-downloader-1.0.5+1.17
  [✔️] whyamionfire-1.1.1
  [✔️] windowthonk-0.1.1

**Comment by Earthcomputer** [comment]
Ok this is a mod compatibility problem. Could you try to find out which mod it's incompatible with by enabling/disabling some of the mods on the list and seeing if it crashes?

**Comment by OsoaGitHub** [comment]
The incompatible mod is Pehkui

**Comment by OsoaGitHub** [comment]
If I don't respond for a while, I'm sleeping. Good luck sorting out the issue

**Comment by Gaming32** [comment]
This issue appears to be resolved. Should it be closed?

**Comment by Earthcomputer** [comment]
Yep, thanks for pointing that out
