### ISSUE TITLE
Incompatible with bobby

### ISSUE THREAD

**Issue by MrAn0nym** [Earthcomputer/multiconnect#228]
Connecting with 1.17.1 to a 1.16.5 server

Mods: 
- advanced_runtime_resource_pack@0.4.3
- betterbeds@1.2.0
- bobby@2.0.4
- clientcommands@2.5.4
- clientcommands-scripting@1.1.1
- cloth-basic-math@0.5.1
- cloth-config2@5.0.38
- com_moandjiezana_toml_toml4j@0.7.2
- com_typesafe_config@1.4.1
- com_velocitypowered_velocity-native@1.1.0-SNAPSHOT
- confabricate@2.1.0-SNAPSHOT+4.1.1
- cullleaves@2.2.0
- dynamicfps@2.0.5
- enhancedblockentities@0.4.1+1.17
- entityculling@1.3.3
- fabric@0.38.2+1.17
- fabric-api-base@0.3.0+a02b446313
- fabric-api-lookup-api-v1@1.3.0+2f75c6ce18
- fabric-biome-api-v1@3.1.12+3fe74aa118
- fabric-blockrenderlayer-v1@1.1.5+a02b446318
- fabric-command-api-v1@1.1.3+5ab9934c18
- fabric-commands-v0@0.2.2+92519afa18
- fabric-containers-v0@0.1.12+a02b446318
- fabric-content-registries-v0@0.2.4+2e8bd82f18
- fabric-crash-report-info-v1@0.1.5+be9da31018
- fabric-dimensions-v1@2.0.11+6cefd57718
- fabric-entity-events-v1@1.1.0+a02b446318
- fabric-events-interaction-v0@0.4.9+a722d8c018
- fabric-events-lifecycle-v0@0.2.1+92519afa18
- fabric-game-rule-api-v1@1.0.7+6cefd57718
- fabric-item-api-v1@1.2.4+a02b446318
- fabric-item-groups-v0@0.2.10+b7ab612118
- fabric-key-binding-api-v1@1.0.4+a02b446318
- fabric-keybindings-v0@0.2.2+36b77c3e18
- fabric-lifecycle-events-v1@1.4.4+a02b44633d
- fabric-loot-tables-v1@1.0.4+a02b446318
- fabric-mining-levels-v0@0.1.3+92519afa18
- fabric-models-v0@0.3.0+a02b446318
- fabric-networking-api-v1@1.0.13+2e8bd82f18
- fabric-networking-blockentity-v0@0.2.11+a02b446318
- fabric-networking-v0@0.3.2+92519afa18
- fabric-object-builder-api-v1@1.10.9+b7ab612118
- fabric-object-builders-v0@0.7.3+a02b446318
- fabric-particles-v1@0.2.4+a02b446318
- fabric-registry-sync-v0@0.7.10+e2961fee18
- fabric-renderer-api-v1@0.4.4+5f02c96918
- fabric-renderer-indigo@0.4.8+a02b446318
- fabric-renderer-registries-v1@3.2.0+a02b446318
- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
- fabric-rendering-fluids-v1@0.1.13+a02b446318
- fabric-rendering-v0@1.1.2+92519afa18
- fabric-rendering-v1@1.7.0+2e8bd82f18
- fabric-resource-loader-v0@0.4.8+a00e834b18
- fabric-screen-api-v1@1.0.4+155f865c18
- fabric-screen-handler-api-v1@1.1.8+a02b446318
- fabric-structure-api-v1@1.1.13+5ab9934c18
- fabric-tag-extensions-v0@1.2.0+3fe74aa118
- fabric-textures-v0@1.0.6+a02b446318
- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
- fabric-transfer-api-v1@1.1.2+8195aec118
- fabricloader@0.11.6
- hydrogen@0.3
- indium@1.0.0+mc1.17.1
- io_leangen_geantyref_geantyref@1.3.11
- iris@1.1.2-starline+build.471
- isometric-renders@0.2.7
- java@16
- krypton@0.1.4
- lazydfu@0.1.2
- minecraft@1.17.1
- modmenu@2.0.5
- multiconnect@1.4.12
- multiconnect-api@1.4.12
- nofade@1.17-2.0.0
- notenoughcrashes@3.4.4+1.17
- org_spongepowered_configurate-core@4.1.1
- org_spongepowered_configurate-extra-dfu4@4.1.1
- org_spongepowered_configurate-gson@4.1.1
- org_spongepowered_configurate-hocon@4.1.1
- reeses-sodium-options@1.1.2
- seedmapper@b1.4.3
- smoothboot@1.16.5-1.6.0
- sodium@0.3.0+IRIS2-build.120
- sodium-extra@0.3.3
- voxelmap@1.10.15
- worldmesher@0.1

When loading in new chunks this is send in the logs:
```
[14:31:46] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.earthcomputer.multiconnect.protocols.generic.blockconnections.ChunkConnector.onNeighborChunkLoaded(net.minecraft.class_2350)" because the return value of "net.earthcomputer.multiconnect.protocols.generic.blockconnections.IBlockConnectableChunk.multiconnect_getChunkConnector()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.32) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.localvar$bed000$fixChunk(ClientPlayNetworkHandler:2977) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onChunkData(ClientPlayNetworkHandler:664) ~[?:?]
	at net.minecraft.network.packet.s2c.play.ChunkDataS2CPacket.apply(ChunkDataS2CPacket:96) ~[?:?]
	at net.minecraft.network.packet.s2c.play.ChunkDataS2CPacket.apply(ChunkDataS2CPacket:22) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1075) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by MrAn0nym** [comment]
Two other things I noticed:
- In some chunks chests appear
- Barrels are visible as normal

**Comment by Earthcomputer** [comment]
This looks like a mod incompatibility. Could you try removing/readding some mods and let me know which mod it's incompatible with?

**Comment by MrAn0nym** [comment]
Turns out it's [Bobby](https://github.com/Johni0702/bobby)… I'll create an issue there
