### ISSUE TITLE
Crashed latest

### ISSUE THREAD

**Issue by BlueTree242** [Earthcomputer/multiconnect#278]
```
java.util.ConcurrentModificationException
	at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:443)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:335)
	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.addAll(ObjectOpenCustomHashSet.java:298)
	at net.minecraft.class_2370.lockRealEntries(class_2370.java:1592)
	at net.earthcomputer.multiconnect.protocols.generic.AbstractProtocol.postMutateRegistry(AbstractProtocol.java:161)
	at net.earthcomputer.multiconnect.protocols.generic.AbstractProtocol.lambda$doRegistryMutation$1(AbstractProtocol.java:80)
	at java.base/java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:589)
	at net.earthcomputer.multiconnect.protocols.generic.AbstractProtocol.doRegistryMutation(AbstractProtocol.java:80)
	at net.earthcomputer.multiconnect.protocols.generic.AbstractProtocol.setup(AbstractProtocol.java:59)
	at net.minecraft.class_310.handler$bal001$onDisconnect(class_310.java:7984)
	at net.minecraft.class_310.method_18096(class_310.java:2225)
	at net.minecraft.class_310.method_18099(class_310.java:2185)
	at net.minecraft.class_412.method_36877(class_412.java:49)
	at net.minecraft.class_500.method_2548(class_500.java:237)
	at net.minecraft.class_500.method_2536(class_500.java:229)
	at net.minecraft.class_4267$class_4270.method_25402(class_4267.java:458)
	at net.minecraft.class_350.method_25402(class_350.java:359)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:218)
	at net.minecraft.class_310.method_1523(class_310.java:1145)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

Minecraft 1.18
Fabric latest
Attempted to join 1.12 server with viaversion, viabackwards and viarewind outdated. choosing 1.12 as version to connect with.

I could fix it if i had time lol, xd

**Comment by BlueTree242** [comment]
i attempted to join again but it didn't crash, just a note

**Comment by Earthcomputer** [comment]
Please post the full log

**Comment by BlueTree242** [comment]
it clearly explains where the problem is in code

**Comment by BlueTree242** [comment]
i dont know where the log is i ran minecraft again and new logs were made

**Comment by Earthcomputer** [comment]
No it does not, it's caused by a previous error. Stop trying to cheeky.

**Comment by BlueTree242** [comment]
at net.earthcomputer.multiconnect.protocols.generic.AbstractProtocol.doRegistryMutation(AbstractProtocol.java:80)
at net.earthcomputer.multiconnect.protocols.generic.AbstractProtocol.setup(AbstractProtocol.java:59)

**Comment by BlueTree242** [comment]
if this not enough ill send full logs just wait for me to find them

**Comment by Earthcomputer** [comment]
My goodness man I said full logs not two extra lines

**Comment by BlueTree242** [comment]
they are not extra, its in the stacktrack

**Comment by Earthcomputer** [comment]
> it clearly explains where the problem is in code

If you really think you know where the problem is then go and make a fucking PR to fix it

**Comment by BlueTree242** [comment]
ok wait its fine im sending logs

**Comment by BlueTree242** [comment]
> > it clearly explains where the problem is in code
> 
> If you really think you know where the problem is then go and make a fucking PR to fix it

nah i don't know much about protocols lol 😅

**Comment by Earthcomputer** [comment]
Then shut the fuck up and give me logs.

**Comment by BlueTree242** [comment]
> Then shut the fuck up and give me logs.

Pls no swearing, its ur mod not mine. Also i am not on pc + the logs are lost bc i started mc again like 10 times, ill find it just be patient

**Comment by BlueTree242** [comment]
[2021-12-01-2.log.gz](https://github.com/Earthcomputer/multiconnect/files/7650008/2021-12-01-2.log.gz)

Finally found the log, sorry for the wait

**Comment by Earthcomputer** [comment]
This is unlikely to occur after the rewrite. Please respond if it does.

**Comment by Earthcomputer** [comment]
Can you confirm that you are using the 1.19 version, and if you are, post the log?
