### ISSUE TITLE
Not Loading and Rendering Chunks - 1.18 running Multiconnect 1.5.2 (& 1.5.1) when connecting to 1.17.1 Server 

### ISSUE THREAD

**Issue by LOLboy199** [Earthcomputer/multiconnect#285]
A set of 9 specific chunks consistently won't load on one of my servers. It's not only not rendering, it seems like the chunks aren't loaded as I fall through and get stuck in the world if I walk into them. If I get close to them and look through them it also causes a line of chunks on the opposite side not to render. 

I tried to recreate it in other parts of the world and in another 1.17.1 server but cannot. 

Running 1.17.1 with no mods loads the chunks fine, but loading the server with only Multiconnect (and/or with other mods) consistently will not load these chunks. Even if I use the mod "Anti Ghost" to request the chunks be reloaded from the server. 

I wish I could be more helpful, but that's pretty much all the info I can figure out. (Side note, love the mod btw thx.) 

![2021-12-06_20 20 05](https://user-images.githubusercontent.com/89465021/144955877-18c6fe36-9c43-4f60-9737-ffa977162749.png)
![2021-12-06_20 26 24](https://user-images.githubusercontent.com/89465021/144955882-497de79b-3210-4648-9609-8ff94a59b49a.png)
![2021-12-06_20 18 12](https://user-images.githubusercontent.com/89465021/144955888-8e00e30b-0d7f-4640-8b46-7ec675225c92.png)

**Comment by LOLboy199** [comment]
After looking at 1.18.1 release candidate 2, this could possibly be a 1.18 glitch and not a multiconnect glitch. Still unsure.

**Comment by Earthcomputer** [comment]
I will wait for 1.18.1 before looking at this then

**Comment by LOLboy199** [comment]
Running the newest version of multiconnect as of today December 12th on 1.18.1- the exact same chunks still will not load.

**Comment by Andrews54757** [comment]
I've had this problem too. Some chunks will not load. Using 1.18.1 on a 1.17.1 server with multiconnect 1.5.6. A stacktrace is spammed in the logs.

```
Failed to translate chunk 20, 7
java.lang.IndexOutOfBoundsException: readerIndex(2069) + length(1) exceeds writerIndex(2069): UnpooledHeapByteBuf(ridx: 2069, widx: 2069, cap: 2069/2069)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
	at net.minecraft.class_2540.readByte(class_2540.java:1013)
	at net.minecraft.class_2540.readByte(class_2540.java:1013)
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readByte$21(TransformerByteBuf.java:793)
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:257)
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:198)
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.readByte(TransformerByteBuf.java:793)
	at net.minecraft.class_2540.method_10816(class_2540.java:344)
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readVarInt$3(TransformerByteBuf.java:194)
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:257)
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:198)
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.method_10816(TransformerByteBuf.java:194)
	at net.minecraft.class_2834.method_12289(class_2834.java:80)
	at net.minecraft.class_2841.method_12326(class_2841.java:163)
	at net.minecraft.class_2826.method_12258(class_2826.java:158)
	at net.earthcomputer.multiconnect.protocols.generic.ChunkData.read(ChunkData.java:48)
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator.lambda$submit$1(ChunkDataTranslator.java:123)
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationTask.run(ChunkDataTranslator.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationFutureTask.run(ChunkDataTranslator.java:271)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by MeFisto94** [comment]
Same symptom, different stack trace:
```
[00:25:34] [Server Connector #1/INFO]: Discovered server protocol: 754 (1.16.5)
[00:25:36] [Netty Client IO #2/ERROR]: Failed to find lambda 1 in caller class net.minecraft.class_2678 at line 43
[00:25:36] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:25:37] [Render thread/INFO]: [CHAT] xxx joined the game
[00:25:37] [Render thread/INFO]: Loaded 53 advancements
[00:25:37] [multiconnect chunk translator #2/ERROR]: !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[00:25:37] [multiconnect chunk translator #2/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[00:25:37] [multiconnect chunk translator #2/ERROR]: Minecraft version: 1.18.1
[00:25:37] [multiconnect chunk translator #2/ERROR]: multiconnect version: 1.5.7
[00:25:37] [multiconnect chunk translator #2/ERROR]: Server version: 754 (1.16.5)
[00:25:37] [multiconnect chunk translator #2/ERROR]: Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:b4ccdaa:1625) <- Paper
[00:25:37] [multiconnect chunk translator #2/ERROR]: Chunk pos: 320, -579
[00:25:37] [multiconnect chunk translator #2/ERROR]: Vertical strip bitmask: {0, 1, 2, 3, 4, 5}
[00:25:37] [multiconnect chunk translator #2/ERROR]: Dimension has sky light: true
[00:25:37] [multiconnect chunk translator #2/ERROR]: Full chunk: true
[00:25:37] [multiconnect chunk translator #2/ERROR]: Compressed packet data: H4sIAAAAAAAA/+1ZT2wc1RmfsdeOEwfHM7ue3aSR5XkY25FMlckQ4aAeYrOEVuHAghYh1ENmHSYuXOJEsPTmNdtqKrk9RBWKq6gioF4CVFHVSEitqsYHn6KopWChnuCCT1V76qGnfv/ezOzsrG2gkaUqH2R+89437/v93vfevHlvPfpi4RHDNQef/e34qXOFvmd+dWzz/Eqftd9m09W1XNeSO7mU5uFStMbgERtrsOiKlxop/bSN/9lSb+fE5lt+xNUeuC2xW8njrst3ypZWSFebZGdNArEFZbg4VkAMQRBoVtvlx5QbBFakFVS4stXCgtOgxxxitIECWJVtu9ING9hdDGDZoAYVoUDQbjuB64LbDRxUrFwHw7vLSBEoiGc7jgv/gK2C4StEOxWEViVqKVRrRS0L/FDfQgoH6G3XDuCiIHIY2EqBICeE4ApUBHBBLRBVgYKpsAGS4BYehFLgWmEAaKkp6JEbhDZqch3od2XVcsMgaFVa0C60AFfVVBjMQAZAZ2jNtGxLgRCgg//DBmZBTQUNZFUQ+QreNNwQuKCdE14jVPgA9AcSCO3CsOGAQOWEUAuRwpCbB+FSFCn7aBhWomjVhWQtzUQVdcKFVtEqPoCtFNIo7BU0VOvr69cA19Ggl+tXTqxfQ1wnXsawG08wvqZRgc4TYbiE4VMYEaqZVZXYtMYrmleFPxJ+xhCR4v5YsCmoBOvC+4rgLcVIPCca0WoOb0LLRrj+TghRpzAN4XojPCH8mmda8ArjkmK+JeZfiurYb9VIhX+hmzGfH7tPsUMcPug7IyafEH0aoS+CZI0MotUzyPaHDBJvXSMQEi0SM2pBnJ9QCDRvln93y+FPSb13797sPbINxQi1UgZU2rcxy1VKzTKATS5woCrgY1CsJtV7tnspjlnNDxR4M5vyxZrUvQ5+Jfz1NP/XECA8OrYifkIoz27E/KRo4wogVMK8ocemkzgvpPRoIaqqdjXdmwTVDoj8iuYto1LiVhv4LqX4aYZXdcVCT/7ZHfl2wA1B1WT+aUb9ZlNpUrP05j/y3cIhw9w8Xzj3TN+zg9VkQ2C7nQgfJPgaM/peJxY9/hqT3yolX93/kQGPz+gzgtmElu8yEj+iLqMVM/jN+Ysxr0Zfo8d8Mab4szosbxeiai9HDr+v0WPeGIUXlrDTLxIGYzn8tL1CTNNwobyck4LOHmklFvHj+GMFYxguAjrA/2qdMayxnsCyJHR5mfkBuyjD5psB1TXDnnLSSrwMMpHmJdTlhL+ZQayHDVdzWT8IdW8K5vL3tjC8tMz9vdRkDBEdkqFtmegoNuxqBBWhCCYh3CLdcDcrieIqtCd+Qt0FRCVbYKU0uoJcgf1eilhAFFFVJcaW4I78aDSVkR+DA78ttCpL11VRXs7hZYxibFk4NqQyX4fe1EtQS2X4aZEU2uZbLaqYfkviW938ofDTmAA/TZKIksRNMoOk9LrZzR/rEH63iby2mmnG/JzgSot5I+QlWuQNSBby41MaiV+GB3V19z+rI1nYK5xXhAinCIaBOUS9h7nbicATCW8U87eIv5Li1+t/iqZTR/oDUWlJ1pH/6HXiF75yzL8cCTLvJdbBvFbM28v2/D2qrK9TNyrrpMNqRpydpmQJBwmxnHT3G1ucryRvlWh9nUqAPAlERzz5K9lWX8fiRHMkRpxXujjyz8JBw6wOFs71bZ4/tNJX9GXEfBmxosqsvN/m61qMvyJc8v15LvrVeSrC5ZTQnepo0mWlaoy8Z0mQX4ZS8lLswA+8aez9zS5J+FLVprDVKs/panWeMlZCdAl57UuQH9Rf4JSOIvPiZqI6b/U0V/hVJz+v6Dn8glXhj4VKR3KZUvz1DOp3SfihW5jbkoSH/Cf8VtL/UopXJ2wH/hwbS8SBOsiRC4iz0IXYfhHHg2LK0iZ6rKpMYI0ljQtd0yHHwhTiFAtgbpSIl7AKoFxBhTpoiRMd/BlMlSmrgCVG7rotOvRWu5M/iNFH/hCInhD+J/L4i2m+UpafsSTIQ2ArHuwsfznLT4g7PuAvCtJOsET8cf5d7jeUU/xFL0HkL/o28ePU15OezPd4U1Zs4ralKhNRz8d5vRdNdqBWZhebtiptSpGXnsN5Q8/j6uLRMBTjZcyj3WDRf5KILb+JWJVpmtURm9eLWqyou+XXOjDFayERYJPxSULiby4Lv5Pwex3Ns2eNOIuJgrroqNPXtOgBf7NJeS8LAhHlnfFJxmKGnwI7T/vZ9HsZ7NRh8Xsr++wmY1mw2YllQeanYtP/Pu0tHJ8T7RR356d5DEXEzD7/a/ET+vBNdJAffzwNcbi78m8LKuHF974s2EQdsK9v8hm1SWiXGZGQVn7k83P1LAN/y8GXL1q1HHgXvfhgLtn1hN/q4G8yEi+sh4SwHjIv7HhZByEEmEYdnhNyXvDAICeWZWvkbGHYMPsODVY3z597tjCy0lfFJri01U/XaHjrPMESrLGymjWGd/BuoieECcxYxUecNIIjjfPgcEL6cODCW6VNMq5GfEao12u0KtXrmr+Wxy9FFIE6HI9uYQGbp1ci9J8ABH7MBPIyWiGOyBi25Q1EWfgplvDTph/4XkIdb2A5wGqNNZwoFCskPYSOXxP0CJEvwRrU+x6dWAlpSD19AEwOGWGDkxZm+DqQNumdiOE0eoJ+Fr0OJP5Q89MdISWR4zo9sINX42nNX0t0BMKfxqLosfiwkeaXw3REh743avxVHhOkyWWJjhRC/vHF4cnIVSmEJs0O7DhP6jOd5kch5WS7vsN5Q1tMF3Zg3EXQsZx+sNd5NhXwaPQzEmbPRNxKRdQbW/EA4MuZzSDoJtU9dcT8u9s1/LML8WneGeKF9SXBUPSEAZ8O5UwPFZVs//fW78SOwstI/ac/L2V4U6gkD7ByWvqU6oRLQtdx0t7xJ40u00tv/EuKpXUI8gui+K9u1kzH/i5zVk34u07MUt7zybVLZuZL0WljGez6ZSA+qX9T/r3asZsE7z0A/j38MBDbzWOM72XyfzODZF6PIFxfeZtLlUie07izAIGbfKf5jmm/bHL5p99b7xMe079BP4U4Z93ysX7uba6fizzfhx2T18JfzvHneet9OWm+73FOnrJaMQHbLSa2j7ECO8s/eG3guHFoxNw83/f38YMfmn869Gtza/zT8c/G/zb+yfhfx6+ZPxluD79j/tL8wLxu/s68bX4+/ntzq89ou0MbE23XXAuGqqNtF8sLGq21RfJTuSH++cQ/uvYo+U9GrrG2OIr1ZsFN+wPAyubJ9kVzbbGyeRZ5Lg4tIF/UGPopxDfXnq5semvsr2EZ0Du8aB5eHIV6KbOOBfcw4EIqvuBJwYlMfeyP5o32o0Pd+nQ70A/+c1pf4n/UWHOHzoE+o53o37Ta8+bhAPu7iPFi/afWXHPItSBvgbTfYIzydY227wIeXLUKUL4r9fNZv5SVYJAX5yIi6jfaF3P8a+RH/UZn/9z+G+7QcyDdaE9Blm9s91c2z9y/egPqt8/cJ/+X7L/e4f9S/HfJX8T2rrd2Af3Qj8tx/CnCYiWlZzJP/yTh2d7+/jZk+QLoASrDmNiGizFyGeI/dgDjb7LfMNhvHkD/6NXrU4ZxYO458t/V/jl8oP/GF9AP7N/23MIi61+F/kEesH/b1D/oR397OtUP9E/O7aQf4nM98rePg5ihM/chPuQppU+M/eYvwF84fjftH+IHjt+F2/n7V9H/lfinkvYQdADjgz4cx4ULGNM1SsbxLwaOb8fjiO9vf6zf1f3jcTKMPgf5jcFufYY5rf3GyTy/ewmvDugzJowc/8QgwdXKVME4cGYD/TdS+gsT2wPmDxZGQCcMKeQV/G33eWPAMAZmjOeh/9t6nAzjyNWXbs8Yg6dfT8U3jtB18HGoHG1s3ZbbXL/R2Pp4xTjQ6edeHvgoBHjtPubP+KrbP7mCld8fuYxDsp32CFKlef+yFA+udMXI2qHcyr/g9edn49uM/QcvR/JajtD1X7vSfjtj0R/hZejTPD+JfvcBsQ+s9HCYNKSOLn5MUn6Y8yDr+82f4TLcK9i3tOFXtroKj7+O6Nye7X58NCfEuw9GGdvhS11Vr36E+sx/37lzAVZL80La98iD1LJXM/946TvGK1t3PoT3e/jlYykP53d2eJ+E5VjH+Bsv46QcaC19DzqxcmGfJO1m/f/A8X9q687KfivZi00WDhqfjH9gfgqb2s/GPx/fgg3uSh+5lOL1+NTT+yPtBaUI+yb2h7/P5W9r4ew+8asJvpnYH36z/DzfrOwP/371O7bLuz/y0B7aQ3to/2f2X1eZn7FIMwAA
[00:25:37] [multiconnect chunk translator #2/ERROR]: Failed to translate chunk 320, -579
java.lang.IllegalArgumentException: No value with id 9670
	at net.minecraft.class_2359.method_39974(class_2359.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_2834.method_12289(class_2834.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_2841.method_12326(class_2841.java:163) ~[client-intermediary.jar:?]
	at net.minecraft.class_2826.method_12258(class_2826.java:158) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkData.read(ChunkData.java:48) ~[multiconnect-1.5.7.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator.lambda$submit$1(ChunkDataTranslator.java:123) ~[multiconnect-1.5.7.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationTask.run(ChunkDataTranslator.java:264) [multiconnect-1.5.7.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationFutureTask.run(ChunkDataTranslator.java:271) [multiconnect-1.5.7.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[00:25:37] [multiconnect chunk translator #2/ERROR]: Failed to translate chunk 327, -574
java.lang.IllegalArgumentException: No value with id 71
	at net.minecraft.class_2359.method_39974(class_2359.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_2834.method_12289(class_2834.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_2841.method_12326(class_2841.java:163) ~[client-intermediary.jar:?]
	at net.minecraft.class_2826.method_12258(class_2826.java:158) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkData.read(ChunkData.java:48) ~[multiconnect-1.5.7.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator.lambda$submit$1(ChunkDataTranslator.java:123) ~[multiconnect-1.5.7.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationTask.run(ChunkDataTranslator.java:264) [multiconnect-1.5.7.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.earthcomputer.multiconnect.protocols.generic.ChunkDataTranslator$TranslationFutureTask.run(ChunkDataTranslator.java:271) [multiconnect-1.5.7.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[00:26:05] [Render thread/INFO]: Stopping!
```

**Comment by Earthcomputer** [comment]
This is unlikely to occur after the rewrite. Please reply if it does.
