### ISSUE TITLE
Mod incompatibility with sodium

### ISSUE THREAD

**Issue by Sneakometer** [Earthcomputer/multiconnect#288]
Joining any 1.8 server with latest multiconnect 1.5.3 and sodium crashes the game with the following exception:
```
java.lang.IllegalStateException: Tried to mark light data as ready for chunk [3, 16] but it hasn't been loaded yet
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkTracker.onLightDataAdded(ChunkTracker.java:92)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkLightAdded(SodiumWorldRenderer.java:304)
	at net.minecraft.class_638.handler$blj000$postLightUpdate(class_638.java:4578)
	at net.minecraft.class_638.method_39849(class_638.java:530)
	at net.minecraft.class_634.method_38543(class_634.java:2198)
	at net.minecraft.class_634.method_38545(class_634.java:2183)
	at net.minecraft.class_634.redirect$bmn000$starlightCallUpdateImmediately(class_634.java:12426)
	at net.minecraft.class_634.method_11143(class_634.java:2183)
	at net.minecraft.class_2676.method_11560(class_2676.java:37)
	at net.minecraft.class_2676.method_11054(class_2676.java:11)
	at net.minecraft.class_634.handler$bdk000$afterOnChunkData(class_634.java:2493)
	at net.minecraft.class_634.method_11128(class_634.java:662)
	at net.minecraft.class_634.handler$bgl000$onOnRenderDistanceCenter(class_634.java:8984)
	at net.minecraft.class_634.method_20320(class_634.java:2234)
	at net.earthcomputer.multiconnect.protocols.v1_13_2.Protocol_1_13_2.updateCameraPosition(Protocol_1_13_2.java:1583)
	at net.earthcomputer.multiconnect.protocols.v1_13_2.Protocol_1_13_2.onSendPacket(Protocol_1_13_2.java:537)
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Protocol_1_12_2.onSendPacket(Protocol_1_12_2.java:800)
	at net.earthcomputer.multiconnect.protocols.v1_11_2.Protocol_1_11_2.onSendPacket(Protocol_1_11_2.java:131)
	at net.earthcomputer.multiconnect.protocols.v1_9_4.Protocol_1_9_4.onSendPacket(Protocol_1_9_4.java:79)
	at net.earthcomputer.multiconnect.protocols.v1_8.Protocol_1_8.onSendPacket(Protocol_1_8.java:1016)
	at net.minecraft.class_2535.handler$bdi000$onSend(class_2535.java:2553)
	at net.minecraft.class_2535.method_10752(class_2535.java)
	at net.minecraft.class_2535.method_10743(class_2535.java:172)
	at net.minecraft.class_634.method_2883(class_634.java:742)
	at net.minecraft.class_746.method_3136(class_746.java:282)
	at net.minecraft.class_746.method_5773(class_746.java:225)
	at net.minecraft.class_638.method_18646(class_638.java:218)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_638.method_32124(class_638.java:201)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:197)
	at net.minecraft.class_310.method_1574(class_310.java:1751)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

Tested with Minecraft 1.18
Multiconnect 1.5.3
Latest Sodium 0.4.0-alpha5+build.795

**Comment by Earthcomputer** [comment]
This seems like an interaction between multiconnect, sodium and starlight. All three are required to reproduce the issue
