### ISSUE TITLE
Incompatibility with Colormatic

### ISSUE THREAD

**Issue by Gaming32** [Earthcomputer/multiconnect#293]
## Disclaimer
I have only tested this on 1.18.1 multiconnect. I imagine the same issue occurs on 1.18.

## Testing I did
I forced the version to each major version of Minecraft on the server `viaproxy.lenni0451.net`, which allows 1.8 &ndash; 1.18.1 clients to join. I then tested it on a Vanilla 1.8.9 server. The following error log is from this last test.

## Other mods that could be affecting this

I have the [OpenAuthMod](https://github.com/RaphiMC/OpenAuthMod) installed, which uses a plugin channel and also uses the multiconnect API to allow that plugin channel through. Note that this issue occurs with or without OpenAuthMod, however.

## Mod versions

multiconnect &mdash; 1.5.6
OpenAuthMod &mdash; 1.1.1

## Error log
```
[13:26:44] [Netty Client IO #5/ERROR]: !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[13:26:44] [Netty Client IO #5/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[13:26:44] [Netty Client IO #5/ERROR]: Minecraft version: 1.18.1
[13:26:44] [Netty Client IO #5/ERROR]: multiconnect version: 1.5.6
[13:26:44] [Netty Client IO #5/ERROR]: Server version: 47 (1.8)
[13:26:44] [Netty Client IO #5/ERROR]: Server brand: vanilla
[13:26:44] [Netty Client IO #5/ERROR]: Compressed packet data: H4sIAAAAAAAA/2NkYGBPZ2BgFGFPSU1LLM0pYQAAZWFd0BIAAAA=
[13:26:44] [Netty Client IO #5/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / minecraft:dimension_type]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / minecraft:dimension_type]
	at net.minecraft.class_5455.method_30534(class_5455.java:56) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5455.method_30530(class_5455.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.handler$zhc000$fixDimensionType(class_2678.java:566) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.<init>(class_2678.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.<init>(class_2678.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:417) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:469) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils$DebugDecoderHandler.decode(DebugUtils.java:301) ~[multiconnect-1.5.6.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	... 35 more
[13:26:44] [Render thread/ERROR]: Writing packet:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@348fb5dc[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@4dc5babf[Wrapped task = com.replaymod.recording.packet.PacketListener$$Lambda$6717/0x000000010105d260@6910dc3]] rejected from java.util.concurrent.ThreadPoolExecutor@de364d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) ~[?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:748) ~[?:?]
	at com.replaymod.recording.packet.PacketListener.save(PacketListener.java:203) ~[replaymod-1.18.1-2.6.3.jar:?]
	at com.replaymod.recording.packet.PacketListener.lambda$save$1(PacketListener.java:168) ~[replaymod-1.18.1-2.6.3.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.11.jar:?]
[13:26:44] [Render thread/ERROR]: Writing packet:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@56aacddf[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@6edf9278[Wrapped task = com.replaymod.recording.packet.PacketListener$$Lambda$6717/0x000000010105d260@2737fb2a]] rejected from java.util.concurrent.ThreadPoolExecutor@de364d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) ~[?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:748) ~[?:?]
	at com.replaymod.recording.packet.PacketListener.save(PacketListener.java:203) ~[replaymod-1.18.1-2.6.3.jar:?]
	at com.replaymod.recording.packet.PacketListener.lambda$save$1(PacketListener.java:168) ~[replaymod-1.18.1-2.6.3.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.11.jar:?]
[13:26:44] [Render thread/ERROR]: Writing packet:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@4f5e5174[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@576cf611[Wrapped task = com.replaymod.recording.packet.PacketListener$$Lambda$6717/0x000000010105d260@4f1ab97d]] rejected from java.util.concurrent.ThreadPoolExecutor@de364d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) ~[?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:748) ~[?:?]
	at com.replaymod.recording.packet.PacketListener.save(PacketListener.java:203) ~[replaymod-1.18.1-2.6.3.jar:?]
	at com.replaymod.recording.packet.PacketListener.lambda$save$1(PacketListener.java:168) ~[replaymod-1.18.1-2.6.3.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.11.jar:?]
[13:26:44] [Render thread/ERROR]: Writing packet:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@af57022[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@2d56d7d2[Wrapped task = com.replaymod.recording.packet.PacketListener$$Lambda$6717/0x000000010105d260@379d4254]] rejected from java.util.concurrent.ThreadPoolExecutor@de364d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) ~[?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:748) ~[?:?]
	at com.replaymod.recording.packet.PacketListener.save(PacketListener.java:203) ~[replaymod-1.18.1-2.6.3.jar:?]
	at com.replaymod.recording.packet.PacketListener.lambda$save$1(PacketListener.java:168) ~[replaymod-1.18.1-2.6.3.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.11.jar:?]
[13:26:44] [Render thread/ERROR]: Writing packet:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@23c5181d[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@5fc26a53[Wrapped task = com.replaymod.recording.packet.PacketListener$$Lambda$6717/0x000000010105d260@2100c1d]] rejected from java.util.concurrent.ThreadPoolExecutor@de364d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) ~[?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:748) ~[?:?]
	at com.replaymod.recording.packet.PacketListener.save(PacketListener.java:203) ~[replaymod-1.18.1-2.6.3.jar:?]
	at com.replaymod.recording.packet.PacketListener.lambda$save$1(PacketListener.java:168) ~[replaymod-1.18.1-2.6.3.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.11.jar:?]
[13:26:44] [Render thread/ERROR]: Writing packet:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@2cf48429[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@2588f563[Wrapped task = com.replaymod.recording.packet.PacketListener$$Lambda$6717/0x000000010105d260@277a652b]] rejected from java.util.concurrent.ThreadPoolExecutor@de364d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) ~[?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:748) ~[?:?]
	at com.replaymod.recording.packet.PacketListener.save(PacketListener.java:203) ~[replaymod-1.18.1-2.6.3.jar:?]
	at com.replaymod.recording.packet.PacketListener.lambda$save$1(PacketListener.java:168) ~[replaymod-1.18.1-2.6.3.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.11.jar:?]
[13:26:44] [Render thread/INFO]: Disconnect from localhost
[13:26:49] [Render thread/INFO]: Stopping!
[13:26:49] [Render thread/INFO]: Disconnect from localhost
```

**Comment by Earthcomputer** [comment]
Hi, can you upload your mod list? The crash is occurring in fixDimensionType in a mixin that is not from multiconnect.

**Comment by Gaming32** [comment]
+ appleskin-fabric-mc1.18-2.2.0
+ architectury-3.2.51
+ ArmoredElytra-3.0.0
+ Autofish-0.9.3-fabric-mc1.17
+ baritone-api-1.8.0
+ bedrockify-1.3.0+mc1.18
+ clientcommands-2.6
+ cloth-config-6.1.48-fabric
+ colormatic-2.4.0+mc.1.18
+ continuity-1.0.3+1.18
+ CraftPresence-Fabric-1.18.1-Release-1.8.8
+ fabric-api-0.44.0+1.18
+ fabric-language-kotlin-1.7.0+kotlin.1.6.0
+ indium-1.0.2-alpha1+mc1.18
+ lambdabettergrass-1.2.1+1.17
+ lambdynamiclights-2.1.0+1.17
+ litematica-fabric-1.18.0-0.0.0-dev.20211203.013300
+ malilib-fabric-1.18.0-0.10.0-dev.26
+ minihud-fabric-1.18.0-0.19.0-dev.20211204.230657
+ modmenu-3.0.0
+ multiconnect-1.5.6
+ OpenAuthMod-fabric-1.1.1
+ plasmovoice-fabric-1.18-1.2.8
+ replaymod-1.18.1-2.6.3
+ RoughlyEnoughItems-7.0.352
+ sodium-fabric-mc1.18.1-rc1-0.4.0-alpha5+build.816
+ tweakeroo-fabric-1.18.0-0.10.0-dev.20211204.230726
+ twitchchat-0.11.2b
+ WI-Zoom-1.3-MC1.18.1
+ wthit-fabric-4.3.1
+ XaerosWorldMap_1.18.7_Fabric_1.18
+ Xaeros_Minimap_21.22.5_Fabric_1.18

**Comment by Earthcomputer** [comment]
Hmm, could you see if you can find out which one we're conflicting with?

**Comment by Gaming32** [comment]
It's Colormatic.

**Comment by Finoway** [comment]
> It's Colormatic.

Hello, I have the same problem with Colormatic when I am not the mod I don't have the problem.

**Comment by JaaiDead** [comment]
https://github.com/kvverti/colormatic/issues/80#issuecomment-1033334062

**Comment by Earthcomputer** [comment]
This is unlikely to occur after the rewrite. Please reply if it does.
