### ISSUE TITLE
Instant disconnect on 1.11-1.16

### ISSUE THREAD

**Issue by Brottweiler** [Earthcomputer/multiconnect#299]
If I connect to a server (tested on `pvp.projectenyo.eu` and `play.oc.tc` and `play.shotbow.net`) as version 1.11 → 1.16 it instantly disconnects me. Connecting as 1.17 works fine. Log below.
```
[21:04:16] [Render thread/INFO]: 'language' is an unsupported metadata key!
[21:04:16] [Render thread/INFO]: Connecting to pvp.projectenyo.eu, 25565
[21:04:16] [Server Connector #3/INFO]: Protocol version forced to 335 (1.12)
[21:04:21] [Server Connector #3/INFO]: 'language' is an unsupported metadata key!
[21:04:22] [Netty Epoll Client IO #2/ERROR]: !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[21:04:22] [Netty Epoll Client IO #2/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[21:04:22] [Netty Epoll Client IO #2/ERROR]: Minecraft version: 1.18.1
[21:04:22] [Netty Epoll Client IO #2/ERROR]: multiconnect version: 1.5.7
[21:04:22] [Netty Epoll Client IO #2/ERROR]: Server version: 335 (1.12)
[21:04:22] [Netty Epoll Client IO #2/ERROR]: Server brand: vanilla
[21:04:22] [Netty Epoll Client IO #2/ERROR]: Compressed packet data: H4sIAAAAAAAA/1NmYGAPYWQAAiYblrScxBIGAPhlWHsSAAAA
[21:04:22] [Netty Epoll Client IO #2/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / minecraft:dimension_type]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / minecraft:dimension_type]
	at net.minecraft.class_5455.method_30534(class_5455.java:56) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5455.method_30530(class_5455.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.handler$zdl000$fixDimensionType(class_2678.java:566) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.<init>(class_2678.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.<init>(class_2678.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:417) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:469) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils$DebugDecoderHandler.decode(DebugUtils.java:301) ~[multiconnect-1.5.7.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	... 33 more
[21:04:22] [Render thread/INFO]: 'language' is an unsupported metadata key!
```

**Comment by lenrik1589** [comment]
Same stack trace, info:
```
[22:34:59] [Netty Epoll Client IO #0/ERROR]: Failed to find lambda 1 in caller class net.minecraft.class_2678 at line 43
[22:34:59] [Netty Epoll Client IO #0/ERROR]: !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[22:34:59] [Netty Epoll Client IO #0/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[22:34:59] [Netty Epoll Client IO #0/ERROR]: Minecraft version: 1.18.1
[22:34:59] [Netty Epoll Client IO #0/ERROR]: multiconnect version: 1.5.7
[22:34:59] [Netty Epoll Client IO #0/ERROR]: Server version: 340 (1.12.2)
[22:34:59] [Netty Epoll Client IO #0/ERROR]: Server brand: vanilla
[22:34:59] [Netty Epoll Client IO #0/ERROR]: Compressed packet data: H4sIAAAAAAAA/1NmYPgxk5EBCJgDWNJyEksYADXCh5ISAAAA
[22:34:59] [Netty Epoll Client IO #0/ERROR]: Unexpectedly disconnected from server!
```

connecting to both proto smp and cmp, nextgen works

**Comment by Brottweiler** [comment]
I was able to connect now, might've been conflict with other mods? I had removed Colormatic and could now connect. So I am going to close this issue in favour of https://github.com/Earthcomputer/multiconnect/issues/293.
