### ISSUE TITLE
Unexpected disconnect (DecoderException)

### ISSUE THREAD

**Issue by xpple** [Earthcomputer/multiconnect#304]
While testing SeedMapper this crash happened:
<details>
<summary>latest.log</summary>

```log
[15:17:34] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[15:17:34] [main/INFO] (FabricLoader) Loading 54 mods:
	- clientarguments b1.1.4
	- fabric 0.45.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cdc8
	- fabric-api-lookup-api-v1 1.4.0+16d92c47c8
	- fabric-biome-api-v1 6.0.1+ded849a9c8
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d95c8
	- fabric-command-api-v1 1.1.6+3ac43d95c8
	- fabric-commands-v0 0.2.5+b4f4f6cdc8
	- fabric-containers-v0 0.1.18+d154e2c6c8
	- fabric-content-registries-v0 0.4.5+6f53a73dc8
	- fabric-crash-report-info-v1 0.1.8+3ac43d95c8
	- fabric-data-generation-api-v1 1.0.0+3fec4ad9c8
	- fabric-dimensions-v1 2.1.7+43d29571c8
	- fabric-entity-events-v1 1.4.5+6b21378ac8
	- fabric-events-interaction-v0 0.4.16+bfa23f17c8
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cdc8
	- fabric-game-rule-api-v1 1.0.10+3ac43d95c8
	- fabric-gametest-api-v1 1.0.5+03d159cfc8
	- fabric-item-api-v1 1.3.0+691a79b5c8
	- fabric-item-groups-v0 0.3.3+3ac43d95c8
	- fabric-key-binding-api-v1 1.0.8+c8aba2f3c8
	- fabric-keybindings-v0 0.2.6+b4f4f6cdc8
	- fabric-lifecycle-events-v1 1.4.10+c15ca335c8
	- fabric-loot-tables-v1 1.0.8+3ac43d95c8
	- fabric-mining-level-api-v1 1.0.3+3ac43d95c8
	- fabric-mining-levels-v0 0.1.7+b4f4f6cdc8
	- fabric-models-v0 0.3.3+3ac43d95c8
	- fabric-networking-api-v1 1.0.18+3ac43d95c8
	- fabric-networking-v0 0.3.5+b4f4f6cdc8
	- fabric-object-builder-api-v1 1.11.0+3b82842ec8
	- fabric-object-builders-v0 0.7.8+3ac43d95c8
	- fabric-particles-v1 0.2.9+526dc1acc8
	- fabric-registry-sync-v0 0.8.5+3ac43d95c8
	- fabric-renderer-api-v1 0.4.9+3ac43d95c8
	- fabric-renderer-indigo 0.4.12+3ac43d95c8
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cdc8
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d7c8
	- fabric-rendering-fluids-v1 0.1.18+3ac43d95c8
	- fabric-rendering-v0 1.1.9+b4f4f6cdc8
	- fabric-rendering-v1 1.10.3+6b21378ac8
	- fabric-resource-loader-v0 0.4.11+3ac43d95c8
	- fabric-screen-api-v1 1.0.7+3ac43d95c8
	- fabric-screen-handler-api-v1 1.1.11+3ac43d95c8
	- fabric-structure-api-v1 2.0.8+295197a7c8
	- fabric-tag-extensions-v0 1.2.5+3ac43d95c8
	- fabric-textures-v0 1.0.9+3ac43d95c8
	- fabric-tool-attribute-api-v1 1.3.4+7de09f55c8
	- fabric-transfer-api-v1 1.5.5+b4f4f6cdc8
	- fabricloader 0.12.12
	- java 17
	- minecraft 1.18.1
	- multiconnect 1.5.7
	- multiconnect-api 1.5.7 via multiconnect
	- seedmapper b1.4.6
[15:17:37] [main/WARN] (FabricLoader/Metadata) Mod `seedmapper` (b1.4.6) does not respect SemVer - comparison support is limited.
[15:17:37] [main/WARN] (FabricLoader/Metadata) Mod `clientarguments` (b1.1.4) does not respect SemVer - comparison support is limited.
[15:17:37] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/frede/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/7a4ca9d54d9ae564dea0363d668036a8420ed9b8/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[15:17:37] [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper!
[15:17:37] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_16
[15:17:38] [main/WARN] (FabricLoader/Mixin) Reference map 'clientarguments-refmap.json' for clientarguments.mixins.json could not be read. If this is a development environment you can ignore this message
[15:17:43] [main/WARN] (FabricLoader/Mixin) @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zpf000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[15:17:46] [Render thread/INFO] (Minecraft) Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:17:47] [Render thread/ERROR] (Minecraft) Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.2.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:132) ~[authlib-3.2.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:44) ~[authlib-3.2.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:153) ~[authlib-3.2.38.jar:?]
	at net.minecraft.client.MinecraftClient.createUserApiService(MinecraftClient.java:670) [minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:424) [minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:199) [minecraft-project-@-mapped.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:78) ~[authlib-3.2.38.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.2.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:113) ~[authlib-3.2.38.jar:?]
	... 13 more
[15:17:48] [Render thread/INFO] (Minecraft) Setting user: Player122
[15:17:49] [Render thread/INFO] (Indigo) [Indigo] Registering Indigo renderer!
[15:17:50] [Render thread/INFO] (Minecraft) Backend library: LWJGL version 3.2.2 build 10
[15:17:54] [Render thread/INFO] (Minecraft) Narrator library for x64 successfully loaded
[15:17:55] [Render thread/INFO] (Minecraft) Reloading ResourceManager: Default, Fabric Mods (Fabric Crash Report Info (v1), SeedMapper, Fabric Networking (v0), Fabric Tag Extensions (v0), Fabric Particles (v1), Fabric Rendering (v0), Fabric Item API (v1), Fabric Textures (v0), Fabric Structure API (v1), Fabric Events Lifecycle (v0), Fabric Rendering (v1), Fabric Mining Level API (v1), Fabric Rendering Fluids (v1), Fabric API, Fabric Transfer API (v1), Fabric Content Registries (v0), Fabric Command API (v1), Fabric Game Test API (v1), Fabric Renderer API (v1), Fabric Screen Handler API (v1), MultiConnect API, Fabric Screen API (v1), Fabric Containers (v0), MultiConnect, Fabric Models (v0), Fabric Biome API (v1), Fabric Data Generation API (v1), Fabric Commands (v0), Fabric API Lookup API (v1), Fabric Game Rule API (v1), Fabric Rendering Data Attachment (v1), Fabric Dimensions API (v1), Fabric Loot Tables (v1), Fabric Resource Loader (v0), Fabric BlockRenderLayer Registration (v1), Fabric Mining Levels (v0), Fabric Object Builders (v0), Fabric Item Groups (v0), Fabric Registry Sync (v0), Fabric Networking API (v1), Fabric Tool Attribute API (v1), Fabric API Base, Fabric Renderer - Indigo, Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), clientarguments, Fabric Object Builder API (v1), Fabric Loader, Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Key Binding API (v1), Fabric Renderer Registries (v1))
[15:17:56] [Realms Notification Availability checker #1/INFO] (Minecraft) Could not authorize you against Realms server: Invalid session id
[15:18:01] [Render thread/INFO] (Minecraft) OpenAL initialized on device OpenAL Soft on Luidsprekers (Realtek(R) Audio)
[15:18:01] [Render thread/INFO] (Minecraft) Sound engine started
[15:18:02] [Render thread/INFO] (Minecraft) Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[15:18:02] [Render thread/INFO] (Minecraft) Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[15:18:02] [Render thread/INFO] (Minecraft) Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[15:18:02] [Render thread/INFO] (Minecraft) Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[15:18:03] [Render thread/INFO] (Minecraft) Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[15:18:03] [Render thread/INFO] (Minecraft) Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[15:18:03] [Render thread/INFO] (Minecraft) Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[15:18:06] [Render thread/INFO] (Minecraft) Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[15:18:06] [Render thread/INFO] (Minecraft) Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[15:18:06] [Render thread/INFO] (Minecraft) Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[15:18:17] [Render thread/INFO] (Minecraft) Connecting to localhost, 25565
[15:18:18] [Server Connector #1/INFO] (multiconnect) Discovered server protocol: 756 (1.17.1)
[15:19:23] [Render thread/INFO] (Minecraft) Connecting to localhost, 25565
[15:19:24] [Server Connector #2/INFO] (multiconnect) Discovered server protocol: 756 (1.17.1)
[15:19:25] [Netty Client IO #3/ERROR] (multiconnect) Failed to find lambda 1 in caller class net.minecraft.network.packet.s2c.play.GameJoinS2CPacket at line 43
[15:19:25] [Render thread/INFO] (Minecraft) Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:19:27] [Render thread/INFO] (Minecraft) Loaded 0 advancements
[15:19:34] [Render thread/INFO] (Minecraft) [CHAT] <Player122> s
[15:19:50] [Render thread/INFO] (Minecraft) [CHAT] Your game mode has been updated to Creative Mode
[15:20:11] [Render thread/INFO] (Minecraft) [CHAT] [SeedMapper] Set "seed" to 4106873255950695344.
[15:20:28] [Render thread/WARN] (ClientCommandInternals) Syntax exception for client-sided command '/seedmapper:locate feature structure desert_pyramid'
com.mojang.brigadier.exceptions.CommandSyntaxException: Version "1.18.1" was not found.
[15:20:28] [Render thread/INFO] (Minecraft) [CHAT] Version "1.18.1" was not found.
[15:20:43] [Render thread/INFO] (Minecraft) [CHAT] [SeedMapper] desert_pyramid found at x: -2039, z: -1943.
[15:20:46] [Render thread/INFO] (Minecraft) [CHAT] Unknown or incomplete command, see below for error
[15:20:46] [Render thread/INFO] (Minecraft) [CHAT] /tp -2039 ~ -1943<--[HERE]
[15:20:52] [Render thread/INFO] (Minecraft) [CHAT] [Server: Made Player122 a server operator]
[15:20:56] [Render thread/INFO] (Minecraft) [CHAT] Teleported Player122 to -2038.500000, 92.248692, -1942.500000
[15:21:10] [Render thread/INFO] (Minecraft) [CHAT] [SeedMapper] overworld_ruined_portal found at x: -2247, z: -2199.
[15:21:13] [Render thread/INFO] (Minecraft) [CHAT] Teleported Player122 to -2246.500000, 86.993854, -2198.500000
[15:21:22] [Render thread/WARN] (Minecraft) Unable to play empty soundEvent: minecraft:entity.cod.ambient
[15:21:23] [Render thread/WARN] (Minecraft) Unable to play empty soundEvent: minecraft:entity.salmon.ambient
[15:21:35] [Render thread/INFO] (Minecraft) [CHAT] Set own game mode to Spectator Mode
[15:21:55] [Render thread/INFO] (Minecraft) [CHAT] Applied effect Night Vision to Player122
[15:22:03] [Render thread/INFO] (Minecraft) [CHAT] Teleported Player122 to 0.500000, 0.000000, 0.500000
[15:22:07] [Render thread/INFO] (Minecraft) [CHAT] [SeedMapper] overworld_ruined_portal found at x: 377, z: 105.
[15:22:10] [Render thread/INFO] (Minecraft) [CHAT] Teleported Player122 to 377.500000, 0.000000, 105.500000
[15:23:21] [Render thread/INFO] (Minecraft) [CHAT] Teleported Player122 to 3000.500000, 44.625380, 3000.500000
[15:23:25] [Render thread/INFO] (Minecraft) [CHAT] [SeedMapper] overworld_ruined_portal found at x: 2729, z: 2617.
[15:23:29] [Render thread/INFO] (Minecraft) [CHAT] Teleported Player122 to 2729.500000, 44.625380, 2617.500000
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) It may be helpful if you also provide the server IP, but you are not obliged to do this.
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Minecraft version: 1.18.1
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) multiconnect version: 1.5.7
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Server version: 757 (1.18)
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Server brand: vanilla
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Compressed packet data: H4sIAAAAAAAA/0tcJO6wLGratGeevxwCGMDAYYnAf4tvfBPsGRgB1IYsuB4AAAA=
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/97 (ItemPickupAnimationS2CPacket) was larger than I expected, found 24 bytes extra whilst reading packet 97
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.io.IOException: Packet 0/97 (ItemPickupAnimationS2CPacket) was larger than I expected, found 24 bytes extra whilst reading packet 97
	at net.minecraft.network.DecoderHandler.decode(DecoderHandler.java:51) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.network.DecoderHandler.callDecode(DecoderHandler.java) ~[minecraft-project-@-mapped.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils$DebugDecoderHandler.decode(DebugUtils.java:301) ~[multiconnect-1.5.7-64b5720b4b825f21.jar:?]
	at net.minecraft.network.DecoderHandler.callDecode(DecoderHandler.java) ~[minecraft-project-@-mapped.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	... 31 more
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) It may be helpful if you also provide the server IP, but you are not obliged to do this.
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Minecraft version: 1.18.1
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) multiconnect version: 1.5.7
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Server version: 757 (1.18)
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Server brand: vanilla
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Compressed packet data: H4sIAAAAAAAA/0tcJO6wLGratGeevxwCGMDAYYnAf4tvfBPsGRjtGsV3AgBrt3zWIgAAAA==
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) It may be helpful if you also provide the server IP, but you are not obliged to do this.
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Minecraft version: 1.18.1
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) multiconnect version: 1.5.7
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Server version: 757 (1.18)
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Server brand: vanilla
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Compressed packet data: H4sIAAAAAAAA/0tcJO6wLGratGeevxwCGMDAYYnAf4tvfBPsGRjtGsV32i0W3w0AqYSycyYAAAA=
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) It may be helpful if you also provide the server IP, but you are not obliged to do this.
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Minecraft version: 1.18.1
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) multiconnect version: 1.5.7
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Server version: 757 (1.18)
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Server brand: vanilla
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Compressed packet data: H4sIAAAAAAAA/0tcJO6wLGratGeevxwCGMDAYYnAf4tvfBPsGRjtGsV32i0W3233X2wDAFdrcZEqAAAA
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) It may be helpful if you also provide the server IP, but you are not obliged to do this.
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Minecraft version: 1.18.1
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) multiconnect version: 1.5.7
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Server version: 757 (1.18)
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Server brand: vanilla
[15:23:55] [Netty Client IO #3/ERROR] (multiconnect) Compressed packet data: H4sIAAAAAAAA/0tcJO6wLGratGeevxwCGMDAYYnAf4tvfBPsGRjtGsV32i0W3233X2wDAFdrcZEqAAAA
[15:23:55] [Render thread/FATAL] (Minecraft) Reported exception thrown!
net.minecraft.util.crash.CrashException: charTyped event handler
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:496) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.Keyboard.onChar(Keyboard.java:458) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.Keyboard.method_22677(Keyboard.java:473) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.Keyboard.method_22675(Keyboard.java:473) ~[minecraft-project-@-mapped.jar:?]
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:39) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:202) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window.java:310) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1142) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:733) [minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [minecraft-project-@-mapped.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.ClassCastException: class net.minecraft.util.Identifier cannot be cast to class net.minecraft.util.registry.RegistryKey (net.minecraft.util.Identifier and net.minecraft.util.registry.RegistryKey are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @2ce6c6ec)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292) ~[?:?]
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206) ~[?:?]
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161) ~[?:?]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298) ~[?:?]
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[?:?]
	at net.minecraft.command.CommandSource.forEachMatching(CommandSource.java:74) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.command.CommandSource.suggestIdentifiers(CommandSource.java:109) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.command.CommandSource.suggestIdentifiers(CommandSource.java:120) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.command.argument.DimensionArgumentType.listSuggestions(DimensionArgumentType.java:37) ~[minecraft-project-@-mapped.jar:?]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:69) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:598) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.client.gui.screen.CommandSuggestor.refresh(CommandSuggestor.java:184) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.gui.screen.ChatScreen.onChatFieldUpdate(ChatScreen.java:80) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.gui.widget.TextFieldWidget.onChanged(TextFieldWidget.java:152) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.gui.widget.TextFieldWidget.write(TextFieldWidget.java:147) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.gui.widget.TextFieldWidget.charTyped(TextFieldWidget.java:358) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.gui.ParentElement.charTyped(ParentElement.java:74) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.Keyboard.method_1458(Keyboard.java:458) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:491) ~[minecraft-project-@-mapped.jar:?]
	... 20 more
```
</details>

**Comment by Earthcomputer** [comment]
This is unlikely to occur after the rewrite. Please reply if it does.
