### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Vecto07** [Earthcomputer/multiconnect#318]
I am trying to use it together with meteorclient 1.17.1 and other mods. It doesnt crash when i remove it. 

```
java.lang.ExceptionInInitializerError
<html>at meteordevelopment.meteorclient.systems.modules.Modules.<clinit>(Modules.java:56)<br/>at net.minecraft.class_128.handler$zom000$onAddStackTrace(class_128.java:524)<br/>at net.minecraft.class_128.method_555(class_128.java:78)<br/>at net.minecraft.class_128.method_568(class_128.java:132)<br/>at net.minecraft.class_128.method_24305(class_128.java:275)<br/>at net.minecraft.client.main.Main.main(Main.java:137)<br/>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)<br/>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>at java.base/java.lang.reflect.Method.invoke(Method.java:567)<br/>at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>
RuntimeException: Mixin transformation of net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager failed
<html>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)<br/>at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)<br/>at net.minecraft.class_2370.onChange(class_2370.java:1058)<br/>at net.minecraft.class_2370.handler$zid000$set(class_2370.java:1053)<br/>at net.minecraft.class_2370.method_10273(class_2370.java:72)<br/>at net.minecraft.class_2370.method_10272(class_2370.java:103)<br/>at net.minecraft.class_2378.method_10227(class_2378.java:318)<br/>at net.minecraft.class_2378.method_29109(class_2378.java:309)<br/>at 
![image](https://user-images.githubusercontent.com/69140727/150426835-4b78a391-3193-4d51-9d83-b48e043fdcfb.png)
net.minecraft.class_2378.method_10224(class_2378.java:301)<br/>at net.minecraft.class_2378.<clinit>(class_2378.java:169)<br/>... 13 more</html>
MixinTransformerError: An unexpected critical error was encountered
<html>at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)<br/>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)<br/>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)<br/>... 24 more</html>
MixinApplyError: Mixin [multiconnect.mixins.json:compat.MixinRegistrySyncManager] from phase [DEFAULT] in config [multiconnect.mixins.json] from mod [multiconnect] FAILED during APPLY
<html>at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)<br/>at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)<br/>at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)<br/>... 27 more</html>
InvalidInjectionException: Critical injection failure: @Inject annotation on onCreatePacket could not find any targets matching 'createPacket' in net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager. Using refmap multiconnect-refmap.json [PREINJECT Applicator Phase -> multiconnect.mixins.json:compat.MixinRegistrySyncManager -> Prepare Injections ->  -> handler$bfg000$onCreatePacket(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
<html>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)<br/>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)<br/>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)<br/>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)<br/>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)<br/>at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)<br/>at jdk.internal.reflect.GeneratedConstructorAccessor21.newInstance(Unknown Source)<br/>at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br/>at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)<br/>at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)<br/>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)<br/>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)<br/>at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)<br/>at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)<br/>at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)<br/>at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)<br/>at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)<br/>at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)<br/>at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)<br/>... 27 more</html>
```

![screenshot 2022-01-20](https://user-images.githubusercontent.com/69140727/150426886-2a5d794b-2276-4dc9-96b6-9fb7bf758152.jpg)

**Comment by Earthcomputer** [comment]
No hacked clients please and I don't support 1.17
