### ISSUE TITLE
Gamecrash

### ISSUE THREAD

**Issue by FlawlessDeveloper** [Earthcomputer/multiconnect#330]
```
[16:03:26] [Render thread/FATAL]: Unreported exception thrown!
java.lang.IllegalStateException: Tried to mark light data as ready for chunk [2, 12] but it hasn't been loaded yet
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkTracker.onLightDataAdded(ChunkTracker.java:92) ~[sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkLightAdded(SodiumWorldRenderer.java:304) ~[sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar:?]
	at net.minecraft.class_638.handler$bop000$postLightUpdate(class_638.java:4578) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_39849(class_638.java:530) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_38543(class_634.java:2198) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_38545(class_634.java:2183) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_38534(class_638.java:142) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1208) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1031) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:811) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1117) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
[16:03:26] [Render thread/INFO]: Saving
[16:03:26] [Render thread/INFO]: Saved in 9 milliseconds.
[16:03:26] [Render thread/INFO]: Stopping worker threads
[16:03:26] [Netty Epoll Client IO #0/ERROR]: !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[16:03:26] [Netty Epoll Client IO #0/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[16:03:26] [Netty Epoll Client IO #0/ERROR]: Minecraft version: 1.18.1
[16:03:26] [Netty Epoll Client IO #0/ERROR]: multiconnect version: 1.5.10
[16:03:26] [Netty Epoll Client IO #0/ERROR]: Server version: 757 (1.18)
[16:03:26] [Netty Epoll Client IO #0/ERROR]: Server brand: iTz_xXBungeeCordXxHD_PVP (git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:ab2b150:unknown) <- Tuinity
[16:03:26] [Netty Epoll Client IO #0/ERROR]: Compressed packet data: H4sIAAAAAAAA/+3WOwrCQBSF4eswhUrER2WlYcAVuIIkvoIxI1GxzFaCK7ByE25RiCO2FlZGmP9rDpfbneqYuq4fIhK05G3adYf0d/aY2ryMM5ts03ztHrNRR1+i8LohP6frSL0ykN7ZFtmiPJyKVZQs6e777qRqjwF4676fiNZyU7Gp1LBhpmFzAAA8FIpW8gc7AAAA/B47AAAAf7EDAADw14AdAHhPAPjrCRPmVp/ALgAA
[16:03:26] [Netty Epoll Client IO #0/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException: java.io.IOException: Root tag must be a named compound tag
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.netty.handler.codec.EncoderException: java.io.IOException: Root tag must be a named compound tag
	at net.minecraft.class_2540.method_30616(class_2540.java:452) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10798(class_2540.java:432) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readNbt$24(TransformerByteBuf.java:808) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:257) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:198) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.method_10798(TransformerByteBuf.java:808) ~[multiconnect-1.5.10.jar:?]
	at net.minecraft.class_6603.<init>(class_6603.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.<init>(class_2672.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:417) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:469) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils$DebugDecoderHandler.decode(DebugUtils.java:301) ~[multiconnect-1.5.10.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	... 31 more
Caused by: java.io.IOException: Root tag must be a named compound tag
	at net.minecraft.class_2507.method_10625(class_2507.java:79) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_30616(class_2540.java:450) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10798(class_2540.java:432) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readNbt$24(TransformerByteBuf.java:808) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:257) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:198) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.method_10798(TransformerByteBuf.java:808) ~[multiconnect-1.5.10.jar:?]
	at net.minecraft.class_6603.<init>(class_6603.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.<init>(class_2672.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:417) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:469) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils$DebugDecoderHandler.decode(DebugUtils.java:301) ~[multiconnect-1.5.10.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	... 31 more
[16:03:26] [Netty Epoll Client IO #0/ERROR]: !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[16:03:26] [Netty Epoll Client IO #0/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[16:03:26] [Netty Epoll Client IO #0/ERROR]: Minecraft version: 1.18.1
[16:03:26] [Netty Epoll Client IO #0/ERROR]: multiconnect version: 1.5.10
[16:03:26] [Netty Epoll Client IO #0/ERROR]: Server version: 757 (1.18)
[16:03:26] [Netty Epoll Client IO #0/ERROR]: Server brand: iTz_xXBungeeCordXxHD_PVP (git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:ab2b150:unknown) <- Tuinity
[16:03:26] [Netty Epoll Client IO #0/ERROR]: Compressed packet data: H4sIAAAAAAAA/+3WOwrCQBSF4eswhUrER2WlYcAVuIIkvoIxI1GxzFaCK7ByE25RiCO2FlZGmP9rDpfbneqYuq4fIhK05G3adYf0d/aY2ryMM5ts03ztHrNRR1+i8LohP6frSL0ykN7ZFtmiPJyKVZQs6e777qRqjwF4676fiNZyU7Gp1LBhpmFzAAA8FIpW8gc7AAAA/B47AAAAf7EDAADw14AdAHhPAPjrCRPmVp/ALgAA
[16:03:26] [Thread-8/INFO]: Saving
```

**Comment by Phoenix-Starlight** [comment]
Its probably caused because client crashes from Sodium. Please look at the top section you pasted.

**Comment by Earthcomputer** [comment]
This is unlikely to occur after the rewrite. Please reply if it does.
