### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by pascal2313** [Earthcomputer/multiconnect#339]
```
[20:42:12] [Netty Client IO #1/ERROR]: !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[20:42:12] [Netty Client IO #1/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[20:42:12] [Netty Client IO #1/ERROR]: Minecraft version: 1.18.1
[20:42:12] [Netty Client IO #1/ERROR]: multiconnect version: 1.5.10
[20:42:12] [Netty Client IO #1/ERROR]: Server version: 757 (1.18)
[20:42:12] [Netty Client IO #1/ERROR]: Server brand: §cZepollo - IP: mc.zepollo.com§r
[20:42:12] [Netty Client IO #1/ERROR]: Compressed packet data: H4sIAAAAAAAA/4WSzQqCQBRGNz3IcFcFElE7l0WLUFBoEZUVpreSxpkYFTPzAXurrIXmkM723sP5vvnZv3o54D0WLujbHDxOuQAdfFdcD2fhZqBBXK7LkZOMRhMPCq2mlEB6CWKUCfJFjpz6oMciQa3CBfo1vJnblmla7bQkf7aTZ4HIanJprKemNTOIsiuqjtsE2m4NHdYhshgNGBKVqd/Vdkxs6mYoIpVlIFWRPAtbbxZpPEnoDR9445TyocdDh5XorlpCcfr3k6SAFR6jctCVkqbpb8xvBvm0fwNDkdtiswIAAA==
[20:42:12] [Netty Client IO #1/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/94 (class_2770) was larger than I expected, found 688 bytes extra whilst reading packet 94
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.io.IOException: Packet 0/94 (class_2770) was larger than I expected, found 688 bytes extra whilst reading packet 94
	at net.minecraft.class_2543.decode(class_2543.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils$DebugDecoderHandler.decode(DebugUtils.java:301) ~[multiconnect-1.5.10.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	... 35 more
[20:42:12] [Netty Client IO #1/ERROR]: !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[20:42:12] [Netty Client IO #1/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[20:42:12] [Netty Client IO #1/ERROR]: Minecraft version: 1.18.1
[20:42:12] [Netty Client IO #1/ERROR]: multiconnect version: 1.5.10
[20:42:12] [Netty Client IO #1/ERROR]: Server version: 757 (1.18)
[20:42:12] [Netty Client IO #1/ERROR]: Server brand: §cZepollo - IP: mc.zepollo.com§r
[20:42:12] [Netty Client IO #1/ERROR]: Compressed packet data: H4sIAAAAAAAA/4WSzQqCQBRGNz3IcFcFElE7l0WLUFBoEZUVpreSxpkYFTPzAXurrIXmkM723sP5vvnZv3o54D0WLujbHDxOuQAdfFdcD2fhZqBBXK7LkZOMRhMPCq2mlEB6CWKUCfJFjpz6oMciQa3CBfo1vJnblmla7bQkf7aTZ4HIanJprKemNTOIsiuqjtsE2m4NHdYhshgNGBKVqd/Vdkxs6mYoIpVlIFWRPAtbbxZpPEnoDR9445TyocdDh5XorlpCcfr3k6SAFR6jctCVkqbpb8xvBvm0fwNDkdtiswIAAA==
```

**Comment by Earthcomputer** [comment]
Please can you provide the full log?

**Comment by pascal2313** [comment]
[2022-04-11-6.log](https://github.com/Earthcomputer/multiconnect/files/8467169/2022-04-11-6.log)
full log

**Comment by JaaiDead** [comment]
Does it say dimension id not found ?

**Comment by JaaiDead** [comment]
@pascal2313 ?

**Comment by pascal2313** [comment]
i dont know i dont use the mod anymore

**Comment by JaaiDead** [comment]
Issue Found 
+Can be Reproduced.
+Deemed to solved in the rewrite.

**Comment by pascal2313** [comment]
Oke
