### ISSUE TITLE
Fireworks dont work on translation rewrite.

### ISSUE THREAD

**Issue by ZeoNight** [Earthcomputer/multiconnect#347]
Fireworks doesn't work with elytra's.

Stack trace:
```
[10:08:07] [Render thread/ERROR]: Error executing task on Client
java.lang.IllegalStateException: Invalid entity data item type for field 2(class_1297::field_6027) on entity minecraft:firework_rocket: into=Optional.empty(class java.util.Optional), from=Optional[class_2338{x=1030, y=1792, z=-20963280}](class java.util.Optional)
0: class_1297::field_5990 = 0
1: class_1297::field_6032 = 300
2: class_1297::field_6027 = Optional.empty
3: class_1297::field_5975 = false
4: class_1297::field_5962 = false
5: class_1297::field_5995 = false
6: class_1297::field_18064 = STANDING
7: class_1297::field_27858 = 0
8: class_1671::field_7614 = 36 firework_rocket
9: class_1671::field_7611 = OptionalInt[0]
10: class_1671::field_7615 = false
	at net.minecraft.class_2945.handler$bmk000$improveErrorMessage(class_2945.java:1093) ~[client-intermediary.jar:?]
	at net.minecraft.class_2945.method_12785(class_2945.java:245) ~[client-intermediary.jar:?]
	at net.minecraft.class_2945.method_12779(class_2945.java:230) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11093(class_634.java:460) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_11808(class_2739.java:39) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_11054(class_2739.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.redirect$zhm000$redirectExecuteTask(class_1255.java:1021) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
```

**Comment by ZeoNight** [comment]
Fixed
