### ISSUE TITLE
1.18.1 -> 1.8 error 

### ISSUE THREAD

**Issue by petulikan1** [Earthcomputer/multiconnect#353]
[22:10:50] [Netty Client IO #19/ERROR]: !!!!!!!! Unexpected disconnect, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[22:10:50] [Netty Client IO #19/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[22:10:50] [Netty Client IO #19/ERROR]: Minecraft version: 1.18.1
[22:10:50] [Netty Client IO #19/ERROR]: multiconnect version: 1.5.10
[22:10:50] [Netty Client IO #19/ERROR]: Server version: 47 (1.8)
[22:10:50] [Netty Client IO #19/ERROR]: Server brand: Waterfall <- Paper
[22:10:50] [Netty Client IO #19/ERROR]: Compressed packet data: H4sIAAAAAAAA/3NllDq03OL0THR4aLn56ZkALUsreR0AAAA=
[22:10:50] [Netty Client IO #19/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.internal.Streams.parse(Streams.java:60) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65) ~[gson-2.8.8.jar:?]
	at net.minecraft.class_3518.method_15267(class_3518.java:503) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15279(class_3518.java:527) ~[client-intermediary.jar:?]
	at net.minecraft.class_2561$class_2562.method_10877(class_2561.java:365) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10808(class_2540.java:324) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readText$76(TransformerByteBuf.java:1036) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:257) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:198) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.method_10808(TransformerByteBuf.java:1036) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_16_5.TitleS2CPacket_1_16_5.<init>(TitleS2CPacket_1_16_5.java:19) ~[multiconnect-1.5.10.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:417) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:469) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils$DebugDecoderHandler.decode(DebugUtils.java:301) ~[multiconnect-1.5.10.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	... 33 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403) ~[gson-2.8.8.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:592) ~[gson-2.8.8.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.Streams.parse(Streams.java:46) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65) ~[gson-2.8.8.jar:?]
	at net.minecraft.class_3518.method_15267(class_3518.java:503) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15279(class_3518.java:527) ~[client-intermediary.jar:?]
	at net.minecraft.class_2561$class_2562.method_10877(class_2561.java:365) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10808(class_2540.java:324) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.lambda$readText$76(TransformerByteBuf.java:1036) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:257) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.read(TransformerByteBuf.java:198) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.transformer.TransformerByteBuf.method_10808(TransformerByteBuf.java:1036) ~[multiconnect-1.5.10.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_16_5.TitleS2CPacket_1_16_5.<init>(TitleS2CPacket_1_16_5.java:19) ~[multiconnect-1.5.10.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:417) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:469) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils$DebugDecoderHandler.decode(DebugUtils.java:301) ~[multiconnect-1.5.10.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	... 33 more
[22:10:54] [Render thread/INFO]: Connecting to play.alphaprison.net, 25565
[22:10:54] [Server Connector #4/INFO]: Protocol version forced to 47 (1.8)

I'm sure you know what to do with this... or if this error has already been fixed, sorry for wasting your time.

**Comment by VytskaLT** [comment]
1.18.1 isn't supported

**Comment by Gaming32** [comment]
That is incorrect. 1.18.1 *is* supported, as 1.18.2 is not yet supported.

**Comment by VytskaLT** [comment]
well i doubt it will get a fix, youll probably just need to wait for the translation rewrite

**Comment by petulikan1** [comment]
Alright thanks

**Comment by JaaiDead** [comment]
Add a Translation rewrite for future use when working on 1.8
