### ISSUE TITLE
OutOfMemoryError translating packet

### ISSUE THREAD

**Issue by FireTner** [Earthcomputer/multiconnect#356]
Just flying around until suddenly this happened; I assume it's something to do with specific block.
I don't know how to reproduce this elsewhere but on 'mc.openredstone.org' '/build' '/p v ShayHi' somewhere on his plot.

```
[16:30:15] [Netty Epoll Client IO #4/ERROR]: !!!!!!!! Unexpected packet error, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[16:30:15] [Netty Epoll Client IO #4/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[16:30:15] [Netty Epoll Client IO #4/ERROR]: Minecraft version: 1.18.2
[16:30:15] [Netty Epoll Client IO #4/ERROR]: multiconnect version: 1.6-beta.8
[16:30:15] [Netty Epoll Client IO #4/ERROR]: Server version: 756 (1.17.1)
[16:30:15] [Netty Epoll Client IO #4/ERROR]: Server brand: Waterfall <- Paper
[16:30:15] [Netty Epoll Client IO #4/ERROR]: Direction: inbound
[16:30:15] [Netty Epoll Client IO #4/ERROR]: Compressed packet data: H4sIAAAAAAAA/72TPU7DMBiGHQl20xu4FRcwvUHIDUIGdjcDu8nAwOZmYE8rLhB6g9AbBG5QjgBHAPw6doWgQG1L9RB9b/zzPF/knB7fJwlJiBlHeCS3lFCey+siJywVal4KxGZRScT2oVaI3eOyQeyfVi3i5mXdIb6+PfeI7x/rDfJdu+oxf9MsO6y/UnWL/ZeyanBerUqF8ytZSPDKWSYIilmWxnq47ObderffnefO3/JQXEx5rIc/1/JQnE9YrIc/1/F0cTaisR4BXMvTxdhcyiiPAK7jEXoy/BMxHiFczaPky4jxCOGy8YiRHSPIw5+r30/4Ln6Qhz9Xr5umf/H9PHy52Jfl+/D38/Dl4rsVwof/j4cf19ybUobwf/HQ2fKZ5XPLTy0/t3xh+TKO/91jyz9Q/z9FBj4d+ids6J9y078Gm/41GP3DQ/f/Cc5Pl40VCAAA
[16:30:15] [Netty Epoll Client IO #4/ERROR]: Unexpectedly disconnected from server!
java.lang.OutOfMemoryError: Cannot reserve 4194304 bytes of direct buffer memory (allocated: 4293134649, limit: 4294967296)
	at java.nio.Bits.reserveMemory(Bits.java:178) ~[?:?]
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:121) ~[?:?]
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:332) ~[?:?]
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:632) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:607) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:202) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:172) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:134) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:126) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.UnsafeByteBufUtil.copy(UnsafeByteBufUtil.java:436) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.copy(PooledUnsafeDirectByteBuf.java:216) ~[netty-all-4.1.68.Final.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$3(MulticonnectClientboundTranslator.java:32) ~[multiconnect-1.6-beta.8.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils.wrapInErrorHandler(DebugUtils.java:215) ~[multiconnect-1.6-beta.8.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.decode(MulticonnectClientboundTranslator.java:30) ~[multiconnect-1.6-beta.8.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[16:30:15] [Render thread/INFO]: Stopping worker threads
```

**Comment by FireTner** [comment]
Thanks for the rename; makes more sense

**Comment by JaaiDead** [comment]
Try allocate more ram lol

**Comment by ZeoNight** [comment]
Not multiconnect issue - Allocate more ram.

**Comment by I-Got-You-Dead** [comment]
I'm getting this exact issue with 6 gbs of ram allocated and a pretty beefy pc, any idea how much ram I should use?

**Comment by I-Got-You-Dead** [comment]
even with 8 gbs of ram allocated 💀
