### ISSUE TITLE
[1.19] -> [1.18.2] When you wanna trade with villager, it disconnects you with this stacktrace

### ISSUE THREAD

**Issue by DarkReaper231** [Earthcomputer/multiconnect#365]
```
[02:26:17] [Netty Epoll Client IO #0/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[02:26:17] [Netty Epoll Client IO #0/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: net.minecraft.class_148: Loading NBT data
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketIntrinsics.sendRawToClient(PacketIntrinsics.java:189) ~[multiconnect-1.6-beta.12.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$2(MulticonnectClientboundTranslator.java:44) ~[multiconnect-1.6-beta.12.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketSystem$Internals.submitTranslationTask(PacketSystem.java:303) ~[multiconnect-1.6-beta.12.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$3(MulticonnectClientboundTranslator.java:36) ~[multiconnect-1.6-beta.12.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils.wrapInErrorHandler(DebugUtils.java:221) [multiconnect-1.6-beta.12.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.decode(MulticonnectClientboundTranslator.java:30) [multiconnect-1.6-beta.12.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: net.minecraft.class_148: Loading NBT data
	at net.minecraft.class_2507.method_10626(class_2507.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10625(class_2507.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_30616(class_2540.java:547) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10798(class_2540.java:529) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10819(class_2540.java:582) ~[client-intermediary.jar:?]
	at net.minecraft.class_1916.method_43716(class_1916.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:171) ~[client-intermediary.jar:?]
	at net.minecraft.class_1916.method_8265(class_1916.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_3943.<init>(class_3943.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:425) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:477) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:?]
	... 39 more
Caused by: java.io.EOFException: fieldSize is too long! Length is 8, but maximum is 0
	at io.netty.buffer.ByteBufInputStream.checkAvailable(ByteBufInputStream.java:327) ~[netty-buffer-4.1.77.Final.jar:?]
	at io.netty.buffer.ByteBufInputStream.readLong(ByteBufInputStream.java:289) ~[netty-buffer-4.1.77.Final.jar:?]
	at io.netty.buffer.ByteBufInputStream.readDouble(ByteBufInputStream.java:224) ~[netty-buffer-4.1.77.Final.jar:?]
	at net.minecraft.class_2489$1.method_23242(class_2489.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_2489$1.method_23262(class_2489.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10626(class_2507.java:147) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10625(class_2507.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_30616(class_2540.java:547) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10798(class_2540.java:529) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10819(class_2540.java:582) ~[client-intermediary.jar:?]
	at net.minecraft.class_1916.method_43716(class_1916.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:171) ~[client-intermediary.jar:?]
	at net.minecraft.class_1916.method_8265(class_1916.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_3943.<init>(class_3943.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:425) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:477) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:?]
	... 39 more
```

**Comment by DarkReaper231** [comment]
Server IP `frendssmp.mc.hostify.cz`
It's warez

**Comment by Earthcomputer** [comment]
Can you try with [this version](https://github.com/Earthcomputer/multiconnect/suites/6918466152/artifacts/268924635), with the JVM flag `-Dmulticonnect.storeBufsForHandler=true` enabled, which will give a better error message, and upload the new log?

**Comment by DarkReaper231** [comment]
```
[17:32:27] [Netty Epoll Client IO #3/ERROR]: !!!!!!!! Unexpected packet error, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[17:32:27] [Netty Epoll Client IO #3/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[17:32:27] [Netty Epoll Client IO #3/ERROR]: Minecraft version: 1.19
[17:32:27] [Netty Epoll Client IO #3/ERROR]: multiconnect version: 1.6-beta.13-8-g953bb667
[17:32:27] [Netty Epoll Client IO #3/ERROR]: Server version: 757 (1.18)
[17:32:27] [Netty Epoll Client IO #3/ERROR]: Server brand: Spigot
[17:32:27] [Netty Epoll Client IO #3/ERROR]: Compressed packet data: H4sIAAAAAAAA/9NgZGJcz8rIwLiaVYABDniAmBHEsPU5cxZEQ9T8YuViYGRU58KjDigPANb9cuRTAAAA
[17:32:27] [Netty Epoll Client IO #3/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(83) + length(1) exceeds writerIndex(83): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 83, widx: 83, cap: 256)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketIntrinsics.sendRawToClient(PacketIntrinsics.java:188) ~[multiconnect-1.6-beta.13-8-g953bb667.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$2(MulticonnectClientboundTranslator.java:52) ~[multiconnect-1.6-beta.13-8-g953bb667.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils.wrapInErrorHandler(DebugUtils.java:226) ~[multiconnect-1.6-beta.13-8-g953bb667.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$3(MulticonnectClientboundTranslator.java:51) ~[multiconnect-1.6-beta.13-8-g953bb667.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketSystem$Internals.submitTranslationTask(PacketSystem.java:303) ~[multiconnect-1.6-beta.13-8-g953bb667.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$4(MulticonnectClientboundTranslator.java:43) ~[multiconnect-1.6-beta.13-8-g953bb667.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils.wrapInErrorHandler(DebugUtils.java:226) [multiconnect-1.6-beta.13-8-g953bb667.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.decode(MulticonnectClientboundTranslator.java:37) [multiconnect-1.6-beta.13-8-g953bb667.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(83) + length(1) exceeds writerIndex(83): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 83, widx: 83, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.77.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.77.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readBoolean(AbstractByteBuf.java:739) ~[netty-buffer-4.1.77.Final.jar:?]
	at net.minecraft.class_2540.readBoolean(class_2540.java:1187) ~[client-intermediary.jar:?]
	at net.minecraft.class_3943.<init>(class_3943.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:425) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:477) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:?]
	41 more
```
