### ISSUE TITLE
[1.19] -> [1.18.2] When you issue command /plugins and the server has a lot of plugins, it disconnects you with this error

### ISSUE THREAD

**Issue by DarkReaper231** [Earthcomputer/multiconnect#366]
```
[02:30:51] [Netty Epoll Client IO #4/ERROR]: !!!!!!!! Unexpected packet error, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[02:30:51] [Netty Epoll Client IO #4/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[02:30:51] [Netty Epoll Client IO #4/ERROR]: Minecraft version: 1.19
[02:30:51] [Netty Epoll Client IO #4/ERROR]: multiconnect version: 1.6-beta.12
[02:30:51] [Netty Epoll Client IO #4/ERROR]: Server version: 758 (1.18.2)
[02:30:51] [Netty Epoll Client IO #4/ERROR]: Server brand: Purpur
[02:30:51] [Netty Epoll Client IO #4/ERROR]: Direction: inbound
[02:30:51] [Netty Epoll Client IO #4/ERROR]: Compressed packet data: H4sIAAAAAAAA/+097XLbNrZ37wvcV0D9K5m1KFGSZbv/5I/EaWzHa3mbbJtOBiQhCRFIsAAoWe30efoWd2f6ZHtAUjJlyxJNkURnd5smcUQSxPn+wDlH//f///zfX/fIvRJ479sff91T8OPet3s3LBrRQKJXh+3X36K93/Z/3XM54wIujQQhwd7+nsuoOzmfkgDu/3UPu4ryAC7LaDQiUn1xue/jwIMbp5hFBK40p0RIuAnhr5cEe0Q4HAtPwuJ7Yw7X1qw15rMv8Y7gdTxQcF3qGx62u9jUbEwVgbvS7X+fvOmZnac3ta0DqxvfkH7wOVi5/dGaZ0S6goZq67pZ4NCQCzTnkUCSCIBxzevSf/UjNeYiXfkpgI/egb+OCJWyddhq7/320/Lj1Z9/y9z+COPPQrlfNrH7gaKDEPvGyGxbrfxE/kgcCR9sXnGsVPhts0mDKXVVJMNpaA1Lo+xAYcFINMlD1gxuayRoFN98wSNJjBG1Y7Wtdlkon4CyIz4PJmSeC+urCKgT82p8ZQ7nB1bPajUconC74bS7B50KdOfdmKAhFVIhDMDC/qmL9VMojA1SrE7hc3QSTSZUof7Nu28qEG4J0j2iahw5FpCjmeA9/euWMA6q1NvGfDIv930i4ZgW4KP0qhx5bqf442fX9wfFn1bUn1JJiohBenWEfSJ73cPiK7Cv2P052vQ8AnnauMTbAKtW6yif8KcyWKvY89P0skEjatll6du/RVTNOBvmxHcG+HqRfkWkxCNzCne951II5XKMZ/Bb5HMrVmCvD+cnXA3gMTE3hvFjq2u1G3cX/ev+3YdBaSr+mszQucBooCKP8o3+91ZddYnHkQtL8aGaYUHQGZmCRQp9jagctM3iuD7KnmKFr2hATAZ73ZfEAbkdlj9+7/34x++OBvCP3xMY4aOf0B+/H8b/SB2XsuRYv4fNpX97iV6ddlVX//w6D92zFKiR7mOsTvVqbYNK1G5b61zVYtFZxEKAieRCeRb4GnHOCBb63QZRvi4021XSYrhi598F4Kpw+8Hrn81mlgzpiCvftbgYNQWRPBIukU1Xv1+/2rI7vXazLI46++6E8glIpqL3ubgqQ96ameoSj/50AX85XBVn6BgejdaxVSGyOtw5ZLnpmWC2RnJy38Hqko8+mVMSOqSAX40TonDjsFtFNqGPfO5FDAjsxgAjBSSmwSg1ylZFqYMNSqRj946OS9MdAypOGHeAyrk4LUv0WnlNXxqE5tz6tnb9nkXKw+7qREogOSM6eftG631jlvq4Eq94oHiYmOoETiQBUESEgKCpbKnbZLKTtzf02xtDem/ZR127VZr4nQo8VIDmyzg5kUcAHxG9Tn4T5EZwRVxzbmG7Gr8QwJpSDyIth3F3gsIESg30o7M36/O6MKwEp9EF5KavtcCPK4u93gEBGKP5OCtL3hrZSuBf5ul5iLnYHvjKsnuN2/PL8/7gvBI/Ij1+UBzhBFrEh0MEq/kSjcAEY8bmBtwJnOShmg72HA7Bfe/YOj60y3MwTrB3kqybiwsfcUOdfEiwolNyhQM8ik/ZjXFiy2o/j5/Hu6wPQ2fYh3e+Czx9oMZNYqijszHrEfR0k3UiSGGzrlirElcMYALbCPsNUqsIOsyfy58Z8gBiB0vyPDUWGKmRCsSFpy5gvZHAvsl0cWftedeu1Liko7GaEf0nciKFQj4jYhgxNE5BXliaGVVjBFiaoyEojQhUfnwyAJAO6SgSyaE4j9+41qMupO69lpOrAuIplerjkHMs5wOiwImeBQazUVWkKwbUDyFWcpLahgeXQxIVB1OJo6FjqVnKIJEkmnlWuKIiL8QjUyvZWeyDgL/7FRSKbBKgB2xQpvQoJ7DS3HFzl4cVH7FDfXxI3jI+M8iAdiW1i33PA0WDpAJWcps4oD5WxNOcN0M8UowGRHNkyPCcrA/lCxH8SrwVeO7iXEeYC8zXqHOk1KVImJk0SPZxJRRfhs8YeHoB5z7SMW2sePgQpZhJilmTyquqYp3lDuS9DqW3BjK5j+B/IAG5L+RzL7hOn7Bjxouv0CcsKuJNLWIxQZQaMlxEzaVX31P/PRCykGedXpUBnzGyAxZcEjEC7FTEa0ivfiLa8yiSsF3g4YI7DlU7bMH3vuxQNvcOuy7InOYntgMYnlCgdNxJ8RWmQAl3BzQMohBfFKo/XuLRHe5QPfjdLd+Iv63VNCEPu8cHubIbK0bAhO0x6/K2dWqj1QA38K8HDe/o2G73jqo0R4mXq+EQnC1N0D6KFGX0F32I94CZ/1qj/1qj/2RrZFoNn/FrrkMw/2azctyqjhN9/hJdXH/gd37vEsbgwVOItw1WNHatltUtryj7Wuekzu9DAUovFwmeoKE+ErzBUvXlPHA/csG8c48aPNS0qjnVPGFYGzk2R0MAFs00oDofSMOI4eXpphNR5sE29xHDYkQQGCm4c5LkCr2kMviZOL3ikym7c9zZXiSX22Ce+yEV5LhIJeUixYCVOjkj0x28dsGDfsjZLlYXrJ0nuWjbO6lJ0LZX8zc4YrnyJWul5fmXv8qSafWR9MPXtQv7JU9qqI2VENuNwXX/ZnDx4a6BO+3DY7tXRfItUtzXiTcdFiKmYUagj30a+ehViKmHIG7kEcD2Os3AId1NHZ9Fx5k5n3skLXaopNZhi8xrTRXv2rK79kEn8+8kcVyeOsjTNbZVitZ0+i3WbS6ZrjkSOBzHpURKUAcoJHKZxyzX1icrF1wqOpxf8YCaPeQ9riI0jA9E9vWhhxdbvxFWYyJ0KJjwfJy2jmR8sBnfgD1fixAOCCstVZ2i2HJ/ycMGTwhSHy+802fpH4IrHBp0UdvPV0Os7K9GtACQQj8wJUabJLr6BMeyDysQlCs8IctGCUQfAC5LBhjn4zAP+z9Fdp2E1k9xMb8Fl83B7gT0h8katZ5Vic8A7uhMLhSgdgCELp2R+pQOLLPSxzipr5BUq8WRQawgBfeRxksUbj/Iy22Z74g7DhIP5pQv2uQLucovWWmrrfdw8JUHPB/PruebGjkXCGU0qO2U13isk2s8V3tCBuq8qBbE2wnR33HH6Iluu5KKL4AqOy4j8b3Lomc4FlI5IhdFU/TWJzjfcRqYPSV50bCh3BQNIwdwog9BQhZn/pe5HQ85cyTv/Ujg+uqPfeI7gIzm4r12Ryd7ymuJHCTr5mOxB4rXx2fvKWO3ZGZ0epmuFz18Di2rGzSCmJtF37vROuPy/a2sah3EUoFgLXcM3lYM96I2Kq3g5AGZx/dOADU6VNXnFmouqxpbtCE9o3fQSHfZSKBo2I2jxj38acNf1vHh8ZFdmhTfYCWAj9q9Vh5BXsc59fHt5c2pQWfroBKj0U/CP+A9Hyv10PUac+NlBH4tEX55JXxJXdgANHeuuT4Jxmuk8AJgY3Q+0LNlKgkBUQiAUam3sGHeSBnahQEWw5htSuxz06TJxTIZEtbHOHpoyonuLDRq6itgG105rbMEkSQp0+wjpTUGTlIKcx7py65uWiLo855GRNJjKT/v6YOHzWNNy2A3j0qXC88ajZqju/fT992jG1zaoM3b/rtPH05/yMN5KzxQH+v5dzzUdtEc57XW5qwKoVufv47JLA+6s3DXKOgR03lKIUlDt9MaTAx3LLvhHPVe0H9USieH/4AAN0FAOSlBL/JDJUB5+7tUi93SkbNDkdWQiAB+C1IkCZ1eZeDR08jv2N3dju99DJ53I5fiecKTRuRhkRKlRsud2lan4Ry0S5vltcqXLyLGKkKM0OSGC2WyIUXTQ6upzrqmlGKKYquIb5WsrJS/iKAP2KyRmHPTU10PrMNKitfiA8jYPeQz8CrdSCru01+IF3vTrh6bsqzoXluoUkieie9r0lP0ik5xoI+3qB6WmGs8YpYW9XHANbk/D8DxNudsxOWLSRlho91ttrrNdqtdBUtcn39CSWIHLUEup271/FPjingU5yFzFuE1kpkqwXWm+k8wULiiE6clbAsi/2hbR6iBbMvu/fQsNZ7ipT6i3FCXGz3/s9Nh+o0eroAkepC+AyhAXwHGReaPAJjfoH9AYO/i4EEtx5/PkdT1xrpwROcKAUPruzwLCemPGtsB73YOfsojphna1MgQl40L6pkUzgOrXdq5+zWgOwD7l6tY8QH0GtHNsEvGXJev92/emTSAdiWTPvoBwjMiuR/X3yxA1ePJdH+bKG3Q6AVhYVJblYPOj3FeJ7mj0RUOzM0b1RNdqrB9qb3zk5lOmRb5NDUqSwuPxJzRAG9u2tsaIZ3Hx4+dVicfvyyJ9vwbV/oF0ieyH9XbLaCn4HFY7pI6BkPjo2pYbdEbKwj2mjMBq+iOAHCedKJeF3w+hFdhiofyKvs8P2KMzze24GxlP13CMiZBvlHXq7Ssj4cGOv0Zf1VaQ5Ap1Z8Z46XbrvahUXWzDbMTqcBlGGqspUX1SzSgDBrKMlqMUyVvKcmVeltPkRo5IlHl10bLBJ6t9lnZXY1IGfNwQkiY2Dhj7ttBJe7baRwcoSllLLbrcgXYOo9lMm8ur4EqoBJsycbNb9XlDsMOixwHO24uGX6EwfrYNGKg0W6w2SP8np7e9BxmVnZYI2qW8+ONnnhq17zXWPTmlhyGJZOsslMVMWI8nmu1mJ7HsJQkmW7FdUcZWsheafmPlw3qf0KWnM73w3MQ3e2jT2AXFgdURnzxwYQG8jZpQjHYjKg7reyDKnjLoQyCqUyrTdMd42BEkNSQ6xxaGgN+g159SHt0tVb9EMQ/XnGPvK7ImsQ7SHclyh1eczfu3InW5SW5LcBN6dUr93LRj1bo+bwTRzavMgk296RtNYF9Ru4hStFTUH0izs5zSfcjqahTHjVbG1Tz68eVlOOq6Tz2Mvz9HLVa7UOJfKIFkrppNbZMBqwm68JnEEEDjEj3CDOcnEwxKuE+omGHwLqqlgoZU4KBrrDS7nPKm0vylCOm118520FAqQDtMdnhi2kdEsjJxu9l3dL/NyYnusjihO8wpuqNwMH7SPpURDuMyRsAE8Fmdvme2xOQxTlwdKEm2PTqtml3m5++pi4fQuhcfIX+DWgeRryPmIlCLZHp1ftP/cATZNY++rQDaQdzqTqFioEfGOyS+uStdv+Kr3JDJ9gdR8fp0U0xULAc0x2Y6yPBTI3nKhKK7bAMuCjUpZid8SDazS5qVg8ohHrtfBZxqfhqM4V/wi7BQpEFvSVK8HEuNNfeJzeIPG4Oyc/iIdlVfWi4658YTBtWd7zJWIMGDQ6RjOQsSr5cQjcQxCPIKvKcMsN6rs9/uO5f/aOZoLekYqJ4yTzStHhrbUwksEe0zSO+yWxrRa1qDsHAQDobM8NxQK00uInXnuZkSh45f8o9Goz6VOQi9gry6yP635mKJ/D3A0VPuMmBEFX00p7o+qQUNJTBbgnUfS/swZezPKR9iuJaySuw6SJguyILkQVu0VPmL8+n04E18YSu+PjaI0OdE4sCRn2qv3MiKU9b1glXFYpnDIrw9fftyeYjspRUvZEsvpNb/Z4Cys7wlOaq6noCRr1svcjKmBxDd/SSr8zIxTaPYNN8U5bO0gOP8tM1i976SPt9MnTUGEEPdQ+Q3alCX8WgIaq//uYm008dpxJ76FzXr/pz1L95F38LpNZn6alSrL58fcpEsKRsjsacT/TYtbgmR4J3HJu2JAfJI4UCQrTvoR+LbyXYHcP9Hp1SL9Jf8BTfrx/2JWHT6tKQzx05T1Mql6P5XCII3iEVOWAETzbz+faWuygYdXK5et8vYa9Npig+we7E7DiZuJ2rCtc+FpSk9vWhOi0FPZac9KsJY6kC0ZiRRVP54q4aLD+QIMVS8xE1yhGBK6zkDpOnJyQI5mqHBd4SIebxcNvia7giLt6w2x34v7PjBOs3XLjk76EHjredSyofU6VG4bwlM2rQP29brZc06b1IBKYUL4QsdoAXkJbiz2SZLheFbx9eXyN5UyL8m2reRKECgvSmtY79ymmQ6uNVNVviENAvV3NGZJFqxAK6pnrNl0P9blV4qQXIJQcPHFmjIHDqvSXmpKD9MikoayZa+6BzXN7Is3s1+TkXjZfIro/AH7EITc8MOLB6z3/59+oGa0SM/oqLtxF4FsbwcqhnOf61bfecVu/ZY6vsPrN3/OV/Hv33L82k3tzTnwAA
[02:30:51] [Netty Epoll Client IO #4/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (40894 > 32767)
	at net.earthcomputer.multiconnect.impl.PacketIntrinsics.readString(PacketIntrinsics.java:233) ~[multiconnect-1.6-beta.12.jar:?]
	at net.earthcomputer.multiconnect.generated.Protocol_1_18_2.translateSPacketGameMessage_1_18_2(Protocol_1_18_2.java:9870) ~[multiconnect-1.6-beta.12.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$0(MulticonnectClientboundTranslator.java:38) ~[multiconnect-1.6-beta.12.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils.wrapInErrorHandler(DebugUtils.java:221) ~[multiconnect-1.6-beta.12.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$1(MulticonnectClientboundTranslator.java:37) ~[multiconnect-1.6-beta.12.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketSystem$Internals.submitTranslationTask(PacketSystem.java:302) ~[multiconnect-1.6-beta.12.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$3(MulticonnectClientboundTranslator.java:36) ~[multiconnect-1.6-beta.12.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils.wrapInErrorHandler(DebugUtils.java:221) ~[multiconnect-1.6-beta.12.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.decode(MulticonnectClientboundTranslator.java:30) ~[multiconnect-1.6-beta.12.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by DarkReaper231** [comment]
The server IP is `targetpvp.mc.hostify.cz`
It's warez server
