### ISSUE TITLE
Unexpected packet error, 

### ISSUE THREAD

**Issue by Sylonin** [Earthcomputer/multiconnect#369]
```
[13:07:49] [Netty Epoll Client IO #1/ERROR]: !!!!!!!! Unexpected packet error, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[13:07:49] [Netty Epoll Client IO #1/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[13:07:49] [Netty Epoll Client IO #1/ERROR]: Minecraft version: 1.19
[13:07:49] [Netty Epoll Client IO #1/ERROR]: multiconnect version: 1.6-beta.13
[13:07:49] [Netty Epoll Client IO #1/ERROR]: Server version: 759 (1.19)
[13:07:49] [Netty Epoll Client IO #1/ERROR]: Server brand: vanilla
[13:07:49] [Netty Epoll Client IO #1/ERROR]: Direction: inbound
[13:07:49] [Netty Epoll Client IO #1/ERROR]: Compressed packet data: H4sIAAAAAAAA/6Vad3wc1bXOuW1G7g3H4F7BQLCBBBLSSCMv9SVA4KW9zWh3JI21O7PM7Fo2aW5yt9xly73iXnHHvWDj3hu4gxvuvcq5d2ZXe7cBv/f+k71T7j33nK+cMwWU5gYtf+FweCpkmLrf1vIir4Q0M9+22uu+oJXv+Pya6eP/LPJFCmwrml+gDkBtuylP/Pohe65Ng8RNpq4HHF/A0EKWGfBFLCtIi1l31oP1ZCOhUeK6fN0K6D7DbK8FjYDPfbnDBtJluH6Dhtvg64kLbf68iGXqPsvWHbQRNkGTxI8BXeM3R50CX0jr6AsHNT+/zmzQCXfGXXBX3FXphrspxVjNqVS5FDVq3PYWuo3uoCX4LrqH7qMH6CEqR+XsEZLe57eNkGOZPieihxzyMf2EHqFHacPEBU7ENgK67SvS7FBs4dCwuvR7UMt1Xuqp9FUGKAPZEKWUjWQT8SQ8GU+hU+k0Op3OoDPpLDqbzqFz6Tw6n75PT7CT7BT7lH2GT+Mz+Cw+h8/R8/Q8/hxfwBfxJXwZX8FX8VV2DV9j19l1fIPdwDfxLXwb38F3cZ3Ey4Na2HC8UL3+Rv3E/xdY+UHD9Nl6WA8GdTPikAO0J+vNjkArKZq2EfZiza8TsdRyg3r8bACRYoVtZtJZ51taxPE5Ya3IdK+0TNoEluGtsB1qyPHSDNt5oYfSR+mv9GeD0WBlCBpKhqJSPAwPY8NxGR3BRtARaCQdRUfTMXQsHYfH0fEwHo+nE/AEOpFOopPpe3QqmoPmonloIRxhR9kxdpx9ii+yS+wyu8Ku0+voBpUyI2ry97rLtyIRK+Tz803rdk4n0plcpYPQNdqFdCXl+BGWjt4piAYL+cnmWh10p+ZEMolMJu+RKWQqmUamkxlkJplFZpM5ZC6ZR+aT98njUq3wv8Tr2jgFvGKCzXjmKSLrRCx2wl6yj+wnpWg/HCAH4CAZTg6Rw+Rj8gk5Qo6SRsdI4ybHyQlykpwi06Bt3QyP1Tro10AsXiy7Gykm3UkP0pP0Ir1JH9KXVO1HqpWQ6v1JjZoDSa1BpHadx+oOI1+v9/gTT7V++plnv/Fcm+dfePGb33rp5W9/55Xvfu/7P/jhqz/68U9++rM/mlZ4MAyhQ6AMxsMEmAJTYQbMhFkwG+bAXJgH8+F9WASLYQkshWXwASyH1bAG1tC1sJaug3V0PWyAD+FDupF+RDfTHXQn3UV3wW66G/bAHroX9tJ99ACNVREcpcfgOD1JT9FP6Wf0DD1LRZp/Ti/Qi/QSvUyv0Kv0Glyj/DThBr0BN+EmvQW36G24Te/AHXqX3qP36QP6iHZmXVgx6o56oD6oL+qHSlB/NAANRIPQMDQSTYllyk60C+1Ge9BetA/tRwfQQXQWXUB32F12j91nD9gj1knprHRRRCYOx6vwarwGr8Xr8Hq8AX+IN+JN+CO8GW/BW/E2vB3vwDvxLrwb78F78T68Hx/AB/EhfBh/jD/BR/BRfAwfx4kCFsUr8qta4jTzDFtHY2AsSDVUpAWDvrDlRHw8b2yBLD8ZxUbFTmEWip9D8hms9E4B81PA/BTweuArBr5miK0avsq6D4O88nPoPBInEY9xXbmCBSbk2gbHAXIX7sF9eCBjuWYaIS2YjASgSuijmxwwOZ34CqxgQFzwpKiP7tAD1J6Q0wsq9YY+qHIf6Av9oAR2QH9eMwNgIAwCnp2wF3jl8CwaDod4DjVqfIwep01O07bl7CkZ+NprPI5W0OetltOVaUXiQPZC/XE8vSeiSUqsHjKWw2s//69f/PJXv/7Nb3dTnrs8c+Po/2TiPeKUiiw7GOBvsPnfMlQ6bQTxQBeM4tRDijEHTQ4Em1nlLWwr38hbB9hBNlIZpTRo1LjJCdy8RRInLcMyK8lQG9XsgM65jrOcIaDcqb+ODoUyNlppOgGaxbHqySnkLIrBFUoHLJmljHzTqZVc7F6S3aVL4R4ViXafLocHVALIgGYX+iyt0FUE5Kff+sb3Jerxa1wqtOf/dNwKayqdjSBorh2iXBFI4arTBJDIA1IRop3QttS9uVE5k+rG0cwAZ+/HEv/jqQY335BaWb7UtIo4AW1j2+UiMzmf5wW1UMhNziLLCjRKPeIsYMSh6AblIEQ5AFWUhvTkXF3z84fnak6cKLncGQrvQSnMRo1kOuIVUKRFXHYx9ZDO66VGZ9qFdqXdaDHtQ/vSfrSE9qfv3CZ3yF1yj9wnjSXkECgR0EJavuBmR49EDDO/8gC0i67hcPo+eIAqIheSOFBsVDd9YX6HE7V1oY8iupMjsGMtrAMPu8WGn03cE7aCGl+jrtnJ9ezTgnzxJn8AbIOWUsD9nDOT9IJXHfm6+XLmauguiLG3UrlEKWGDlFI0TBmujFB4NUxCbZfgzWwL2wn7YD/dD29xroRj9AQWJXKb3UGpsq2afBABp8bftFx/QM/LLzD+9Oe//PV/fdWTcdapu5r2UvopA9hAZQFaQIcqC9FCuogupsPZErqULqMf0OV0BV1Jx7BVVEq3PN3kwjLfjV66gqibFPGgAIawHnFqTMXT8HQ8A8/Es/BsPAfPxfPwfPw+XoAX4kV4MZZWZ2tG0CEL4AZqV1hL3pReYLTnBSXoTiq1XMP2F3hF+KMXXnlaEqchXmq2xfWOK9XdjBS6g1Y+RiW1kpIRVZMzIs4Eo9hKWYg7IZGEeUGrSLedqgK8e0Iv4Mgdg+3+MciWcN8tCw+PTT1SoNt4Hz/RElZTRg0zwJGz5gQ2kU1ik9l7bAqbyqax6WwGm8lmsdlsDpvL5rH5rKH83FCuZYnVm5FYflZrEpdcbQfTIZSr/XLWWIqw37bCDhOCYBiZCkIuVE38aPh1IrzHKLINasv6liey0NK4abMnpVwTgW/hUUYqjGSmF6kmK7xMEnEQrq6ZFDgP4yW5zoUVp2vYTsfK8TXMPMM0cqO2GYsv2gejSbXkfKzRCTpDF+gK3SDavqhDx3f//o9//uvf9dJgIjfKhbLp5MQF0026H92iQjRJCe63bC3oBd6hCahqIRGk3x+MBnSHU0GurUUMYaU41wi8y7iQmvKxmibPrSb/XxH2RKod9YIuzOgzr7+xh725l+1jpbCfCS4+xA6zj11G/oTFfYWwY82FH2vxGTvNzrCz7Bw7zz5nF1jcb3Arxo3YDXaTyfRoa/l8u0YoFDX1mhMQ1xtccRSDML890XxURkaQEbj+SDISHtJyKuG71sEKWpFUCbVTtlEuBjmV9kBC/ZehXkRwVZ1kmHPj7eTIktFj8qby07QIBwAnRSfRuEyq30zOMofLUmGIwz7HJXGP6fBOJpi2npzcvJo5M8VWIDSF4MyEypAyiXMgTyWvvtA0NB1JeGuEwlwvuqVR6yScgk/hMzgNZ+AsnIPz8DlcgK3sIlyCy3AFrsLvm0v7N0QZ+JxoKJRMy8J7ybXt10JhoccdtJPbFumHiK2FA5ZlO5WucC/CfQh3IbfgNtyBUfiy7DBzjXyfcMxBXcvzVZSy0DACiUqROg04GpUzKRtDluPIdV8zVQDF5E+5jAVpDPt8VpVZuYSVov8jlybFJhoM2BwLyDg0Ho1BY+Wz8VthfjjesYn6kRLFY4j0mKCdUM4kMWRrublGSueAqFuhUZJoyxMuPLm7oHqGul5GBOQmg9NL/dGkQVpF8jM1+YNsjqR4JBYOTCKTPNvKFxopj++qXTQU5jjBTeQjVjcNId20yJkvzCj1fHc/UkL6E/mE44Y9zM0SN+23ECBMKFOqDCZDyFBSSkaTsWQcaTqBNGs+kbSYRFpOJq1c4Z6ty7CALCSLyGKyhCwly8gHZDlZQVaSVWQ1WUPWknVkPdlAPiQbySbyEdlMtpCtZBvZTnaQnWQX2U1e30PeePMPb739P2fJOdLuPPmcFAYvkIvkErlMrpCr5Bq5TpwbJHKT3CIPyENSTh6RTrQ77UF70l60Nx1IB3GfUQrDoIyOgBF0JB0JFW0aDhfjqdegmQSTQTRp3oN4l2s6pPe5FtAFsBA8zZWkuGAlXQWr6Gq6nm6gG2ET3QRb6BbYSrfRbZz1RA4fhEM8geP28yGUwyPohDqjLqgr6obiTcaeqBfqx0pYf8ZVHhvEBrPBaAgbgoayoaiUDWPD0XBWxsrQCDSCjWSj0Cg2Go1hPMfZWDSO8Xxn4zlqT3URaQaajRaghWg928A+ZBvZJvYREzW1hwkCkekjmTrcTh4S1HEanUEufSBBIFxWuRRyEV1CgkYuoyuIUwniZILcvh66wW6gm+wmuoVusdtM+EK5TB+heGOzGxYl313pofRUeim9lT5KX65rS5T+oueoDFIGK0OUoUqpIrR1GVfXnN7wKGW0MhqPwWPxODweT8BeT3IJXoqX4RP4JD6FP03qNl7D17HcZbyH7+MH+CGWsKBd1MwPev1h8uMXv/uMRFdCIhQ6OTVq1qotrFXVatUbyURfoQsr/HRFg/GxFDZzJYcjWSSpvmXf4YmSKuEBaDUeiLooH+DleAVeiU1rFW4g45fJX+nJxojlC0UDHEVzKklv1fya39C8Xf3km997VhI3nsrKZP3rpUJ5CWvLs5bnbSni0MuzdwwpZ8dkNx3jKk8uVHXlAhcLCZmARxIhE2Qf4opvX9iKOE1XozVoLVqH1qMN6EO0EW1CH6FerDfbjLagPqwv24q2oe1oBxpKxyhjlUVoMVqClqJl6AO0HK1AK9Eq9Li8LyGTDFtgJVdJVZo2E/UsfKxouItaGK3MlnVgvMHv0oC4VtaIrqTnQSrkun41W8PWsnXsfbaALWSL2GK2hC1ly9gHbDlbwVayVfJ5O2E76o/l06vPt/6OzEkW153u21q2qpkaEadOqh35bcKPPCES4QETqSCzqhXlQims6wFZIKRjvtvNz0nvy0vizUvkFE+FhHtKE86xFoEAXg+C5R0GjVCuyKWcASjV1UuM5w5jIgVaxCdYr4FnQzLbjlby60OclPm6fJwvA5wQdZ790YhlG1qwTZbu18EKVzOGZH6BlEGOqYUdn5gI+Aos26wCzVs+1XoaenoZFvc1SKbbFFpvy43bQ9ZGkrER3bY1vxWJaDVlyMs0vnmEJE2W6M6ZQt/yiItwxZt+krOuaGK99NS3fyhbEM8EVU43QVtgNGudYTjG3XYkfTqmeNOxrcD3JXVLeJK05yLEF7JyvRAIsezp65j7b5ySokKjpunYanIh2pGcuOJM1ZuxHK6QtDmpkvay7AlCluU1D1JsSKk8Hos90nMjObIb8byIFGNHC3MTm+/k1HmsrhhFiI57ErjbkfimDvIUyzT2KLD0ep3YCfraaTIFx/NzO/vvHex3O9kutpsdpA+ZANaG8gqD7VOEI1aFbJSyVXtX4xLVPTGH/94o08BQ9BC/6tAwaVRKfvbycz9omvYykSgyZbT6omaxePlO9/VNsr5fwg4XuV10bN5C4llJHVdUhtsikK7x2x25bQsmOTtX8aQfujfJy5mLxsM8JBqj3txkDpL6LJrZ3gjiz5BQPtKJRqTeEYkzczP5Nr8hCsNvRDrKQaoi6xmheISi+UeJUiMFWZ1KiWZqoi0hbZOrf9tK8RxtXv1aHPnUzI3/zLAnRSaX46jIIlcD5Ij20i4qGkwCtEWTqbmMkBweglpHVz/wYEbt9kZ7Nzu7sm7KfpCC6PnPdKOxSp7WJj9PmHjpkSO4qNsmtw/MjkEjGkL76TEqwV3Y4koo6OAJXHQcSWI/0cMMxIbg8ajIxorbZ92UmjxOk0R3J3vjM7oQt1+EixbjePdHWiGvEV63ORU0JMmugK6HHUGraY0zVKxsZsTgy/yNdNiJfo8vJHruhthj3YNqTtbvCl78ZtZPAN7pCu/2hbQBf8Ji7SFvigHvH97aT/bD296El5sV9RA5BIeJaNuJSe8ncEQ9woN8lByFY3AcTsAJVfQ2AqK5oZ+GvDOQn+hveN2NzIP9l78tt4UMp0B3KqzJVraNpc/ei9FywlUf4bqPcOWXZB25eoybR8ztI+YGEgsLuQP9bhf+/W70+h70RmJ+eggdRofVo+rftNyTqv8eKs8gmTyqEcZRdGKH0lI6jA6nZTSLcWjfEwr/Lbeb8k2+TWnUxekv19AdmM/S/YXglfoNGjZqLP0kKr3IwWXqCHUHzaLrO0FRLwhmm3FOiRnAbIL3O69kEa2R7mD8M6NqfebZDKp1NYzHa2ACXgsT8URYB5Nwq9KkQe8KWAmrQO7bceH2rh7zDL4iXbPdMqCe+e3F7ityq4ZnBqdY8ZWGsoauE86a++0VdBXNpnOFuBA+WyQtT1g4Kue92Ixol+3KPhLsDB16Qyh1zJiT3tjPLmg9GCkGWdEXGO0KgyHTibh9Y4EbqdPBp1p/4bivgcsOHJrcUQX3kIPREDScHkJl9DAS22zUWLQxZjDRspjJ3rHf/ftXFc8J2Etec/JQRMyx9+GhsB+Xxnfzjh3bj4eEtZPfpzkOzxrhnZqlJqn7txCOydgmnWmsboKc9AOP/2gDK6avfaT2V9z+BytjH6uC38TE5ZSSmHk+/8Jd5bvSy/zBqCPmlSGtg69AGF7vgxqHXaEn6E16mt7jN365Zu+Oe+CeuBfuHRttj8FfTbPHopRJszvFUPCPDKK9ExXHHCf/eDfrywei8V5XosXwpSpcNJAeSwt4Hn8+GsfGstTB5JeNEdIGlcfRCXQSnUKfIk9KnUXuVA5dQKJ5JBpHV9E1dAQdRcdQtvljCe6PB+CBeBAejIfgodhTa2VcG4zEo/Do9Pnj3Fi3LvOkMdoD2v0r1XnUCNfcBbVqV1uFqn+R7xhHvT5h4hOvrJbC+4pH1Gf8u55MlqJJ02YToPlEaNGyVdYRZXyqmQ6oWVyImCdlGE1+pp5Wz6hn1XPqefVz9YJ6Ub2kXlavqFfVa+p19YZ6U5XcR2yS4+PSIRzxCWHiwGL5fF04rraarqFrOSSLdqf4eioxel5Fs/qKLtCxD5gZZf83nssq15M/gBIEnibXr6Mb6GZWuR5vFmacjD7/QhJmcGgU04GAbYV9oahj+H0Bw/E7VSaoE9VJ6mT1PXWKOlWdpk5XZ6gz1Vlq6lT1i9A0M27KbUXvY4yw1jEkvIQbfCrE60FXzksRCup+8TUD50aLn/sh5bDyRcNXvEUdg3aoUh7mWR28Yt+qblNT563iK7ppMD3Dl3Si+b0Iso9ePQCTwSt9Olqjs9pF7ap2U4vV7moPtafaS+2t9lH7qv3UErW/OkBN8xEDaLoWSx8sxutuvVR52QyB3Q3+3i/rMO9bL2Ucp8UxYISEAl/sKL4MwL4s0FKZS7lYPVsuzlbnqHPVdEeSYHAxCBGcnmUc1rYNzQtGjYD8XYr4Lg1hkgTwPPUQoEr5Wkj3uf0gGXET+2/9tdjsSHQjqlStVl0002O9FFfzchBs3qIV96j1k85JZJRwmEGDn5b5dJanJD2kZasn+WPkj5wLbEMvjFlV70HQUnJknkiXDsvnmLpWyLGZtWj99BMNGkpswLFE6yg/qHFlvmdh9CMdw3plySKHrSLxZbXrbDkPFrr6LWTlOuR39X7ZWMKZmAwuiNrc0usdeJK5z3Lwi8qfpZwyuI7yRzjfW+14wRvComu18Jtvvf3X0HNygyaG2VqwSOvo+Aosx70W164jt5o5R/LFOey1/MefbvcrKcWdQp2rQx4D/Ps/BdN8CMJvJ30v5n7R4zPMAm5quIR0QJ6MxldSEOX4FdHsfM7jir/FL/74l19XrS1v38r38OfFN1qkRSVmDqQYO+QPP/9T4X8Ay6D5e+UvAAA=
[13:07:49] [Netty Epoll Client IO #1/ERROR]: Note: to get a more complete error, run with JVM argument -Dmulticonnect.storeBufsForHandler=true
[13:07:49] [Netty Epoll Client IO #1/ERROR]: Unexpectedly disconnected from server!
java.lang.NoClassDefFoundError: Could not initialize class net.earthcomputer.multiconnect.protocols.generic.TagLoader
	at net.earthcomputer.multiconnect.packets.latest.SPacketSynchronizeTags_Latest.doFixTags(SPacketSynchronizeTags_Latest.java:123) ~[multiconnect-1.6-beta.13.jar:?]
	at net.earthcomputer.multiconnect.packets.latest.SPacketSynchronizeTags_Latest$BlockGroup.fixTags(SPacketSynchronizeTags_Latest.java:64) ~[multiconnect-1.6-beta.13.jar:?]
	at net.earthcomputer.multiconnect.generated.Protocol_1_19.translateSPacketSynchronizeTags_Latest(Protocol_1_19.java:9184) ~[multiconnect-1.6-beta.13.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$0(MulticonnectClientboundTranslator.java:38) ~[multiconnect-1.6-beta.13.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils.wrapInErrorHandler(DebugUtils.java:225) ~[multiconnect-1.6-beta.13.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$1(MulticonnectClientboundTranslator.java:37) ~[multiconnect-1.6-beta.13.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketSystem$Internals.submitTranslationTask(PacketSystem.java:302) ~[multiconnect-1.6-beta.13.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$4(MulticonnectClientboundTranslator.java:36) ~[multiconnect-1.6-beta.13.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils.wrapInErrorHandler(DebugUtils.java:225) ~[multiconnect-1.6-beta.13.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.decode(MulticonnectClientboundTranslator.java:30) ~[multiconnect-1.6-beta.13.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Earthcomputer** [comment]
You didn't provide the full log which makes it hard for me to diagnose the issue, but this looks the same as https://github.com/QuiltMC/quilted-fabric-api/issues/15

**Comment by Sylonin** [comment]
Sorry
Yeah seems to be the same issue, am using Quilt.
Please feel free to delete this issue, sorry for the inconvenience
