### ISSUE TITLE
Can't connect to 2b2t

### ISSUE THREAD

**Issue by jacobwasbeast21** [Earthcomputer/multiconnect#37]
When I try to connect to 2b2t with the multiconnect mod installed
it posts this in console and disconnects me
-----
r #80/ERROR]: Couldn't connect to server
java.lang.RuntimeException: Attempted to register ID minecraft:stone_slab at different raw IDs (44, 524332)! If you're trying to override an item, use .set(), not .register()!
	at net.minecraft.class_2370.handler$zei000$setPre(class_2370.java:1142) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_2370.method_10273(class_2370.java) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_2348.method_10273(class_2348.java:24) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_2370.registerInPlace(class_2370.java:567) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Items_1_12_2.registerAliases(Items_1_12_2.java:189) ~[multiconnect.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Items_1_12_2.registerItems(Items_1_12_2.java:626) ~[multiconnect.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Protocol_1_12_2.modifyRegistry(Protocol_1_12_2.java:1549) ~[multiconnect.jar:?]
	at net.earthcomputer.multiconnect.protocols.AbstractProtocol.lambda$setup$0(AbstractProtocol.java:44) ~[multiconnect.jar:?]
	at java.util.LinkedHashMap$LinkedKeySet.forEach(Unknown Source) ~[?:1.8.0_241]
	at net.earthcomputer.multiconnect.protocols.AbstractProtocol.setup(AbstractProtocol.java:43) ~[multiconnect.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_13_2.Protocol_1_13_2.setup(Protocol_1_13_2.java:90) ~[multiconnect.jar:?]
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Protocol_1_12_2.setup(Protocol_1_12_2.java:515) ~[multiconnect.jar:?]
	at net.minecraft.class_412$1.redirect$zdd000$sendHandshake(class_412.java:600) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_412$1.run(class_412.java:68) [intermediary-minecraft-1.15.2-client.jar:?]
----------------------------
or heres the pastebin

https://pastebin.com/ZCEKDsRM

**Comment by jacobwasbeast21** [comment]
fixed aristois hack client multiconnect is not updated.
so I used new one.
