### ISSUE TITLE
1.19 Multiconnect Error

### ISSUE THREAD

**Issue by Manhhai2302** [Earthcomputer/multiconnect#380]
Kicked when place a block in 1.19 vanilla server
This is the error message:
```
[21:17:02] [Server thread/INFO]: Manhhai2302 left the game
[21:17:02] [Server thread/WARN]: handleDisconnection() called twice
[21:17:09] [Server thread/INFO]: Manhhai2302[/171.228.154.57:60336] logged in with entity id 7735 at (347.14171144917054, 108.17675927506424, 91.35409353416715)
[21:17:09] [Server thread/INFO]: Manhhai2302 joined the game
[21:17:55] [Server thread/INFO]: Manhhai2302 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(24) + length(1) exceeds writerIndex(24): PooledUnsafeDirectByteBuf(ridx: 24, widx: 24, cap: 24)
[21:17:55] [Server thread/INFO]: Manhhai2302 left the game
```

**Comment by Earthcomputer** [comment]
Hi, please can you send the client log, rather than the server log?

**Comment by TheLostSea2302** [comment]
This is the log
[2022-06-17-7.log](https://github.com/Earthcomputer/multiconnect/files/8931912/2022-06-17-7.log)
Sorry for late respond

**Comment by TheLostSea2302** [comment]
This is the important log section, i think so:

[21:14:40] [Render thread/INFO]: Connecting to hudfdfhsuk.aternos.me, 25565
[21:14:40] [Server Connector #4/INFO]: Protocol version forced to 759 (1.19)
[21:14:41] [Render thread/INFO]: New minimap session initialized!
[21:14:41] [Render thread/INFO]: New world map session initialized!
[21:14:41] [Render thread/INFO]: Started 1 worker threads
[21:14:41] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIPlugin] stage [START], registered 5 plugins: DefaultRuntimePlugin [roughlyenoughitems], DefaultClientRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems], DefaultClientPlugin [roughlyenoughitems]
[21:14:41] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIClientPlugin] stage [START], registered 2 plugins: DefaultClientRuntimePlugin [roughlyenoughitems], DefaultClientPlugin [roughlyenoughitems]
[21:14:41] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIServerPlugin] stage [START], registered 3 plugins: DefaultRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems]
[21:14:41] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIPlugin] with 2 entry types, 5 item comparators, 0 fluid comparators and 2 fluid support providers in 9ms.
[21:14:41] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIClientPlugin] with 1425 entries, 1655 displays, 1 display visibility predicates, 21 categories (Crafting, Smelting, Smoking, Blasting, Campfire, Stone Cutting, Fuel, Brewing, Composting, Stripping, Smithing, Anvil, Beacon Base, Beacon Payment, Tilling, Pathing, Waxing, Wax Scraping, Oxidizing, Oxidation Scraping, Information), 4 exclusion zones and 3 overlay deciders in 81ms.
[21:14:41] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIServerPlugin] with 4 menu infos in 5ms.
[21:14:41] [Render thread/WARN]: [REI] Suppressing Reload Plugins of stage START
[21:14:41] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIPlugin] stage [END], registered 5 plugins: DefaultRuntimePlugin [roughlyenoughitems], DefaultClientRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems], DefaultClientPlugin [roughlyenoughitems]
[21:14:41] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIClientPlugin] stage [END], registered 2 plugins: DefaultClientRuntimePlugin [roughlyenoughitems], DefaultClientPlugin [roughlyenoughitems]
[21:14:41] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIServerPlugin] stage [END], registered 3 plugins: DefaultRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems]
[21:14:41] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIPlugin] with 2 entry types, 5 item comparators, 0 fluid comparators and 2 fluid support providers in 10ms.
[21:14:41] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIClientPlugin] with 1425 entries, 1502 displays, 1 display visibility predicates, 21 categories (Crafting, Smelting, Smoking, Blasting, Campfire, Stone Cutting, Fuel, Brewing, Composting, Stripping, Smithing, Anvil, Beacon Base, Beacon Payment, Tilling, Pathing, Waxing, Wax Scraping, Oxidizing, Oxidation Scraping, Information), 4 exclusion zones and 3 overlay deciders in 59ms.
[21:14:41] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIServerPlugin] with 4 menu infos in 2ms.
[21:14:42] [Render thread/INFO]: Loaded 157 advancements
[21:14:44] [Netty Client IO #1/ERROR]: Unexpectedly disconnected from server!
java.net.SocketException: Connection reset
	at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258) ~[netty-buffer-4.1.77.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.77.Final.jar:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[21:14:44] [Render thread/INFO]: Minimap session finalized.
[21:14:44] [Render thread/INFO]: Finalizing world map session...
[21:14:45] [Thread-1/INFO]: World map force-cleaned!
[21:14:45] [Render thread/INFO]: World map session finalized.
[21:14:45] [Render thread/INFO]: Stopping worker threads

**Comment by Earthcomputer** [comment]
Can you confirm if you can connect to this server with a vanilla client?

**Comment by TheLostSea2302** [comment]
Yes
I can connect with the server with a Vanilla client, or remove the Multiconnect mods, i can connect to the server

**Comment by Earthcomputer** [comment]
If you give me permission to join a server I could try to look into it, otherwise I have no good way of debugging this issue. At first glance it looks like a server-side issue.
