### ISSUE TITLE
[1.19 -> 1.19] Joining carpet server

### ISSUE THREAD

**Issue by aria1th** [Earthcomputer/multiconnect#400]
Server carpet version matches with client carpet version, but it somehow breaks with multiconnect.

```
[19:53:55] [Netty Client IO #4/INFO]: Joined carpet server with matching carpet version
[19:53:55] [Netty Client IO #4/ERROR]: !!!!!!!! Unexpected packet error, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[19:53:55] [Netty Client IO #4/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[19:53:55] [Netty Client IO #4/ERROR]: Minecraft version: 1.19
[19:53:55] [Netty Client IO #4/ERROR]: multiconnect version: 1.6-beta.16
[19:53:55] [Netty Client IO #4/ERROR]: Server version: 759 (1.19)
[19:53:55] [Netty Client IO #4/ERROR]: Server brand: vanilla
[19:53:55] [Netty Client IO #4/ERROR]: Direction: inbound
[19:53:55] [Netty Client IO #4/ERROR]: Compressed packet data: H4sIAAAAAAAA/xPlSU4sKkgtscpIzcnJd+Uz1DPRM7fULjMyMjAzMAcADK3Yzh4AAAA=
[19:53:55] [Netty Client IO #4/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Cannot send packet Other to protocol 759 from protocol 759
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot send packet Other to protocol 759 from protocol 759
	at net.earthcomputer.multiconnect.generated.Protocol_1_19.sendToServer(Protocol_1_19.java:896) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketSystem$ProtocolClassProxy.sendToServer(PacketSystem.java:425) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketSystem.lambda$sendToServer$3(PacketSystem.java:149) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketSystem.sendToServer(PacketSystem.java:153) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.CustomPayloadHandler.forceSendIdentifierCustomPayload(CustomPayloadHandler.java:65) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.impl.APIImpl.forceSendCustomPayload(APIImpl.java:57) ~[multiconnect-1.6-beta.16.jar:?]
	at me.senseiwells.essentialclient.feature.MultiConnectSupport.sendCustomPacket(MultiConnectSupport.java:32) ~[essential-client-1.19-1.2.3-BETA-210622.jar:?]
	at carpet.network.ClientNetworkHandler.handler$zja000$onHello(ClientNetworkHandler.java:527) ~[fabric-carpet-1.19-1.4.79+v220607.jar:?]
	at carpet.network.ClientNetworkHandler.respondHello(ClientNetworkHandler.java) ~[fabric-carpet-1.19-1.4.79+v220607.jar:?]
	at carpet.network.ClientNetworkHandler.onHi(ClientNetworkHandler.java:116) ~[fabric-carpet-1.19-1.4.79+v220607.jar:?]
	at carpet.network.ClientNetworkHandler.handleData(ClientNetworkHandler.java:95) ~[fabric-carpet-1.19-1.4.79+v220607.jar:?]
	at me.senseiwells.essentialclient.feature.MultiConnectSupport.lambda$static$0(MultiConnectSupport.java:18) ~[essential-client-1.19-1.2.3-BETA-210622.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.CustomPayloadHandler.lambda$handleClientboundIdentifierCustomPayload$4(CustomPayloadHandler.java:110) ~[multiconnect-1.6-beta.16.jar:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at net.earthcomputer.multiconnect.protocols.generic.CustomPayloadHandler.handleClientboundIdentifierCustomPayload(CustomPayloadHandler.java:110) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.packets.latest.SPacketCustomPayload_Latest$Other.handle(SPacketCustomPayload_Latest.java:38) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.generated.Protocol_1_19.translateSPacketCustomPayload_Latest(Protocol_1_19.java:4108) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$0(MulticonnectClientboundTranslator.java:45) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils.wrapInErrorHandler(DebugUtils.java:226) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$1(MulticonnectClientboundTranslator.java:44) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketSystem$Internals.submitTranslationTask(PacketSystem.java:345) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$4(MulticonnectClientboundTranslator.java:43) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils.wrapInErrorHandler(DebugUtils.java:226) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.decode(MulticonnectClientboundTranslator.java:37) ~[multiconnect-1.6-beta.16.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:?]
	... 36 more
```

**Comment by Earthcomputer** [comment]
Fixed with https://github.com/Earthcomputer/multiconnect/commit/66ad91591a159b8cb9190a022fafcfd43c7c579d
