### ISSUE TITLE
[1.19 -> 1.18.2] Generic Java error when connecting to MP server

### ISSUE THREAD

**Issue by Echomercc** [Earthcomputer/multiconnect#404]
Fabric Loader 0.14.8 - Multiconnect Beta 1.6 - Minecraft Java 1.19

Attempting to connect to a confirmed 1.18.2 server throws this error in response after 'Loading terrain' text shows up. 

_"Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $"_

Minecraft game output throws the following:

```
Connecting to [IP Address], 25777
Discovered server protocol: 758 (1.18.2)
Couldn't connect to server
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.google.gson.Gson.fromJson(Gson.java:901)
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.downloadJson(AssetDownloader.java:281)
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.getVersionUrls(AssetDownloader.java:101)
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.getVersionFile(AssetDownloader.java:131)
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.getAssetUrl(AssetDownloader.java:118)
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.getLangFileUrls(AssetDownloader.java:153)
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.getLangFile(AssetDownloader.java:195)
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.getTranslations(AssetDownloader.java:213)
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.addExtraTranslations(AssetDownloader.java:70)
	at net.minecraft.class_1078.handler$zkp000$onLoad(class_1078.java:523)
	at net.minecraft.class_1078.method_4675(class_1078.java:49)
	at net.minecraft.class_1076.method_14491(class_1076.java:65)
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.reloadLanguages(AssetDownloader.java:45)
	at net.earthcomputer.multiconnect.protocols.generic.AbstractProtocol.setup(AbstractProtocol.java:44)
	at net.earthcomputer.multiconnect.connect.ConnectionHandler.onSendHandshake(ConnectionHandler.java:111)
	at net.minecraft.class_412$1.redirect$zlg000$sendHandshake(class_412.java:537)
	at net.minecraft.class_412$1.run(class_412.java:79)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 18 more
```

**Comment by Earthcomputer** [comment]
Update

**Comment by Echomercc** [comment]
> Update

Thanks, will try now
