### ISSUE TITLE
[1.19] -> [1.18 with ViaVersion] When connecting to a lot of servers it won't join

### ISSUE THREAD

**Issue by DarkReaper231** [Earthcomputer/multiconnect#405]
![2022-07-01-145720_1920x1080_scrot](https://user-images.githubusercontent.com/38611351/176899050-828f9985-668e-4b69-b8a9-4fc31dbf949c.png)

It also throws this error

```
[14:56:30] [Server Connector #21/INFO]: Discovered server protocol: 758 (1.18.2)
[14:56:30] [Server Connector #21/ERROR]: Couldn't connect to server
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:901) ~[gson-2.8.9.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.downloadJson(AssetDownloader.java:281) ~[multiconnect-1.6-beta.16-9-gc215c456.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.getVersionUrls(AssetDownloader.java:101) ~[multiconnect-1.6-beta.16-9-gc215c456.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.getVersionFile(AssetDownloader.java:131) ~[multiconnect-1.6-beta.16-9-gc215c456.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.getAssetUrl(AssetDownloader.java:118) ~[multiconnect-1.6-beta.16-9-gc215c456.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.getLangFileUrls(AssetDownloader.java:153) ~[multiconnect-1.6-beta.16-9-gc215c456.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.getLangFile(AssetDownloader.java:195) ~[multiconnect-1.6-beta.16-9-gc215c456.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.getTranslations(AssetDownloader.java:213) ~[multiconnect-1.6-beta.16-9-gc215c456.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.addExtraTranslations(AssetDownloader.java:70) ~[multiconnect-1.6-beta.16-9-gc215c456.jar:?]
	at net.minecraft.class_1078.handler$bkj000$onLoad(class_1078.java:1023) ~[client-intermediary.jar:?]
	at net.minecraft.class_1078.method_4675(class_1078.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.class_1076.method_14491(class_1076.java:65) ~[client-intermediary.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.AssetDownloader.reloadLanguages(AssetDownloader.java:45) ~[multiconnect-1.6-beta.16-9-gc215c456.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.AbstractProtocol.setup(AbstractProtocol.java:41) ~[multiconnect-1.6-beta.16-9-gc215c456.jar:?]
	at net.earthcomputer.multiconnect.connect.ConnectionHandler.onSendHandshake(ConnectionHandler.java:107) ~[multiconnect-1.6-beta.16-9-gc215c456.jar:?]
	at net.minecraft.class_412$1.redirect$bla000$sendHandshake(class_412.java:537) ~[client-intermediary.jar:?]
	at net.minecraft.class_412$1.run(class_412.java:79) [client-intermediary.jar:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[gson-2.8.9.jar:?]
	... 18 more
```

Also happens with some 1.17 servers

**Comment by Earthcomputer** [comment]
update
