### ISSUE TITLE
[1.19] -> [1.17] Placing sign throws error and crashes game

### ISSUE THREAD

**Issue by DarkReaper231** [Earthcomputer/multiconnect#406]
```
[17:40:46] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:890) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1143) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]
Caused by: java.lang.IllegalArgumentException: Cannot set property class_2758{name=rotation, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in Block{minecraft:air}
	at net.minecraft.class_2688.method_11657(class_2688.java:117) ~[client-intermediary.jar:?]
	at net.minecraft.class_498.handler$znl000$enhanced_bes$renderBakedModelSign(class_498.java:542) ~[client-intermediary.jar:?]
	at net.minecraft.class_498.method_25394(class_498.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
	... 6 more
```

**Comment by DarkReaper231** [comment]
Tried it again and also got some multiconnect error hanling
```
[17:45:17] [Netty Epoll Client IO #0/ERROR]: !!!!!!!! Unexpected packet error, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[17:45:17] [Netty Epoll Client IO #0/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[17:45:17] [Netty Epoll Client IO #0/ERROR]: Minecraft version: 1.19
[17:45:17] [Netty Epoll Client IO #0/ERROR]: multiconnect version: 1.6-beta.17
[17:45:17] [Netty Epoll Client IO #0/ERROR]: Server version: 759 (1.19)
[17:45:17] [Netty Epoll Client IO #0/ERROR]: Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:ff5727c:1644) <- §3Dream-RPG§r
[17:45:17] [Netty Epoll Client IO #0/ERROR]: Direction: inbound
[17:45:17] [Netty Epoll Client IO #0/ERROR]: Compressed packet data: H4sIAAAAAAAA/+2az28bxxWAlxJrW7IUc5aSBbZpkp2VzBq+iLtxHKMXS6Zru00imM62x9QGQqMHBw5VeIv2otqBy95K5WCvgAboyTB9Se1DAVOX3ooGKpCeixb+D3TvgX1v3pv9MSQlWVYSIN1nWx9nZud9b4ZL7or065ZVuNDv//ePk5Y1ZR17d+X9yyvvfbD8zsr5n1x+76JlWQuldl2KqXvnS5fmpTjyyTK2K1N3lkqX6rrtTRSh3eb23+ZtaC/H7UvY/oTb95awrfMInJfktTN51LyBNudR8+K8BcrDeYtjmXlHMnnOZfJYa+k8Y5k8RzhP0rYn4nrXzuk27NFYwVo7N2VN/2yl8U79g6tB40dL5y/8v+3dxEvsnbV1pWQVp60fF8aev3HrZnHywasfHWqtjYlvOGz45wgpFLinbDsC/rrYUJ01oMSBZJaNE8s2TLI5C/RQtxrSB6r5DvU4TmxxeASGbOx2VAVYBzR8SCGl49RqjriGU2vSvgb95ZptX5fCKdfgKIfmg0yqZJgHFhKq2m17TqWm8hwHOiX0Ih2y/BZqglSOI6VEu3QgjcQyZLlWk+K4Lct+GVctnXLZto/DfpTLnmwKKV3h4WzpeLZzQ00UdogHQtlzcy2JST6ea9mY+QSuEdZy/DoVcVy1pLyHP2FXbfiThIMNtwYPmtDve1Iehz2tebZsgsWvObIJc/GgazzjBv4AdRhS/8fNlupA4tquNTEtzGviKKxDEdrXJG5yVe4S15lNo63ZYoZ8wG1ms3l9BBWqzHA3/56DCzrRzLI5nFUu5+D8Rh3SqCOmGq+yt3rw/h3D9A74T33d/lO9g/K7HsH3CEzPG3ZwS/t7vd6w8X3oEy9W4rNfUw6UQV7wP1EPnjzZu4pz+Zou+V2X1+2zl+n65PeRsMU0n7ynetq7D7+fpuspgsztUR343OL+6y0mnjrVe8orxzw+e13f4NDnbed94LX8kNlL0cOl9iTTpaU/HVjEIPdQBwecTOT7Te+Jy141G4jZ0MtUzw74fc8qWK+cLR61CmNb48VDt542WpMfwV2BpOvhSPLVM4mZuuYSkx8gbdUREC8EeMUUIggoWxBAiY6YDRp43QBiC0fCEC9qAh8Q50LyAlUglSUkjdal/TOJv57QoYqVH1JLdQnFy5JEOpBFaUNKEoYz3JF4Y7/QfuzQWoDqUNQFEYWmWIpveYTUdKihvXX2UhbwzWifYKq0ygsjFUEHVmZYi6izvC5GxqzZoWaHpj9k/1y4xOuvY+aSFSq/ZR0e5s8sHp5e8s0GV8iLHbN8Qs0Keiqy+z+X7H/sXUoR/HWcgX46kLdD6KZQZxuTvAtBoHkFaMsFplQU5Gcd7zfUM8wPA2yZS55I/XpZINrsBwZcBxai/IHyKnbQH5A/ZP+criNVTz1TT1IXn1Fh6vXqcB3sXyCtvcB+yQXZakM6Qvm1bqTf3Bexq1/i7afA+0tb3WTLhQYzaKibYqE5y1NGesUwL3UIfevPBJ9gr2Cven3jPbpUxFt9uinXbfkyfoEvQtqFSsfgOjOidZ5cz3gzTPtLmto/Y5D9FfZHHeqNooSOwdS4jCLlk1iPGOK3NPfqz+Y3WYm4QKPf1lzq6KxZ/573v0Ovn0gzirlDXfUlZr1u+F/0+RfJ+2mGlU7WW9HskP9yh/1Lu/h3r2NO7D/UWzXcFUx/t3jMeto4VGgVb41NHvun83fnP6/9w+lNrY3B3YOP5whSajpEX9M3CG83CkFQI1AvYSDgnlGF1JQG2e9JTceowxViFXmaiG93q8obXCE/mk/HdVw1fFmvN+Bnj4dvdCmqAZ8LIn/A/uAq+68mfn+/fg/X7/L6Ja/fNdZPhx78/mOfQ16f/aogTTftjVlj+rXhyr2H62I2fKtS6YUqskZ+5Ffrf5uzjfZnvV+NX/DrriZ4vdyO/QN1RBHxLNM/uz9/u813BhXWVHRBo/ziz+J7QvyJ3l9eFX8VX4rvC/ixm2k1y7urKX8ttX5eVpRhvF7Dj7GLX3tDg9T/dvuuKKu0ijVOL4z0qi74FRif944DF8dPsauC91jw9xei1oHxt17Ir9l+Ab+U4KdPAkTyicAJT45a/FD/mVXqJ7af0/mHftz/z0SlJl4jNw58Voa2eM5+rENKel9Uv9BSv7tDAWdCzVUmdxDv+uz36flHDpx/vn4/1vvgMH3sz9r1gs/EmlVmmPHHdWRff7pjmH/I6z8571bN5Q74s+v3Ev/A+X8Afj+7zQn18+AR4e7g2M3iFNwdFMZatw5NFm9ObMJtgeRbR/UZhKbDlCYdptTcQ4z4KKSePBzqXwjYq7lf//CYH+JvZP2NA/S7BjOh/QFR/ZInlTi9/429+E+M4FtM32AmFhoEZrqzShz5UbD2NHehWUcmhha3gD/mL1KjTpyvk3f+ov4mYa9+fVxGG3+ImPkwOD0wv0wdsV/eUVyOk3AhJ0zu4FUZlMZjXdbv+qlPN5VPE6Kd9SZfqZhsZdt6XpsS/VIvc5m9y+n1M/HzSO0d5Te88zEz/mpIXmCbyOnRq573eorDwqyjFWQ54GfvndF+FcvMusFdI8iSlqu/Iau21tkbUXUxH9zRfjw18URSXy5pytGnzF6iKtkrI+1fH06v2my1wB9Vb+O3gsuf3iZ/xHXcZ+qNMs+3ISSlPKkU68xIc/1khG8q0CDC5Rrm/CC6ryi5rYi7eB/vG9WOpQgj3A65He43om63+zAM70cb3a5qP+R+gtxQaMkut3m49XDfxmxY1tHPJ7vdDcv6/CiU0rUO/7qrGIaIkPhwFYgD4V+IDw+HdADWoWak2DXa8YHddAcdAbcFhSPFQ9ZENL05tTE9if+5wFKBn9GOL45De2aR2jCwaF1RtE7jxao0vmgpQsd38OZqEQ4oAMs8oRRPhCNVe9waF5RBHbi4uKgOEFZqhmAWeKAgUgNl5qx5ACeIU6dp9lsmLc2CQUuzMIJ55JFHHnnk8e2IUVe6A2BBP/65frCoH7yuH6yMrZX2WbkZ28z+ztxm9vuMbHvbYD/LbYN94rZBs7+fZZ+4bZDQ3x7BPPLII4888vg2xVrpm64gjzzyyCOPPPL4+uPgPgTII4888sgjjzxeLP7w6PHvb+CDZ5sbv6KutRs89lPmBeabzDeYL339XittPX4UPdu0rH9vbjz6Ytqyth5Hz/71CgxttB99oQ4JHzxD3m7+bgJw7sPg9hEs6f36h6qk834R6XpyXLWlsFXJLn0R8aZNJpe/e+Bm/I3F5iRxi9tTzKMvu7Q88sgjjzzyyGNk/A/0UBgjhksAAA==
[17:45:17] [Netty Epoll Client IO #0/ERROR]: It's possible to create a full recording of all packets in a session by adding -Dmulticonnect.enablePacketRecorder=true to your JVM args.
[17:45:17] [Netty Epoll Client IO #0/ERROR]: For more complex problems, this may be required to diagnose the issue.
[17:45:17] [Netty Epoll Client IO #0/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Cannot invoke "net.earthcomputer.multiconnect.protocols.generic.DimensionTypeReference.getValue(net.minecraft.class_5455)" because "dimensionType" is null
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.earthcomputer.multiconnect.protocols.generic.DimensionTypeReference.getValue(net.minecraft.class_5455)" because "dimensionType" is null
	at net.earthcomputer.multiconnect.packets.latest.ChunkData_Latest.computeSectionsLength(ChunkData_Latest.java:27) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.generated.Protocol_1_19.translateSPacketChunkData_Latest(Protocol_1_19.java:3235) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$0(MulticonnectClientboundTranslator.java:45) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.debug.DebugUtils.wrapInErrorHandler(DebugUtils.java:228) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$1(MulticonnectClientboundTranslator.java:44) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketSystem$Internals.submitTranslationTask(PacketSystem.java:345) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$4(MulticonnectClientboundTranslator.java:43) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.debug.DebugUtils.wrapInErrorHandler(DebugUtils.java:228) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.decode(MulticonnectClientboundTranslator.java:37) ~[multiconnect-1.6-beta.17.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:?]
	... 28 more
[17:45:17] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:890) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1143) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]
Caused by: java.lang.IllegalArgumentException: Cannot set property class_2758{name=rotation, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in Block{minecraft:air}
	at net.minecraft.class_2688.method_11657(class_2688.java:117) ~[client-intermediary.jar:?]
	at net.minecraft.class_498.handler$znl000$enhanced_bes$renderBakedModelSign(class_498.java:542) ~[client-intermediary.jar:?]
	at net.minecraft.class_498.method_25394(class_498.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
	... 6 more
```

**Comment by Earthcomputer** [comment]
Hi, this looks like a more complicated problem than I first thought. Could you enable packet recording by adding -Dmulticonnect.enablePacketRecorder=true to your JVM args, and then send over the recording file (the path to it is logged after you disconnect from the server)?

**Comment by Earthcomputer** [comment]
OP says it fixed itself, closing
