### ISSUE TITLE
[1.19] When Warden kills you with his beam thing, it disconnects from server due to error

### ISSUE THREAD

**Issue by DarkReaper231** [Earthcomputer/multiconnect#414]
```
[16:42:25] [Netty Epoll Client IO #1/ERROR]: !!!!!!!! Unexpected packet error, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[16:42:25] [Netty Epoll Client IO #1/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[16:42:25] [Netty Epoll Client IO #1/ERROR]: Minecraft version: 1.19
[16:42:25] [Netty Epoll Client IO #1/ERROR]: multiconnect version: 1.6-beta.17
[16:42:25] [Netty Epoll Client IO #1/ERROR]: Server version: 759 (1.19)
[16:42:25] [Netty Epoll Client IO #1/ERROR]: Server brand: Spigot
[16:42:25] [Netty Epoll Client IO #1/ERROR]: Compressed packet data: H4sIAAAAAAAA/1PUYHBovjtz5gwGhgMuDQwg4LCJNfsc4/lVDJiAUSA3My81uSgxrcQqNa8ks6Ty6l5WB9lDE5gAjCiJfEgAAAA=
[16:42:25] [Netty Epoll Client IO #1/ERROR]: It's possible to create a full recording of all packets in a session by adding -Dmulticonnect.enablePacketRecorder=true to your JVM args.
[16:42:25] [Netty Epoll Client IO #1/ERROR]: For more complex problems, this may be required to diagnose the issue.
[16:42:25] [Netty Epoll Client IO #1/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(67) + length(4) exceeds writerIndex(68): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 67, widx: 68, cap: 256)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketIntrinsics.sendRawToClient(PacketIntrinsics.java:239) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$2(MulticonnectClientboundTranslator.java:52) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.debug.DebugUtils.wrapInErrorHandler(DebugUtils.java:228) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$3(MulticonnectClientboundTranslator.java:51) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketSystem$Internals.submitTranslationTask(PacketSystem.java:346) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$4(MulticonnectClientboundTranslator.java:43) ~[multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.debug.DebugUtils.wrapInErrorHandler(DebugUtils.java:228) [multiconnect-1.6-beta.17.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.decode(MulticonnectClientboundTranslator.java:37) [multiconnect-1.6-beta.17.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(67) + length(4) exceeds writerIndex(68): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 67, widx: 68, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.77.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:809) ~[netty-buffer-4.1.77.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readFloat(AbstractByteBuf.java:856) ~[netty-buffer-4.1.77.Final.jar:?]
	at net.minecraft.class_2540.readFloat(class_2540.java:1277) ~[client-intermediary.jar:?]
	at net.minecraft.class_5709$class_5710.method_32934(class_5709.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_5709$class_5710.method_32962(class_5709.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_5717.method_32963(class_5717.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_5745$1.method_33127(class_5745.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_5745$1.method_10297(class_5745.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_2675.method_11542(class_2675.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.class_2675.<init>(class_2675.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:425) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:477) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:?]
	... 41 more
```

**Comment by DarkReaper231** [comment]
![2022-07-10-164500_1920x1080_scrot](https://user-images.githubusercontent.com/38611351/178149732-67290ae7-fc97-4e68-85e1-6fe5f9052b4a.png)

**Comment by DarkReaper231** [comment]
Server IP: 82.208.17.43:27393

**Comment by Earthcomputer** [comment]
Update to beta.18, this was already fixed
