### ISSUE TITLE
Crash when opening Singleplayer with WorldeditCUI installed

### ISSUE THREAD

**Issue by VL4DST3R** [Earthcomputer/multiconnect#427]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

When having both multiconnect and WorldeditCUI installed if it try to open a SP world i get kicked out with the following stack trace:

```
java.util.concurrent.RejectedExecutionException: event executor terminated
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:932)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:834)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:825)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:815)
	at net.earthcomputer.multiconnect.impl.PacketSystem.sendToServer(PacketSystem.java:155)
	at net.earthcomputer.multiconnect.protocols.generic.CustomPayloadHandler.forceSendIdentifierCustomPayload(CustomPayloadHandler.java:65)
	at net.earthcomputer.multiconnect.impl.APIImpl.forceSendCustomPayload(APIImpl.java:57)
	at org.enginehub.worldeditcui.fabric.CUINetworking.sendUnchecked(CUINetworking.java:42)
	at org.enginehub.worldeditcui.fabric.CUINetworking.send(CUINetworking.java:33)
	at org.enginehub.worldeditcui.fabric.FabricModWorldEditCUI.helo(FabricModWorldEditCUI.java:196)
	at org.enginehub.worldeditcui.fabric.FabricModWorldEditCUI.onTick(FabricModWorldEditCUI.java:144)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.client.MinecraftClient.handler$bkd000$onEndTick(MinecraftClient:13890)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1869)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1101)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

I have also [opened a ticket on the WorldEdit CUI git repo](https://github.com/EngineHub/WorldEditCUI/issues/67) a while back but figured i should bring it here as well. If needed, a full crash report is there as well.

### Log File

**P.S.: please stop enforcing the log file field, one can just add it to the ticket itself.**

**Comment by Earthcomputer** [comment]
> P.S. please stop enforcing the log file field, you can just add it to the ticket itself.

You didn't include enough of the log, which means I don't have enough context to fix the issue.

**Comment by VL4DST3R** [comment]
> 

Full crash report was in the other thread, as i said.

Here, for redundancy:
<details>
  <summary>Click to expand</summary>

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 18.07.2022, 13:09
Description: Unexpected error

java.util.concurrent.RejectedExecutionException: event executor terminated
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:932)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:834)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:825)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:815)
	at net.earthcomputer.multiconnect.impl.PacketSystem.sendToServer(PacketSystem.java:155)
	at net.earthcomputer.multiconnect.protocols.generic.CustomPayloadHandler.forceSendIdentifierCustomPayload(CustomPayloadHandler.java:65)
	at net.earthcomputer.multiconnect.impl.APIImpl.forceSendCustomPayload(APIImpl.java:57)
	at org.enginehub.worldeditcui.fabric.CUINetworking.sendUnchecked(CUINetworking.java:42)
	at org.enginehub.worldeditcui.fabric.CUINetworking.send(CUINetworking.java:33)
	at org.enginehub.worldeditcui.fabric.FabricModWorldEditCUI.helo(FabricModWorldEditCUI.java:196)
	at org.enginehub.worldeditcui.fabric.FabricModWorldEditCUI.onTick(FabricModWorldEditCUI.java:144)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.client.MinecraftClient.handler$blj000$onEndTick(MinecraftClient:13890)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1869)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1101)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:932)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:834)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:825)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:815)
	at net.earthcomputer.multiconnect.impl.PacketSystem.sendToServer(PacketSystem.java:155)
	at net.earthcomputer.multiconnect.protocols.generic.CustomPayloadHandler.forceSendIdentifierCustomPayload(CustomPayloadHandler.java:65)
	at net.earthcomputer.multiconnect.impl.APIImpl.forceSendCustomPayload(APIImpl.java:57)
	at org.enginehub.worldeditcui.fabric.CUINetworking.sendUnchecked(CUINetworking.java:42)
	at org.enginehub.worldeditcui.fabric.CUINetworking.send(CUINetworking.java:33)
	at org.enginehub.worldeditcui.fabric.FabricModWorldEditCUI.helo(FabricModWorldEditCUI.java:196)
	at org.enginehub.worldeditcui.fabric.FabricModWorldEditCUI.onTick(FabricModWorldEditCUI.java:144)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$blj000$onEndTick(class_310.java:13890)

-- Affected level --
Details:
	All players: 1 total; [class_746['VL4DST3R'/78, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 4096, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~NULL~~
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, cullleaves/smartleaves, lambdabettergrass/default, illuminations/pixelaccurate, continuity/default, continuity/glass_pane_culling_fix, minecraft/physicsmod, loadmyresources.hiddenpack, Faithful 1.19 (Compliance).zip, Faithful 1.18 (Vizzy).zip, Redone Netherite Tools.zip, Brewing Guide.zip, Faithful Broken Items Addon.zip, Faithful Bushy Leaves.zip, Faithful Emissive.zip, Faithful Glowing Ores.zip, Faithful Loaded Bows.zip, Faithful Light Armor.zip, Faithful Honey Layers.zip, Faithful Colored Ping Indicator.zip, Faithful Camo Creepers.zip, Faithful Hunger Preview.zip, Faithful 3D Cactus.zip, Faithful Golden Wheat Short.zip, Faithful Colored Sheep Face.zip, Faithful Overlays.zip, Faithful Redstone Utility Pack.zip, Faithful Stack Items.zip, Faithful BumpMapped.zip, Tiny Reticle.zip, My TexturePack.zip, My TestPack.zip, My SoundPack.zip, LowerShields.zip, Flamier Fire.zip, SpawnEgg.zip, HD Shields.zip, Goat Scream.zip, White Enchantment Glint.zip, All Level Names 1.13.zip, Custom Totem v1.zip, Animated Entities.zip,

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1048862136 bytes (1000 MiB) / 3019898880 bytes (2880 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3,69
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 16384,00
	Memory slot #0 clockSpeed (GHz): 3,60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384,00
	Memory slot #1 clockSpeed (GHz): 3,60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384,00
	Memory slot #2 clockSpeed (GHz): 3,60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384,00
	Memory slot #3 clockSpeed (GHz): 3,60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 130975,13
	Virtual memory used (MB): 32452,75
	Swap memory total (MB): 65536,00
	Swap memory used (MB): 20,34
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 1.19-1.1.0-build.12
		advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		advancementinfo: AdvancementInfo 1.19-fabric0.53.3-1.3.1
		ambientsounds: Ambiend Sounds (Fabric) 5.2.0
		animatica: Animatica 0.5+1.19
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.9.30
		armorchroma: Armor Chroma 1.2.2
		armorsoundtweak: Armor Sound Tweak 6.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
		audio_engine_tweaks: Tweaks for Audio Engine 1.2.2
		autofish: Autofish 0.9.5
		autohud: Auto HUD 2.1+1.19
		balm-fabric: Balm 4.2.0+0
		better-resource-pack-sorting: Better Resource Pack Sorting 2.0.0+build.7
		betteradvancements: Better Advancements 0.2.1.134
		betterbiomeblend: Better Biome Blend 1.19-1.3.6-fabric
		betterf3: BetterF3 1.3.1
		betterpingdisplay: Better Ping Display 1.1.1
		betterthirdperson: Better Third Person 1.8.1
		blur: Blur (Fabric) 2.6.0
			midnightlib: MidnightLib 0.5.2
			satin: Satin 1.8.0
		bookshelf: Bookshelf 14.0.3
		borderlessmining: Borderless Mining 1.1.5+1.19
		cem: Custom Entity Models 0.7.1
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0-beta.3
		chat_heads: Chat Heads 0.6.0
		chesttracker: Chest Tracker 1.1.17
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
			whereisit: Where Is It 1.14.11
		citresewn: CIT Resewn 1.1.1+1.19
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.19
		cleardespawn: Clear Despawn 1.1.8
		clienttweaks: Client Tweaks 8.0.0
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v6 7.0.72
		colorfulsubtitles: Colorful Subtitles 1.0.0
		colormatic: Colormatic 3.1.2+mc.1.19
		continuity: Continuity 2.0.0+1.19
		controllable: Controllable 0.1
			thonkutil-base: ThonkUtil Base 1.13.1+575521ba57
		controlling: Controlling For Fabric 10.0+3
		creativecore: CreativeCore (Fabric) 2.7.2
		cullleaves: Cull Leaves 2.3.4
		custom-crosshair-mod: Custom Crosshair Mod 1.4.0-fabric
		damagetilt: Damage Tilt 1.19-fabric-0.1.2
		dark-loading-screen: Dark Loading Screen 1.6.12
		dashloader: DashLoader 4.0.0+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		dcch: DCCH 1.2
		double_hotbar: Double Hotbar 1.2.0
		draggable-resource-packs: Draggable Resource Packs 3.0.0+build.6
		dyed: Dyed 1.0.2
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		easiervillagertrading: EasierVillagerTrading 1.19-fabric0.53.3-1.5.4
			gbfabrictools: GBfabrictools 1.3.4+1.19
		effective: Effective 1.2.2
		elytra-flight-hud: Elytra Flight Hud 1.1.3
		elytraautopilot: Elytra AutoPilot 1.4.0
			completeconfig-base: completeconfig-base 2.0.0
		emojitype: Emoji Type 2.0.0+1.19
		enchdesc: EnchantmentDescriptions 11.0.4
		enhanced-searchability: Enhanced Searchability 3.0.0+build.6
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			spruceui: SpruceUI 4.0.0+1.19
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.7
		entity_texture_features: Entity Texture Features 3.1.4
		entitycollisionfpsfix: Entity Collision FPS Fix 2.0.0.0
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		equipmentcompare: Equipment Compare 1.3.1
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
		fabric: Fabric API 0.57.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fabricskyboxes: FabricSkyBoxes 0.5.6
		fabrishot: Fabrishot 1.8.0
		fallingleaves: Falling Leaves 1.12.1+1.19
		fancymenu: FancyMenu 2.10.0
		ferritecore: FerriteCore 4.2.1
		firstperson: FirstpersonModel 2.1.0
		forcecloseloadingscreen: kennytv's epic force close loading screen mod for Fabric 1.1.1
		forgeconfigapiport: Forge Config API Port 4.0.0
		freecam: Freecam 1.1.2
		goprone: GoProne 2.0.1
		highlighter: Highlighter 1.1.2
		horsedebug: Horse debug info 1.2.4
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.5
		indium: Indium 1.0.6+mc1.19
		inventoryhotswap: Inventory Hotswap 1.3.0
		inventoryprofilesnext: Inventory Profiles Next 1.5.3
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		jumpoverfences: JumpOverFences 1.16-0.0.3
		keybind_fix: Keybind Fix 1.0.0
		konkrete: Konkrete 1.3.3
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.2.6
		lightoverlay: Light Overlay 7.0.0
		lithium: Lithium 0.8.1
		loadmyresources: Load My Resources 1.0.1
		lod: Distant Horizons 1.6.5a
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
		lookaround: Lookaround! 0.11.1
		loud_leads: Loud Leads 1.0.1+mc1.19
		maptooltip: Map Tooltip 2.0.0
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.0
		moreculling: More Culling 1.19-0.5.0
			conditional-mixin: conditional mixin 0.3.0
		mousewheelie: Mouse Wheelie 1.10.0+mc1.19-pre1
			amecsapi: Amecs API 1.3.6+mc22w17a
			coat: Coat 1.0.0-beta.18+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		multiconnect: MultiConnect 1.6-beta.18
			multiconnect-api: MultiConnect API 1.6-beta.18
		nbttooltip: NBT Tooltip 1.7.0
		no-telemetry: No Telemetry 1.3.0
		nochatreports: No Chat Reports 1.19-v1.2.2
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		particlerain: Particle Rain 2.0.0
		phosphor: Phosphor 0.8.1
		physicsmod: Physics Mod 2.7.5
		pling: Pling 1.5.0
		presencefootsteps: Presence Footsteps 1.6.1
			kirin: Kirin UI 1.11.0
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		roughlyenoughitems: Roughly Enough Items 9.1.511
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		sheepsqueak: Sheep Squeak 1.0.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.9+1.19
			mm: Manningham Mills 2.3
		skinlayers: 3d Skin Layers 1.4.7-mc1.19
		slight-gui-modifications: 'Slight' GUI Modifications 2.2.0
			org_codehaus_groovy_groovy: groovy 3.0.11
			org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.11
		smoothswapping: Smooth Swapping 0.4.5
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19-1.0.6
		spellchecker: Spell Checker 2.1.0
		stepup: StepUp 1.19-fabric0.53.3-1.1
			crowdin-translate: CrowdinTranslate 1.4+1.19
		torohealth: ToroHealth Damage Indicators 1.19-fabric-1
		tpshud: TPS Hud 1.4.2+1.19
			me_obsilabor_alert: alert 1.0.6
		transparent: Transparent 5.1.0
		vectorientation: Vectorientation 1.0.1a
		waveycapes: WaveyCapes 1.2.0
		weaponmaster: YDM's Weapon Master 3.0.0
		worldeditcui: WorldEditCUI 1.19+01
		xaerominimap: Xaero's Minimap 22.12.0
		xaeroworldmap: Xaero's World Map 1.26.1
		zihusekeyboardwithmenu: UseKeyboardWithMenu 1.0.0
		zoomify: Zoomify 1.7.0
			com_github_llamalad7_mixinextras: mixinextras 0.0.10
			dev_isxander_settxi_settxi-core: settxi-core 2.3.0
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.3.0
			settxicloth: Settxi Cloth Impl 1.0.6
	Loaded Shaderpack: ComplementaryShaders v4.5.zip
		Profile: Custom (+53 options changed by user)
	Launched Version: fabric-loader-0.14.8-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.59, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, cullleaves/smartleaves, lambdabettergrass/default, illuminations/pixelaccurate, continuity/default, continuity/glass_pane_culling_fix, minecraft/physicsmod (incompatible), loadmyresources.hiddenpack (incompatible), file/Faithful 1.19 (Compliance).zip, file/Faithful 1.18 (Vizzy).zip (incompatible), file/Redone Netherite Tools.zip (incompatible), file/Brewing Guide.zip (incompatible), file/Faithful Broken Items Addon.zip (incompatible), file/Faithful Bushy Leaves.zip (incompatible), file/Faithful Emissive.zip (incompatible), file/Faithful Glowing Ores.zip (incompatible), file/Faithful Loaded Bows.zip (incompatible), file/Faithful Light Armor.zip (incompatible), file/Faithful Honey Layers.zip (incompatible), file/Faithful Colored Ping Indicator.zip (incompatible), file/Faithful Camo Creepers.zip (incompatible), file/Faithful Hunger Preview.zip (incompatible), file/Faithful 3D Cactus.zip (incompatible), file/Faithful Golden Wheat Short.zip (incompatible), file/Faithful Colored Sheep Face.zip (incompatible), file/Faithful Overlays.zip (incompatible), file/Faithful Redstone Utility Pack.zip (incompatible), file/Faithful Stack Items.zip (incompatible), file/Faithful BumpMapped.zip (incompatible), file/Faithful Smooth bow crossbow Anim.zip (incompatible), file/Megumin Hat v2.zip (incompatible), file/Tiny Reticle.zip (incompatible), file/My TexturePack.zip (incompatible), file/My TestPack.zip (incompatible), file/My SoundPack.zip (incompatible), file/LowerShields.zip (incompatible), file/Flamier Fire.zip (incompatible), file/SpawnEgg3D.zip (incompatible), file/Anime Phantoms.zip (incompatible), file/Senko Pack.zip (incompatible), file/HD Shields.zip (incompatible), file/Goat Scream.zip (incompatible), file/White Enchantment Glint.zip (incompatible), file/All Level Names 1.13.zip (incompatible), file/Custom Totem.zip (incompatible), file/Animated Entities.zip (incompatible), file/Dramatic Skys.zip (incompatible)
	Current Language: English (US)
	CPU: 24x AMD Ryzen 9 5900X 12-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['VL4DST3R'/78, l='ServerLevel[Amplified LOD Test]', x=62.80, y=63.00, z=-257.78]]
	Data Packs: vanilla, Fabric Mods, loadmyresources.hiddenpack (incompatible)
	World Generation: Stable
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), WorldEditCUI (worldeditcui), MultiConnect (multiconnect), Fabric Lifecycle Events (v1) (fabric-lifecycle-events-v1)
```
</details>

**Comment by Earthcomputer** [comment]
Why did you check the "I confirm I have the latest version of multiconnect" box if you don't have the latest version of multiconnect? You complain about the issue template, but it's literally there to deal with people like you who refuse to give the necessary information.

**Comment by VL4DST3R** [comment]
No problem, also i'm sorry, didn't mean to cause you any trouble.
I'm around if you need me to further test this issue.
