### ISSUE TITLE
Sodium Extra + Bobby causes log spam

### ISSUE THREAD

**Issue by Felix14-v2** [Earthcomputer/multiconnect#437]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

After some *random* actions I found this message spamming in the logs:

```
[Render thread/ERROR]: Error executing task on Client
java.lang.RuntimeException: class net.earthcomputer.multiconnect.protocols.v1_12.FlowerPotBlockEntity is missing a mapping! This is a bug!
	at net.minecraft.class_2586.method_38241(class_2586.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_10999(class_2586.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_38242(class_2586.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_20598(class_2818.java:380) ~[client-intermediary.jar:?]
	at de.johni0702.minecraft.bobby.FakeChunkStorage.serialize(FakeChunkStorage.java:232) ~[bobby-4.0.0.jar:?]
	at net.minecraft.class_631.saveRealChunk(class_631.java:615) ~[client-intermediary.jar:?]
	at de.johni0702.minecraft.bobby.VisibleChunksTracker.update(VisibleChunksTracker.java:29) ~[bobby-4.0.0.jar:?]
	at de.johni0702.minecraft.bobby.VisibleChunksTracker.updateCenter(VisibleChunksTracker.java:11) ~[bobby-4.0.0.jar:?]
	at net.minecraft.class_631.handler$zzb000$bobbySaveChunksBeforeMove(class_631.java:653) ~[client-intermediary.jar:?]
	at net.minecraft.class_631.method_20317(class_631.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_20320(class_634.java:2279) ~[client-intermediary.jar:?]
	at net.minecraft.class_4282.method_20321(class_4282.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_4282.method_11054(class_4282.java:6) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1095) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
```

I was able to reproduce it using these steps:
- Install Multiconnect, Bobby, Sodium and Sodium Extra
- Launch MC
- Join to play.teslacraft.org
- Log in to the server (If you don't want to create an account, I can provide my own)
- Write `/bw` several times
- Go to the lobby using `/lobby 6` (tested with 6th lobby)
- See the spam in logs

Demo: https://youtu.be/wXLnDL20TOU
Logs from this video:
[latest.log](https://github.com/Earthcomputer/multiconnect/files/9162685/latest.log)

### Log File

other [latest.log](https://github.com/Earthcomputer/multiconnect/files/9162412/latest.log) file

**Comment by Felix14-v2** [comment]
There is no log spam in the latest version, however Bobby still causes problems with the Sodium installed (invisible chunks). I will open a separate issue for this
