### ISSUE TITLE
[1.19.1 -> 1.19] sending a chat message or command causes a disconnect "An internal error occurred in your connection"

### ISSUE THREAD

**Issue by LoganDark** [Earthcomputer/multiconnect#448]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

When joining a 1.19 server such a MineHut (mc.minehut.com), trying to send any chat messages or commands results in being disconnected with an "An internal error occurred in your connection" error.

This does not happen in singleplayer/integrated servers.

<details><summary>Log (I don't use paste services)</summary>

```
[11:15:03] [main/INFO]: Loading Minecraft 1.19.1 with Fabric Loader 0.14.8
[11:15:04] [main/INFO]: Loading 6 mods:
	- fabric-resource-loader-v0 0.5.5+a6d2f785a9 via multiconnect
	- fabricloader 0.14.8
	- java 17
	- minecraft 1.19.1
	- multiconnect 1.6-beta.21
	- multiconnect-api 1.6-beta.21 via multiconnect
[11:15:04] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/LoganDark/Downloads/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[11:15:04] [main/INFO]: Compatibility level set to JAVA_16
[11:15:05] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[11:15:05] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[11:15:05] [main/WARN]: Failed to update counter. Error code: 0x800007D5
[11:15:05] [main/WARN]: Disabling further attempts to query Paging File.
[11:15:37] [main/INFO]: Building optimized datafixer
[11:15:42] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:15:42] [Render thread/INFO]: Setting user: LoganDark
[11:15:43] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[11:15:47] [Render thread/ERROR]: Failed to load Narrator libraries
[11:15:47] [Render thread/ERROR]: 32-bit version failed to load
[11:15:47] [Render thread/INFO]: Reloading ResourceManager: Default, Programmer Art (Fabric Resource Loader (v0), Fabric Loader, MultiConnect, MultiConnect API), Fabric Mods (Fabric Resource Loader (v0), Fabric Loader, MultiConnect, MultiConnect API)
[11:15:50] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[11:15:50] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[11:15:51] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on VoiceMeeter Input (VB-Audio VoiceMeeter VAIO)
[11:15:51] [Render thread/INFO]: Sound engine started
[11:15:51] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[11:15:51] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[11:15:51] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[11:15:51] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[11:15:51] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[11:15:51] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[11:15:51] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[11:15:52] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[11:15:52] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[11:15:52] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[11:15:52] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[11:15:59] [Render thread/INFO]: Connecting to mc.minehut.com, 25565
[11:15:59] [Server Connector #1/INFO]: Protocol version forced to 759 (1.19)
[11:16:25] [Worker-Bootstrap-3/INFO]: 4283 Datafixer optimizations took 48250 milliseconds
[11:16:33] [Render thread/INFO]: Connecting to mc.minehut.com, 25565
[11:16:33] [Server Connector #2/INFO]: Protocol version forced to 759 (1.19)
[11:16:34] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[11:16:34] [Worker-Bootstrap-4/INFO]: 24 Datafixer optimizations took 1 milliseconds
[11:16:35] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[11:16:35] [Render thread/INFO]: [System] [CHAT] 
[11:16:35] [Render thread/INFO]: [System] [CHAT]                                      
[11:16:35] [Render thread/INFO]: [System] [CHAT] 
[11:16:35] [Render thread/INFO]: [System] [CHAT] Welcome back LoganDark!
[11:16:35] [Render thread/INFO]: [System] [CHAT] 
[11:16:35] [Render thread/INFO]: [System] [CHAT] Try /join Golf if you haven't!
[11:16:35] [Render thread/INFO]: [System] [CHAT] 
[11:16:35] [Render thread/INFO]: [System] [CHAT]                                      
[11:16:35] [Render thread/INFO]: [System] [CHAT] 
[11:16:36] [Render thread/ERROR]: Failed to retrieve publicKey property for profile 298e1fd4-cae9-4cfa-b45a-a7b239c5e1c9
com.mojang.authlib.minecraft.InsecurePublicKeyException$InvalidException: Invalid profile public key signature
	at net.minecraft.class_7428.method_43550(class_7428.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_640.<init>(class_640.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11113(class_634.java:1622) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11721(class_2703.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11054(class_2703.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1128) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:767) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11:16:36] [Render thread/ERROR]: Failed to retrieve publicKey property for profile 4e7a98e4-72e7-48bf-8868-2fe772fac748
com.mojang.authlib.minecraft.InsecurePublicKeyException$InvalidException: Invalid profile public key signature
	at net.minecraft.class_7428.method_43550(class_7428.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_640.<init>(class_640.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11113(class_634.java:1622) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11721(class_2703.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11054(class_2703.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1128) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:767) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11:16:36] [Render thread/ERROR]: Failed to retrieve publicKey property for profile c3e0d276-cac7-4196-bbf1-49bdc14a1201
com.mojang.authlib.minecraft.InsecurePublicKeyException$InvalidException: Invalid profile public key signature
	at net.minecraft.class_7428.method_43550(class_7428.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_640.<init>(class_640.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11113(class_634.java:1622) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11721(class_2703.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11054(class_2703.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1128) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:767) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11:16:36] [Render thread/ERROR]: Failed to retrieve publicKey property for profile c95ade40-284a-4b31-98c8-91ce7c732639
com.mojang.authlib.minecraft.InsecurePublicKeyException$InvalidException: Invalid profile public key signature
	at net.minecraft.class_7428.method_43550(class_7428.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_640.<init>(class_640.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11113(class_634.java:1622) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11721(class_2703.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11054(class_2703.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1128) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:767) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11:16:36] [Render thread/ERROR]: Failed to retrieve publicKey property for profile 99dde201-15d6-4cb5-8438-e609b620ba15
com.mojang.authlib.minecraft.InsecurePublicKeyException$InvalidException: Invalid profile public key signature
	at net.minecraft.class_7428.method_43550(class_7428.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_640.<init>(class_640.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11113(class_634.java:1622) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11721(class_2703.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11054(class_2703.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1128) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:767) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11:16:36] [Render thread/ERROR]: Failed to retrieve publicKey property for profile 42fb8ac9-bf08-48d6-83ee-03e60e74311e
com.mojang.authlib.minecraft.InsecurePublicKeyException$InvalidException: Invalid profile public key signature
	at net.minecraft.class_7428.method_43550(class_7428.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_640.<init>(class_640.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11113(class_634.java:1622) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11721(class_2703.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11054(class_2703.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1128) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:767) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11:16:36] [Render thread/ERROR]: Failed to retrieve publicKey property for profile b91d4812-011d-44db-8f48-4e010c76011a
com.mojang.authlib.minecraft.InsecurePublicKeyException$InvalidException: Invalid profile public key signature
	at net.minecraft.class_7428.method_43550(class_7428.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_640.<init>(class_640.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11113(class_634.java:1622) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11721(class_2703.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11054(class_2703.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1128) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:767) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11:16:36] [Render thread/ERROR]: Failed to retrieve publicKey property for profile 32377c60-b6b1-46f2-bc95-3bcbdc01e3ed
com.mojang.authlib.minecraft.InsecurePublicKeyException$InvalidException: Invalid profile public key signature
	at net.minecraft.class_7428.method_43550(class_7428.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_640.<init>(class_640.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11113(class_634.java:1622) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11721(class_2703.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11054(class_2703.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1128) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:767) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11:16:36] [Render thread/INFO]: Loaded 4 advancements
[11:16:36] [Render thread/INFO]: [System] [CHAT] FireExtravasate just got credits for voting at https://minecraftservers.org/vote/443456! Use /voting for info.
[11:16:36] [Render thread/INFO]: [System] [CHAT] OneSockSloane: join UxBox [???? ??? ????s???? ??s? ????s?? ????] [??x???] [????s????]
[11:16:47] [Render thread/INFO]: Stopping!
```

</details>

I tried to send a chat message right before the last line of the log and got disconnected with the internal error. No information was written to the log at that point. Here is a screenshot of the error:

![image](https://user-images.githubusercontent.com/4723091/182216687-f1a8d26e-1d53-4dca-8217-5cefadf8a81e.png)

### Log File

see above

**Comment by Earthcomputer** [comment]
Does the server require secure player profiles?

**Comment by LoganDark** [comment]
I'm really not sure. MineHut runs directly on 1.19, not 1.19.1, but I don't know what proxy it's using (+ it uses ViaVersion).

**Comment by MODKILLER1001** [comment]
This is what I get 
![image](https://user-images.githubusercontent.com/17520451/182253422-502bbe58-e113-4092-af91-e434710e3b10.png)

**Comment by MODKILLER1001** [comment]
Disabling chat preview seems to fix it.

**Comment by Earthcomputer** [comment]
@MODKILLER1001 that looks like a different issue, please create a separate report for it and include the log.

**Comment by Oyssis** [comment]
Minehut supports 1.19.1 now

**Comment by LoganDark** [comment]
> Minehut supports 1.19.1 now

They didn't yesterday + their servers don't use viaversion so they often have the same issue.

**Comment by LoganDark** [comment]
@Earthcomputer have you been able to reproduce the issue? If not I can take my instance of minecraft into a debugger and try to figure out exactly which exception is happening

**Comment by LoganDark** [comment]
Nevermind it appears that since MineHut added support for 1.19.1, I can confirm the error still occurs even without multiconnect installed. Sorry for wasting the time of TWO issue trackers now (wtf...)

**Comment by LoganDark** [comment]
It appears that this is a trigger on MineHut's side - Multiconnect is not properly emulating an earlier version of the client, because real clients that are 1.19 or 1.18.2 do not get disconnected like this. ViaFabric also has the same issue. I don't think perfect emulation is a goal, but feel free to reopen this issue if you want to investigate further.
