### ISSUE TITLE
Chunks do not render (LongArray with size 8192 is bigger than allowed 2601)

### ISSUE THREAD

**Issue by StayWithMeSenpai** [Earthcomputer/multiconnect#463]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

After joining a 1.12.2 Minecraft Server (unicacity.de)
The chunks around 176 / 68 / 234 dont render

![javaw_GeI8IdyP4N](https://user-images.githubusercontent.com/39851578/184456578-66dfbb31-6f8b-4f30-a1b3-f867c0e93763.jpg)

and i get this error in the console:
`Error executing task on Client
io.netty.handler.codec.DecoderException: LongArray with size 8192 is bigger than allowed 2601
	at net.minecraft.class_2540.method_10809(class_2540.java:354)
	at net.minecraft.class_2540.method_10801(class_2540.java:347)
	at net.minecraft.class_2841.method_12326(class_2841.java:175)
	at net.minecraft.class_2826.method_12258(class_2826.java:169)
	at net.minecraft.class_2818.method_12224(class_2818.java:448)
	at net.minecraft.class_631.method_16020(class_631.java:102)
	at net.minecraft.class_634.redirect$bfl000$fixChunk(class_634.java:2521)
	at net.minecraft.class_634.method_38539(class_634.java:709)
	at net.minecraft.class_634.method_11128(class_634.java:704)
	at net.minecraft.class_2672.method_11528(class_2672.java:45)
	at net.minecraft.class_2672.method_11054(class_2672.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.class_310.method_1523(class_310.java:1129)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`

### Log File

https://pastebin.com/raw/y08Tqcej

**Comment by LuckyKuka** [comment]
I think it's Sodium's error, try without Sodium
