### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by MorningXiao** [Earthcomputer/multiconnect#512]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

When I was playing a server, the game was not responding.

### Log File

17:04:29.764 Compressed packet data: H4sIAAAAAAAA/+1bXYwb1RW+M57deNNUzLD7gKqIjk0Wsi/Im8kCD32YzM6mISFk18mspRUkKWUXKAokUY0rWqlu660MQhUUV2J5gigGEREJCeWpQqUUoqpqqUBK3miLIlTx0L5UeaiEmp5z7r3jmfH4Z3ftnVLmEObzvefc8333zJ3Z8bWdY0z52o0bN57YztgOdtPhI8fuPXL/Cee+I7OH7r3/24yxyW/++e//+vcX//lxivEINcog7mBfLx0p3ueeOOoV9++bnUtr13/t2Gpd0Zk2evB3Lytn/vGCcs1c21lVWdKmKHDQdd7QDTr6TuzXmaEYCnh07oB4XQkk0HlLIYcIkC5mMMUg9D26wpPCP3ilG7ylAIViQCZsAx8ewA8HOMI4CEJpBuTTISP+j8NJGuPDdNKlkB6FyAw5E4UaBIoi2A3Mq2MnvIRITGCAHE6ggJqcjj5GGlEKysODATIgFgwDyQ0DYQBWCV9gHgiBHODFmWFy7MF+GIih0EO5DDnK4P2GyEuBBh5lJwWKsThthTTxf1wZ/odg4CQN4uCs49MGdVsW7yhkKN+4ZRWMYRryolmW5JtuQxGzzxI4LsZaIoXoF0P89rjvF/HTMfzdeAWOi5jZCFot3CfQDfdPd0Chq09+S7yOwU78XsTfWQfUlppddHThj6IXwWidYusQp8PYc5vvXAd/GPfO8hR7++BH5N1t1kf9o3FGPP90BLvzShtvnRuECYmd67uO9RdvE/uC6F+jhBNi4MRArr/Uehq7E/4aaVl4JvgwAw8FZ66Zp9Z2Pvk/8FzwpTP/sUPvFrVBk+cjH8HAeRoKv8oKnC8T4lW76OCmDYo/ljeKvo4Wv50M/4B4o/ydzn/H+g/Jonr+b2xEoDfAnKPyxckYvnnB1wF72LaNavJ5ve7YJ/+6dfTk72/+m7f5iB6JW0Q/SBvtHbJ+o+eCDDwXrO2E54L1PRAovUOGYsow/vRurUVvsNEb/1bxdvpDM2z+Drzql5K/x3LMmzw1osryPgpeM07PZvg5nyBCQCo1L4gDTYEY1dKT94dzXHdJRMo8J1QF5kPou6U8qZbiO6Dwm2KWbcQiMsib9zEfQjOO3+czAyj7AxjSoZpBftOvrOA1w7wd+E2pOswbxSC/aIrTFuCXMxJEfc1/MPyqGqxgpP5qkDem/mrg/G+w/rHrILwO266DQEKRL7/h9Rc1/15jBmW1JZIXmF9QM4QDvyW2+EJEsg70QDAGDwTwOLC289STn76onPkwc80c6l6BIUDs34cRd6aH/Bc/aX5hSqyOreNv1yHA2FL6JM3sLyzT3mV3HzEfwZH4sB78lhVFl3gzBb4jYRWEvsIG+XtYO78WbhfCOBhb6cIf5svMiMCNTa+Dtd55deL132D6OEj+DhZ6V75Vb6iD/KfDOGSLlrhlPfhtge5g9fRtm+WvDkbGhk3yw6PBt0Ym6DME5Zp5Rj39p8yh0Sc+Nf/2orL991Nn3y5+cutHufdyVzfypJAdoN51WLvUjjvaJuOVaO16qHx8QHpWpTgM0Uw479xlx85O4XE13oI/8FmHlorIX/UH7TjJmMMuQ3IlS37MpwOPKr4KoTLsx6CsrZP+rH8QuvyDLnTpJDZLOnle8oOEHIuM4zxaDhuq7uc1+brW+FT0y6aQiu2sqldNTGqzWh75QBd0gnS9Rnpl3akf4mG+Jh+nQX7MV1VQjAN+X4xDOnOYR4V4Xg/NJF1YLxvzUj+Oy/F6VHNyXlDfLM4f8tB4eMPSeEV8YcQugH8O+JlWbDThHjN1sFi11UZzN9THIb0Km8PxtXyjCXEG+lm2uRv6VbXOkEel+ijZEUXopXrnxLxofqifOVgHRvWAeeeyNrVx3jCkqvChNI7PX1Wr+2Gd8Pk9W0T+Juir7wd9U/Z3skxtQL2hE8eTn82Bv2GTH+arvvQe1n2O6pSbaEJ+0N84pzDwgyi1CuuQ11OvYR34qQWXo9cwKa0rDdDRf0HzcjCO9NcUEUfrE9c/zGeC9L2G/Af3jUGdz9uaiby2zvWhv9EkP9RXbVxGHvCreo3m54D/pcvkh/OmNs7pNcxL9Zx4TeQ5R3oZP5+0vmBe71O989jGfp0j6SX9UCeuF+pO+Rcwf/Nm7IA17ujIPxHQdyynEj+cbORp1b/xSmA8w7phfr4+RH0xjyL056g+vL68zoH6oh5cF2J9cn243vG6w/zUT/p+2mhquZGgvqzacGCACf1ZPaDvHPl3mTj+oJvLNrVmPlBfMc9d51Ef+h3tPPJONImf6gsI/pYewO8i7i/47RgEHXj+55DfXcge4PpyI6h/e0ufw/Wh/nOOjvpyIX1C/+QU6iu+AHmbU76+Z319zSnAgF/ou+0WJ5N1pgP+/cqusE68vgnrzoEa8r9xgNfXbOlzd73K6/sT1Dcm9NH15fD65TrpA5653T5/o47+A1Sfuq9jujbZnMrcEvb79SxE5gfjXr56CeY99/jSR1ln9NLFR2u73kD9Bxs5c057NWvXir+6SPVbuAX17a7dkRsDvxOojzi/dSdUv3h9OuoDXOrobxtfcJSZiy19EDcK+mB9Hab1d/sl1De+dLX+npI9jOPzOH4e9U1Ota+n8Pntg79/P+gj/yi1Zy5S/1XS9zjow3k8Jtb/wSKOQ/0wjy76YvS/8zngoY8bb25av5Kdf+4bcP6z7zqyvo9B3DysnwOr0KmdP/pcLTd2EV4Gxp+fx/FH0d8s1PAazNqh/AXU9xfQv+2dz5feh/6RNwP+O95B/h9+vI76hvKjPsBV6AT9yL8/eyDkP6qE/RF99Xnp187H+Un/08XJurMttv5CH7Yj64s/rExOwZPtTX/VtitvF9WbtLOnTx2CJ9qqmpfbIPLzJtnOWOF21N8L+zS5QbhhUwy+KdDCzjqC701G1s1vyyyuRDuAitFCl+uhDtDRCnSJl9CbZxDQ5csH8tsX7XT8hdbClQAi/8O20OEKHT7aEnG7S2aKtxjeEL8rOlzBj2hzHQ+7QX5X8I4KXBH8Wk9+OjkQRLvGEC3REehiQBAdk/hdV6Id4JdIDsNQNDmD6CY27VKf1GzaxT7punw3m/hNwS9585xHoiPQDSBzxTy1ALps1BeKu+VcRgvNUcZ3qwVSPomuRCfKH9TBJD91RFCeQZs+PXgob6KO2x8Su+Sej/kQFkMfU2hcB3N9dEQ/dNQRKw4icyvfz9eriBWJdhZQA6RPcZbzZp6NeIse6fA8r9iRv8piPy7J2wFUzxI/21Y5S3yEdcSK2UJwVH5QJ/5Jzl/k8wb+Xwr+NZF/zeeNYk0gVlQi8buCt0ZoRvgZ56/Uxcc09Ma79bET8o8iL7afR4ToNfRLhLRjuE6esfl6wZXMkYSYNcRK3qwTnmUcKwzrjkhvcAHNwLrn62/0ZBjZ8wLXEKsCnwF+vE7WeOH53YIQO8zg3SKErNsl34c9L1DeymW6LnergfLL0b3543FQ1lFHm54eie5kOw9rujJ69pR26Lc7nln4zQ713R2nf7ZQW/j5wupCFT8xpA9mzE1+FcbOWLSP7GOf4/Jwxx63LAsRv7GNeowMbU3jJzaI3b8qI/gYjLUi2N/+vWHd41WWTUALbg0mUyxrxiszRMtaFhmtjpixOFrtWGBja5wjiowQij/G2Piy51WagItA70Ha5VXPK7/FLG9x0Wu+lbFWFr2yBzxluIMieqsrgKB2eaXsZayZpyABoFV6pIxt6+5yidpkmaiuTBRnmsAP+e5eIn5rEdowfyjGEvRk7vIuLAF/Zma57EHbmgG2C4B1z2teKHszi8t/wAF3r3ql14H/ruVHSuUHPW/GW/ZQ110eyiuVrFVUVYbxHjYrhF7Js+4pA/7Isyol7PAsj2R8YC1T05uhJuZtlnlPk46PerzfW+LtEmYF/u81Xy99Rp4mRS55TzfRBT3Ez4NLX3hyFPXBCMEvIiSNsDJmKQd7muFon79JXEFP2Wvjf7DUGiX7KscjGcP85VhXO7/XD7/3QAw/h+ub4b8ex389hj8wKsIfb33y+3ONBkv+zzrzf9iN/0pP/hNE8gG8Ot6FP2olyt2PXYkNDLGUSq2kEX5ccFdi+B9o71qXhSSVjnfk947L/iHaCYEP4uF6u3/Y/L1ss8UeisEDwq1MUw+x9Hc0qaWWWmqppZaEJfnbWjR4FOCWNAZMEZsSGbk7obwityluiBfqCbWa+I9pkj53+YTNStjchC3px/iVhK2SsNUTtrWE7ULC9uuE7Y8J2ycJ2z8TthsJW1VPWkFqqaWWWmqppbb1lkl+EyC11L7qFvMloqSuS8krfgym7xHt2S3ij/DmBG/hWETHQH9mHCND/M57j+C1l4XjWGz4sMycFV/Jnn9K9JzcUn7fbPkigV8bpzZMS58AUksteUv6MsyJh5CEdOh7bk5UR272tiR16HuO7U1SR252eS5JHUnPP+nzn+T6l08ACd8BEr8DppZaaqmlltpXy/4LZUDLMsFuAAA= 17:04:29.765 Unexpectedly disconnected from server! java.lang.OutOfMemoryError: Cannot reserve 4194304 bytes of direct buffer memory (allocated: 4235170806, limit: 4236247040) 	at java.base/java.nio.Bits.reserveMemory(Bits.java:178) 	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:121) 	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:332) 	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:649) 	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:624) 	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:203) 	at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:173) 	at io.netty.buffer.PoolArena.allocate(PoolArena.java:134) 	at io.netty.buffer.PoolArena.allocate(PoolArena.java:126) 	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:396) 	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188) 	at io.netty.buffer.UnsafeByteBufUtil.copy(UnsafeByteBufUtil.java:436) 	at io.netty.buffer.PooledUnsafeDirectByteBuf.copy(PooledUnsafeDirectByteBuf.java:216) 	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$4(MulticonnectClientboundTranslator.java:38) 	at net.earthcomputer.multiconnect.debug.DebugUtils.wrapInErrorHandler(DebugUtils.java:228) 	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.decode(MulticonnectClientboundTranslator.java:36) 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) 	at com.replaymod.recording.packet.PacketListener.channelRead(PacketListener.java:357) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Felix14-v2** [comment]
Can you reproduce this with the latest version of MultiConnect?
It resembles an incompatibility with ReplayMod, which has probably been fixed.
