### ISSUE TITLE
pick-block kick

### ISSUE THREAD

**Issue by lenrik1589** [Earthcomputer/multiconnect#54]
if in survival you pick-block block that you have in your inventory but not in hotbar it kicks you
![2020-06-09_14 38 40](https://user-images.githubusercontent.com/48890625/84143380-2655e580-aa5f-11ea-8a1b-662e10a48319.png)
 ```
[14:38:36] [Netty Epoll Client IO #1/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.class_2535.method_10761(class_2535.java:203) ~[intermediary-minecraft-1.16-pre2-client.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.io.IOException: Can't serialize unregistered packet
	at net.minecraft.class_2545.method_10838(class_2545.java:39) ~[intermediary-minecraft-1.16-pre2-client.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:15) ~[intermediary-minecraft-1.16-pre2-client.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	... 13 more
```

**Comment by Earthcomputer** [comment]
Whoops, that was a silly oversight on my part
