### ISSUE TITLE
weird crash

### ISSUE THREAD

**Issue by ayunami2000** [Earthcomputer/multiconnect#73]
```
---- Minecraft Crash Report ----
// You're mean.

Time: 7/5/20 7:06 PM
Description: Ticking entity

java.lang.IllegalArgumentException: The value 8605 is not in the specified inclusive range of 0 to 8191
	at org.apache.commons.lang3.Validate.inclusiveBetween(Validate.java:1032)
	at net.minecraft.class_3508.method_15214(class_3508.java:127)
	at net.minecraft.class_2841.method_12336(class_2841.java:124)
	at net.minecraft.class_2841.method_12328(class_2841.java:113)
	at net.minecraft.class_2826.method_12256(class_2826.java:88)
	at net.minecraft.class_2826.method_16675(class_2826.java:79)
	at net.minecraft.class_2818.method_12010(class_2818.java:257)
	at net.minecraft.class_1937.method_30092(class_1937.java:273)
	at net.minecraft.class_2248.method_9611(class_2248.java:166)
	at net.minecraft.class_2248.method_30094(class_2248.java:156)
	at net.minecraft.class_2843.method_12352(class_2843.java:113)
	at net.minecraft.class_2843.method_12356(class_2843.java:71)
	at net.minecraft.class_2818.multiconnect_onNeighborLoaded(class_2818.java:1436)
	at net.minecraft.class_631.handler$zhn001$onLoadChunkFromPacket(class_631.java:2039)
	at net.minecraft.class_631.method_16020(class_631.java:179)
	at net.minecraft.class_634.method_11128(class_634.java:783)
	at net.minecraft.class_631$$Lambda$4681/193458626.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.earthcomputer.multiconnect.protocols.v1_13_2.PendingChunkDataPackets.processPackets(PendingChunkDataPackets.java:31)
	at net.minecraft.class_631.handler$zff000$onSetChunkMapCenter(class_631.java:1081)
	at net.minecraft.class_631.method_20317(class_631.java:191)
	at net.minecraft.class_634.method_20320(class_634.java:2297)
	at net.earthcomputer.multiconnect.protocols.v1_13_2.Protocol_1_13_2.updateCameraPosition(Protocol_1_13_2.java:1439)
	at net.earthcomputer.multiconnect.protocols.v1_13_2.Protocol_1_13_2.onSendPacket(Protocol_1_13_2.java:370)
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Protocol_1_12_2.onSendPacket(Protocol_1_12_2.java:698)
	at net.minecraft.class_2535.handler$zip000$onSend(class_2535.java:1036)
	at net.minecraft.class_2535.method_10752(class_2535.java)
	at net.minecraft.class_2535.method_10743(class_2535.java:166)
	at net.minecraft.class_634.method_2883(class_634.java:859)
	at net.minecraft.class_746.method_3136(class_746.java:263)
	at net.minecraft.class_746.method_5773(class_746.java:212)
	at net.minecraft.class_638.method_18646(class_638.java:254)
	at net.minecraft.class_638$$Lambda$4005/226391371.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:603)
	at net.minecraft.class_638.method_18116(class_638.java:212)
	at net.minecraft.class_310.method_1574(class_310.java:1529)
	at net.minecraft.class_310.method_1523(class_310.java:994)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.apache.commons.lang3.Validate.inclusiveBetween(Validate.java:1032)
	at net.minecraft.class_3508.method_15214(class_3508.java:127)
	at net.minecraft.class_2841.method_12336(class_2841.java:124)
	at net.minecraft.class_2841.method_12328(class_2841.java:113)
	at net.minecraft.class_2826.method_12256(class_2826.java:88)
	at net.minecraft.class_2826.method_16675(class_2826.java:79)
	at net.minecraft.class_2818.method_12010(class_2818.java:257)
	at net.minecraft.class_1937.method_30092(class_1937.java:273)
	at net.minecraft.class_2248.method_9611(class_2248.java:166)
	at net.minecraft.class_2248.method_30094(class_2248.java:156)
	at net.minecraft.class_2843.method_12352(class_2843.java:113)
	at net.minecraft.class_2843.method_12356(class_2843.java:71)
	at net.minecraft.class_2818.multiconnect_onNeighborLoaded(class_2818.java:1436)
	at net.minecraft.class_631.handler$zhn001$onLoadChunkFromPacket(class_631.java:2039)
	at net.minecraft.class_631.method_16020(class_631.java:179)
	at net.minecraft.class_634.method_11128(class_634.java:783)
	at net.minecraft.class_631$$Lambda$4681/193458626.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.earthcomputer.multiconnect.protocols.v1_13_2.PendingChunkDataPackets.processPackets(PendingChunkDataPackets.java:31)
	at net.minecraft.class_631.handler$zff000$onSetChunkMapCenter(class_631.java:1081)
	at net.minecraft.class_631.method_20317(class_631.java:191)
	at net.minecraft.class_634.method_20320(class_634.java:2297)
	at net.earthcomputer.multiconnect.protocols.v1_13_2.Protocol_1_13_2.updateCameraPosition(Protocol_1_13_2.java:1439)
	at net.earthcomputer.multiconnect.protocols.v1_13_2.Protocol_1_13_2.onSendPacket(Protocol_1_13_2.java:370)
	at net.earthcomputer.multiconnect.protocols.v1_12_2.Protocol_1_12_2.onSendPacket(Protocol_1_12_2.java:698)
	at net.minecraft.class_2535.handler$zip000$onSend(class_2535.java:1036)
	at net.minecraft.class_2535.method_10752(class_2535.java)
	at net.minecraft.class_2535.method_10743(class_2535.java:166)
	at net.minecraft.class_634.method_2883(class_634.java:859)
	at net.minecraft.class_746.method_3136(class_746.java:263)
	at net.minecraft.class_746.method_5773(class_746.java:212)
	at net.minecraft.class_638.method_18646(class_638.java:254)
	at net.minecraft.class_638$$Lambda$4005/226391371.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 7911
	Entity Name: ayunami2000
	Entity's Exact location: 143.85, 96.00, 281.31
	Entity's Block location: World: (143,96,281), Chunk: (at 15,6,9 in 8,17; contains blocks 128,0,272 to 143,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.14, -0.08, 0.05
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:603)
	at net.minecraft.class_638.method_18116(class_638.java:212)

-- Affected level --
Details:
	All players: 1 total; [class_746['ayunami2000'/7911, l='ClientLevel', x=143.85, y=96.00, z=281.31]]
	Chunk stats: Client Chunk Cache: 18225, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (154,96,282), Chunk: (at 10,6,10 in 9,17; contains blocks 144,0,272 to 159,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 774067370 game time, 1000 day time
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.15-SNAPSHOT:0e38c66:unknown) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:616)
	at net.minecraft.class_310.method_1587(class_310.java:2181)
	at net.minecraft.class_310.method_1514(class_310.java:672)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 726092912 bytes (692 MB) / 1509949440 bytes (1440 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		bleachhack: BleachHack 13.37
		com_github_vatuu_discord-rpc: discord-rpc 1.6.2
		fabric: Fabric API 0.14.1+build.372-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c02
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a977402
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+b0993bc102
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea86602
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.2+4d66bed502
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.8.9+build.203
		minecraft: Minecraft 1.16.1
		mm: Manningham Mills 2.0
		multiconnect: MultiConnect 1.3.4
		multiconnect-api: MultiConnect API 1.3.4
		optifabric: Optifabric 1.1.0-beta2
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		wurst: Wurst Client v7.3-MC1.16.1
	Launched Version: fabric-loader-0.8.9+build.203-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre2
	OptiFine Build: 20200703-234202
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
```

as seen above i am using other mods and optifine with optifabric and two hacked clients, and this crash occurred on `play.palace.network` after walking around a very small amount.

**Comment by Earthcomputer** [comment]
Hacked clients are not supported. Try without them and open a new issue if it persists.
