### ISSUE TITLE
Looped "Joining world" for specific servers.

### ISSUE THREAD

**Issue by Kichura** [Earthcomputer/multiconnect#88]
When joining specific servers such as hypixel using multiconnect-1.3.11, The joining world text stays in place with no progression whilst latest.log reporting an register issue for ocean biome or related. (Sample: java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:worldgen/biome / minecraft:ocean] at different raw IDs (0, 174)! If you're trying to override an item, use .set(), not .register()! )

+ This includes causing the log file to endlessly grow until the user presses cancel during an connection attempt.

**Comment by Earthcomputer** [comment]
Multiconnect doesn't translate connections to `hypixel.net`. Please verify this doesn't happen on vanilla clients.

**Comment by Kichura** [comment]
^ I have tried to reproduce this issue on a vanilla client and hypixel accepts the connection just fine.

**Comment by Earthcomputer** [comment]
I just joined hypixel with multiconnect and I cannot reproduce the problem. Can you send me your log file?

**Comment by Kichura** [comment]
[main/INFO]: Connecting to mc.hypixel.net, 25565
[Server Connector #1/INFO]: Hypixel detected, protocol version forced to 751 (1.16.2)
[main/WARN]: Received invalid identifier in minecraft:register: BungeeCord (Non [a-z0-9/._-] character in path of location: minecraft:BungeeCord)
[main/FATAL]: Error executing task on Client
java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:worldgen/biome / minecraft:ocean] at different raw IDs (0, 174)! If you're trying to override an item, use .set(), not .register()!
	at net.minecraft.class_2370.handler$zjg000$setPre(class_2370.java:1155) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_2370.method_10273(class_2370.java) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_2370.register(class_2370.java:608) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_634.mda762c7$lambda$addMissingValues$0$4(class_634.java:2498) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at java.util.Optional.ifPresent(Optional.java:176) ~[?:?]
	at net.minecraft.class_634.addMissingValues(class_634.java:2498) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_634.handler$zhk002$onOnGameJoin(class_634.java:2477) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:359) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:110) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:18) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:990) [intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-MCWine-SNAPSHOT.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.1+build.205.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.1+build.205.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.1+build.205.jar:?]
[main/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at net.minecraft.class_634.method_11152(class_634.java:1819) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:65) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:10) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:990) [intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-MCWine-SNAPSHOT.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-MCWine-SNAPSHOT.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.1+build.205.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.1+build.205.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.1+build.205.jar:?]
[main/WARN]: Received invalid identifier in minecraft:register: HYP|McVersion (Non [a-z0-9/._-] character in path of location: minecraft:HYP|McVersion)

The rest of the log file repeats the same null errors over and over again.

**Comment by Earthcomputer** [comment]
Can you please attach the full log file by uploading to a site such as pastebin? I am interested in more than just the error message.

**Comment by Kichura** [comment]
https://pastebin.com/raw/kDzgH2aB - Full log is here.

**Comment by Earthcomputer** [comment]
I have managed to reproduce this but only with fabric API installed. I am looking into this further to see which mod is at fault.

**Comment by Earthcomputer** [comment]
The conditions under which it happens is on all servers where the protocol is the current version (1.16.2) when you have multiconnect and fabric API installed.

**Comment by Earthcomputer** [comment]
How did my dumb shit code even work without fabric API....

**Comment by Kichura** [comment]
I assume your mod has worked without fabric api because of some compatibility support or a related configuration.

**Comment by Earthcomputer** [comment]
https://github.com/Earthcomputer/multiconnect/releases/tag/v1.3.12

**Comment by Kichura** [comment]
Thanks for patching this issue. 😊
