### ISSUE TITLE
Error loading entity

### ISSUE THREAD

**Issue by MODKILLER1001** [Earthcomputer/multiconnect#99]
I keep getting

[20:30:45] [main/WARN]: Exception loading entity: 
net.minecraft.class_148: Loading entity NBT
	at net.minecraft.class_1297.method_5651(class_1297.java:1663) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1299.method_17839(class_1299.java:473) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_156.method_17974(class_156.java:402) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1299.method_5892(class_1299.java:472) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1299.method_17848(class_1299.java:535) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1299.method_17842(class_1299.java:516) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1917.method_8283(class_1917.java:254) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_839.method_3589(class_839.java:22) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_839.method_3569(class_839.java:12) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_824.method_23079(class_824.java:107) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_824.method_23081(class_824.java:96) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_824.method_3554(class_824.java:128) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_824.method_3555(class_824.java:96) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1260) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:727) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:546) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1023) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.2+build.206.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassCastException: net.minecraft.class_638 cannot be cast to net.minecraft.class_3218
	at net.minecraft.class_1590.method_5749(class_1590.java:200) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1297.method_5651(class_1297.java:1654) ~[intermediary-minecraft-1.16.2-client.jar:?]
	... 33 more

**Comment by Earthcomputer** [comment]
Please, for the love of god, send the whole log and not just the bit you think is useful. You have given me the one least useful bit of the log.

**Comment by MODKILLER1001** [comment]
I found the issue, mojang fucked it up https://bugs.mojang.com/browse/MC-189565
